BALL::Mainframe Class Reference
#include </Users/andreas/BALL-cmake/source/APPLICATIONS/BALLVIEW/mainframe.h>
Public Slots
void show ()
bool eventFilter (QObject *, QEvent *e)
Catch key events.
void reset ()
remove all loaded Molecules and Representations, reset Coloring options
void about ()
void howToCite ()
Public Member Functions
Mainframe (QWidget *parent=0, const char *name=0)
virtual ~Mainframe ()
Protected Attributes
Scene * scene_
Constructor & Destructor Documentation
BALL::Mainframe::Mainframe (QWidget * parent = 0, const char * name = 0)
References about(), bucky_64x64_xpm, BALL::VIEW::MainControl::BUILD, BALL::VIEW::MainControl::complement_selection_action_, BALL::VIEW::MainControl::complementSelection(), BALL::VIEW::MainControl::DISPLAY, BALL::VIEW::MainControl::DISPLAY_VIEWPOINT, BALL::VIEW::MainControl::EDIT, BALL::LogStream::error(), BALL::VIEW::MainControl::FILE, BALL::VIEW::MainControl::FILE_OPEN, BALL::Path::find(), BALL::VIEW::MainControl::HELP, howToCite(), BALL::VIEW::MainControl::initPopupMenu(), BALL::VIEW::MainControl::insertMenuEntry(), BALL::VIEW::MainControl::insertPopupMenuSeparator(), BALL::VIEW::MainControl::loadBALLViewProjectFile(), BALL::Log, BALL::VIEW::MainControl::MACRO, BALL::VIEW::MainControl::MOLECULARMECHANICS, BALL::VIEW::DatasetControl::registerController(), BALL::VIEW::ServerWidget::registerObjectCreator(), BALL::VIEW::MainControl::save_project_action_, BALL::VIEW::MainControl::saveBALLViewProjectFile(), scene_, BALL::VIEW::HelpViewer::setBaseDirectory(), BALL::VIEW::HelpViewer::setDefaultPage(), BALL::VIEW::MainControl::setLoggingFilename(), BALL::VIEW::MainControl::setMenuHint(), BALL::VIEW::HelpViewer::setProject(), BALL::VIEW::MainControl::setStatusbarText(), BALL::VIEW::HelpViewer::setWhatsThisEnabled(), BALL::VIEW::Scene::stereoBufferSupportTest(), BALL::VIEW::MainControl::stop_simulation_action_, BALL::VIEW::MainControl::stopSimulation(), BALL::VIEW::MainControl::toggleFullScreen(), BALL::VIEW::MainControl::TOOLS, BALL::VIEW::MainControl::TOOLS_PYTHON, BALL::VIEW::MainControl::USER, and BALL::VIEW::MainControl::WINDOWS.
BALL::Mainframe::~Mainframe () [virtual]
Member Function Documentation
void BALL::Mainframe::about () [slot]
References BALL_RELEASE_STRING, and BALL::Path::find().
Referenced by Mainframe().
bool BALL::Mainframe::eventFilter (QObject * sender, QEvent * e) [slot]
Catch key events.
References BALL::VIEW::CompositeManager::begin(), BALL::VIEW::MainControl::checkMenus(), BALL::VIEW::MainControl::composite_manager_, BALL::VIEW::MainControl::control_selection_, BALL::VIEW::MainControl::deleteClicked(), BALL::VIEW::MainControl::getMolecularControlSelection(), BALL::VIEW::CompositeManager::getNumberOfComposites(), BALL::VIEW::Scene::keyPressEvent(), and scene_.
void BALL::Mainframe::howToCite () [slot]
Referenced by Mainframe().
void BALL::Mainframe::reset () [slot]
remove all loaded Molecules and Representations, reset Coloring options
References BALL::VIEW::MainControl::clearData(), BALL::VIEW::COLORING_ELEMENT, BALL::VIEW::MainControl::composites_locked_, BALL::VIEW::DRAWING_MODE_SOLID, BALL::VIEW::DRAWING_PRECISION_HIGH, BALL::VIEW::MainControl::getRepresentationManager(), BALL::VIEW::MODEL_STICK, BALL::VIEW::DisplayProperties::selectColoringMethod(), BALL::VIEW::DisplayProperties::selectMode(), BALL::VIEW::DisplayProperties::selectModel(), BALL::VIEW::DisplayProperties::setDrawingPrecision(), BALL::VIEW::DisplayProperties::setSurfaceDrawingPrecision(), and BALL::VIEW::DisplayProperties::setTransparency().
void BALL::Mainframe::show () [virtual, slot]
Initialize all registered ModularWidget objects. It initializes the menu structure, the preferences dialogs and connects every ModularWidget with the MainControl. This method also creates the first menu entry FILE with its subentry EXIT to exit the application. See ModularWidget for further information concerning menu structure creation and preferences handling.
Calls registerConnectionObject()
Calls fetchPreferences()
Calls applyPreferences()
Calls insertMenuEntry()
Calls ModularWidget::initializeWidget()
Calls QMainWindow::show()
Note: Call this method to start the application.
Reimplemented from BALL::VIEW::MainControl.
References BALL::VIEW::Scene::addToolBarEntries(), BALL::VIEW::MainControl::applyPreferences(), BALL::Path::find(), BALL::VIEW::MainControl::initPopupMenu(), BALL::VIEW::MainControl::preferences_action_, BALL::VIEW::MainControl::qload_action_, BALL::VIEW::MainControl::qsave_action_, BALL::VIEW::MainControl::quickLoadConfirm(), BALL::VIEW::MainControl::quickSave(), BALL::VIEW::MainControl::restoreWindows(), scene_, BALL::VIEW::MainControl::stop_simulation_action_, and BALL::VIEW::MainControl::WINDOWS.
Referenced by main().
Member Data Documentation
Scene* BALL::Mainframe::scene_ [protected]
Referenced by eventFilter(), Mainframe(), and show().