BALL::VIEW::ColoringSettingsDialog Class Reference
[QT Dialogs]
#include <BALL/VIEW/DIALOGS/coloringSettingsDialog.h>
Public Member Functions
ColoringSettingsDialog (QWidget *parent=0, const char *name="ColoringSettings", Qt::WFlags fl=0)
Constructor.
virtual ~ColoringSettingsDialog ()
Destructor.
virtual void applySettingsTo (ColorProcessor &cp) const
virtual ColorProcessor * createColorProcessor (ColoringMethod method) const throw (Exception::InvalidOption)
virtual void getSettings (const ColorProcessor &cp)
virtual QWidget * getEntryFor (ColoringMethod method)
virtual vector< ColorRGBA > getColors (ColoringMethod method) const
Protected Slots
void middleResidueColorPressed ()
void lastResidueColorPressed ()
void firstResidueColorPressed ()
void negativeChargeColorPressed ()
void neutralChargeColorPressed ()
void positiveChargeColorPressed ()
void nullDistanceColorPressed ()
void maxDistanceColorPressed ()
void minimumTFColorPressed ()
void maximumTFColorPressed ()
void unassignedTFColorPressed ()
void minimumOccupancyColorPressed ()
void maximumOccupancyColorPressed ()
void unassignedOccupancyColorPressed ()
void helixColorPressed ()
void turnColorPressed ()
void strandColorPressed ()
void coilColorPressed ()
void forceMaxColorPressed ()
void forceMinColorPressed ()
void acidicColorPressed ()
void aromaticColorPressed ()
void basicColorPressed ()
void otherColorPressed ()
void polarColorPressed ()
void hydrophobicColorPressed ()
virtual void maxDistanceChanged ()
virtual void maxTFChanged ()
virtual void forceMaxValueChanged ()
virtual void forceMinValueChanged ()
Protected Member Functions
virtual void setDefaultValues_ ()
Protected Attributes
QColorTable * element_table_
QColorTable * residue_table_
QColorTable * chain_table_
QColorTable * molecule_table_
Detailed Description
Dialog for the molecular model coloring settings. It is inserted to the Preferences.
Constructor & Destructor Documentation
BALL::VIEW::ColoringSettingsDialog::ColoringSettingsDialog (QWidget * parent = 0, const char * name = "ColoringSettings", Qt::WFlags fl = 0)
Constructor.
virtual BALL::VIEW::ColoringSettingsDialog::~ColoringSettingsDialog () [inline, virtual]
Destructor.
Member Function Documentation
void BALL::VIEW::ColoringSettingsDialog::acidicColorPressed () [inline, protected, slot]
References BALL::VIEW::chooseColor().
virtual void BALL::VIEW::ColoringSettingsDialog::applySettingsTo (ColorProcessor & cp) const [virtual]
void BALL::VIEW::ColoringSettingsDialog::aromaticColorPressed () [inline, protected, slot]
References BALL::VIEW::chooseColor().
void BALL::VIEW::ColoringSettingsDialog::basicColorPressed () [inline, protected, slot]
References BALL::VIEW::chooseColor().
void BALL::VIEW::ColoringSettingsDialog::coilColorPressed () [inline, protected, slot]
References BALL::VIEW::chooseColor().
virtual ColorProcessor* BALL::VIEW::ColoringSettingsDialog::createColorProcessor (ColoringMethod method) const throw (Exception::InvalidOption) [virtual]
void BALL::VIEW::ColoringSettingsDialog::firstResidueColorPressed () [inline, protected, slot]
References BALL::VIEW::chooseColor().
void BALL::VIEW::ColoringSettingsDialog::forceMaxColorPressed () [inline, protected, slot]
References BALL::VIEW::chooseColor().
virtual void BALL::VIEW::ColoringSettingsDialog::forceMaxValueChanged () [protected, virtual, slot]
void BALL::VIEW::ColoringSettingsDialog::forceMinColorPressed () [inline, protected, slot]
References BALL::VIEW::chooseColor().
virtual void BALL::VIEW::ColoringSettingsDialog::forceMinValueChanged () [protected, virtual, slot]
virtual vector<ColorRGBA> BALL::VIEW::ColoringSettingsDialog::getColors (ColoringMethod method) const [virtual]
virtual QWidget* BALL::VIEW::ColoringSettingsDialog::getEntryFor (ColoringMethod method) [virtual]
virtual void BALL::VIEW::ColoringSettingsDialog::getSettings (const ColorProcessor & cp) [virtual]
void BALL::VIEW::ColoringSettingsDialog::helixColorPressed () [inline, protected, slot]
References BALL::VIEW::chooseColor().
void BALL::VIEW::ColoringSettingsDialog::hydrophobicColorPressed () [inline, protected, slot]
References BALL::VIEW::chooseColor().
void BALL::VIEW::ColoringSettingsDialog::lastResidueColorPressed () [inline, protected, slot]
References BALL::VIEW::chooseColor().
virtual void BALL::VIEW::ColoringSettingsDialog::maxDistanceChanged () [protected, virtual, slot]
void BALL::VIEW::ColoringSettingsDialog::maxDistanceColorPressed () [inline, protected, slot]
References BALL::VIEW::chooseColor().
void BALL::VIEW::ColoringSettingsDialog::maximumOccupancyColorPressed () [inline, protected, slot]
References BALL::VIEW::chooseColor().
void BALL::VIEW::ColoringSettingsDialog::maximumTFColorPressed () [inline, protected, slot]
References BALL::VIEW::chooseColor().
virtual void BALL::VIEW::ColoringSettingsDialog::maxTFChanged () [protected, virtual, slot]
void BALL::VIEW::ColoringSettingsDialog::middleResidueColorPressed () [inline, protected, slot]
References BALL::VIEW::chooseColor().
void BALL::VIEW::ColoringSettingsDialog::minimumOccupancyColorPressed () [inline, protected, slot]
References BALL::VIEW::chooseColor().
void BALL::VIEW::ColoringSettingsDialog::minimumTFColorPressed () [inline, protected, slot]
References BALL::VIEW::chooseColor().
void BALL::VIEW::ColoringSettingsDialog::negativeChargeColorPressed () [inline, protected, slot]
References BALL::VIEW::chooseColor().
void BALL::VIEW::ColoringSettingsDialog::neutralChargeColorPressed () [inline, protected, slot]
References BALL::VIEW::chooseColor().
void BALL::VIEW::ColoringSettingsDialog::nullDistanceColorPressed () [inline, protected, slot]
References BALL::VIEW::chooseColor().
void BALL::VIEW::ColoringSettingsDialog::otherColorPressed () [inline, protected, slot]
References BALL::VIEW::chooseColor().
void BALL::VIEW::ColoringSettingsDialog::polarColorPressed () [inline, protected, slot]
References BALL::VIEW::chooseColor().
void BALL::VIEW::ColoringSettingsDialog::positiveChargeColorPressed () [inline, protected, slot]
References BALL::VIEW::chooseColor().
virtual void BALL::VIEW::ColoringSettingsDialog::setDefaultValues_ () [protected, virtual]
void BALL::VIEW::ColoringSettingsDialog::strandColorPressed () [inline, protected, slot]
References BALL::VIEW::chooseColor().
void BALL::VIEW::ColoringSettingsDialog::turnColorPressed () [inline, protected, slot]
References BALL::VIEW::chooseColor().
void BALL::VIEW::ColoringSettingsDialog::unassignedOccupancyColorPressed () [inline, protected, slot]
References BALL::VIEW::chooseColor().
void BALL::VIEW::ColoringSettingsDialog::unassignedTFColorPressed () [inline, protected, slot]
References BALL::VIEW::chooseColor().
Member Data Documentation
QColorTable* BALL::VIEW::ColoringSettingsDialog::chain_table_ [protected]
QColorTable* BALL::VIEW::ColoringSettingsDialog::element_table_ [protected]
QColorTable* BALL::VIEW::ColoringSettingsDialog::molecule_table_ [protected]
QColorTable* BALL::VIEW::ColoringSettingsDialog::residue_table_ [protected]