BALL::TContourSurface< T > Class Template Reference
[Miscellaneous]
#include <BALL/DATATYPE/contourSurface.h>
Classes
class Cube
Public Types
Type definitions
typedef std::pair< Position,
Position > KeyType
typedef Vector3 PointType
typedef std::vector< std::pair
< PointType, std::pair
< Position, Position > > > VectorType
Public Member Functions
Constructors and Destructors.
TContourSurface ()
Default constructor.
TContourSurface (T threshold)
Constructor with threshold.
TContourSurface (const TContourSurface &surface)
Copy constructor.
TContourSurface (const TRegularData3D< T > &data, T threshold=0.0)
Constructor for TRegularData3D.
virtual ~TContourSurface ()
Destructor.
Assignment
const TContourSurface & operator= (const TContourSurface< T > &surface)
Assignment operator.
const TContourSurface< T > & operator<< (const TRegularData3D< T > &data)
Create a contour surface from a given data set.
virtual void clear ()
Clear method.
Predicates
bool operator== (const TContourSurface< T > &surface) const
Equality operator.
Protected Member Functions
void addTriangles_ (Cube &cube, const FacetArray &facet_data)
void computeTriangles (Size topology, const TRegularData3D< T > &data)
Protected Attributes
T threshold_
The threshold separating inside and outside.
HashMap< std::pair< Position,
Position >, Position > cut_hash_map_
Detailed Description
template<typename T>
class BALL::TContourSurface< T >
This class contains a contour surface. Contour surfaces are created from 3D (volume) data sets, in general from data sets store in RegularData3D using a marching cube algorithm.
Member Typedef Documentation
template<typename T> typedef std::pair<Position, Position> BALL::TContourSurface< T >::KeyType
template<typename T> typedef Vector3 BALL::TContourSurface< T >::PointType
The point type. This type is used to store points in the 3-d regularData.
template<typename T> typedef std::vector<std::pair<PointType, std::pair<Position, Position> > > BALL::TContourSurface< T >::VectorType
The vector type. This type is used to store the edge points of the contour-Surface.
Constructor & Destructor Documentation
template<typename T > BALL::TContourSurface< T >::TContourSurface () [inline]
Default constructor.
template<typename T > BALL::TContourSurface< T >::TContourSurface (T threshold) [inline]
Constructor with threshold.
template<typename T > BALL::TContourSurface< T >::TContourSurface (const TContourSurface< T > & surface) [inline]
Copy constructor.
template<typename T > BALL::TContourSurface< T >::TContourSurface (const TRegularData3D< T > & data, T threshold = 0.0) [inline]
Constructor for TRegularData3D.
References BALL::TContourSurface< T >::operator<<().
template<typename T > BALL::TContourSurface< T >::~TContourSurface () [inline, virtual]
Destructor.
Member Function Documentation
template<typename T> void BALL::TContourSurface< T >::addTriangles_ (Cube & cube, const FacetArray & facet_data) [protected]
Referenced by BALL::TContourSurface< T >::operator<<().
template<typename T > void BALL::TContourSurface< T >::clear () [inline, virtual]
Clear method.
Reimplemented from BALL::TSurface< float >.
References BALL::TContourSurface< T >::cut_hash_map_.
Referenced by BALL::TContourSurface< T >::operator<<().
template<typename T> void BALL::TContourSurface< T >::computeTriangles (Size topology, const TRegularData3D< T > & data) [protected]
template<typename T > const TContourSurface< T > & BALL::TContourSurface< T >::operator<< (const TRegularData3D< T > & data) [inline]
Create a contour surface from a given data set.
References BALL::TContourSurface< T >::addTriangles_(), BALL::TContourSurface< T >::clear(), BALL::getContourSurfaceFacetData(), BALL::TRegularData3D< ValueType >::getOrigin(), BALL::TRegularData3D< ValueType >::getSize(), BALL::TSurface< float >::normal, BALL::TContourSurface< T >::Cube::setTo(), BALL::TContourSurface< T >::Cube::shift(), and BALL::TContourSurface< T >::threshold_.
Referenced by BALL::TContourSurface< T >::TContourSurface().
template<typename T > const TContourSurface< T > & BALL::TContourSurface< T >::operator= (const TContourSurface< T > & surface) [inline]
Assignment operator.
References BALL::TContourSurface< T >::threshold_.
template<typename T > bool BALL::TContourSurface< T >::operator== (const TContourSurface< T > & surface) const [inline]
Equality operator.
References BALL::TContourSurface< T >::threshold_.
Member Data Documentation
template<typename T> HashMap<std::pair<Position, Position>, Position> BALL::TContourSurface< T >::cut_hash_map_ [protected]
Referenced by BALL::TContourSurface< T >::clear().
template<typename T> T BALL::TContourSurface< T >::threshold_ [protected]
The threshold separating inside and outside.
Referenced by BALL::TContourSurface< T >::operator<<(), BALL::TContourSurface< T >::operator=(), and BALL::TContourSurface< T >::operator==().