BALL::VIEW::DemoTutorialDialog Class Reference
#include </Users/andreas/BALL-cmake/source/APPLICATIONS/BALLVIEW/demoTutorialDialog.h>
Public Slots
void show ()
Show and raise the dialog.
void showDemo ()
void showTutorial ()
void nextStepClicked ()
Next Step.
virtual void checkMenu (MainControl &main_control)
Public Member Functions
DemoTutorialDialog (QWidget *parent=NULL, const char *name=NULL)
Default Constructor.
virtual ~DemoTutorialDialog ()
Destructor.
virtual void onNotify (Message *message)
Message handling method.
virtual void initializeWidget (MainControl &main_control)
void setDemoMode (bool state)
Protected Member Functions
void nextStepDemo_ ()
void nextStepTutorial_ ()
void initDemo_ ()
void initTutorial_ ()
void enableNextStep_ ()
virtual void onNotifyTutorial_ (Message *message)
virtual void onNotifyDemo_ (Message *message)
String getBaseDir_ ()
Private Attributes
List< Composite * > composites_
RegularData3D * grid_
System * system_
String prefix_
bool demo_mode_
Position current_step_
Mesh * surface_
QAction * demo_action_
QAction * tutorial_action_
Detailed Description
Dialog for showing a demo and tutorial.
Constructor & Destructor Documentation
BALL::VIEW::DemoTutorialDialog::DemoTutorialDialog (QWidget * parent = NULL, const char * name = NULL)
Default Constructor.
References BALL::LogStream::error(), BALL::Log, nextStepClicked(), and BALL::VIEW::ModularWidget::registerWidget().
BALL::VIEW::DemoTutorialDialog::~DemoTutorialDialog () [virtual]
Destructor.
References BALL::LogStream::error(), BALL::Log, and surface_.
Member Function Documentation
void BALL::VIEW::DemoTutorialDialog::checkMenu (MainControl & main_control) [virtual, slot]
Menu checking method. This method is called MainControl::checkMenus before a popup menu is shown. It should be used to update the state of menu entries (e.g. disable or enable entries).
Parameters:
main_control the MainControl object whose menus should be checked
Reimplemented from BALL::VIEW::ModularWidget.
References demo_action_, BALL::VIEW::MainControl::isBusy(), and tutorial_action_.
void BALL::VIEW::DemoTutorialDialog::enableNextStep_ () [protected]
Referenced by onNotifyDemo_(), and onNotifyTutorial_().
String BALL::VIEW::DemoTutorialDialog::getBaseDir_ () [protected]
References BALL::Path::find(), and BALL::FileSystem::PATH_SEPARATOR.
Referenced by initDemo_(), and initTutorial_().
void BALL::VIEW::DemoTutorialDialog::initDemo_ () [protected]
References getBaseDir_(), prefix_, and show().
Referenced by show().
void BALL::VIEW::DemoTutorialDialog::initializeWidget (MainControl & main_control) [virtual]
Initialize the widget. This method is called automatically immediately before the main application is started. It should add the widget's menu entries and connections (if required). This method will be called by MainControl::show.
Parameters:
main_control the MainControl object to be initialized with this ModularWidget
See also:
finalizeWidget()
Reimplemented from BALL::VIEW::ModularWidget.
References demo_action_, BALL::VIEW::ModularWidget::getMainControl(), BALL::VIEW::MainControl::HELP, BALL::VIEW::ModularWidget::insertMenuEntry(), BALL::VIEW::MainControl::insertPopupMenuSeparator(), BALL::VIEW::ModularWidget::setMenuHint(), showDemo(), showTutorial(), and tutorial_action_.
void BALL::VIEW::DemoTutorialDialog::initTutorial_ () [protected]
References getBaseDir_(), BALL::VIEW::ModularWidget::getMainControl(), and prefix_.
Referenced by show().
void BALL::VIEW::DemoTutorialDialog::nextStepClicked () [slot]
Next Step.
References current_step_, demo_mode_, nextStepDemo_(), prefix_, BALL::VIEW::HelpViewer::showHelp(), and showTutorial().
Referenced by DemoTutorialDialog().
void BALL::VIEW::DemoTutorialDialog::nextStepDemo_ () [protected]
References BALL::Composite::apply(), BALL::VIEW::ModifyRepresentationDialog::applyPressed(), BALLVIEW_DEBUG, BALL::VIEW::MolecularStructure::calculateFDPB(), BALL::VIEW::MolecularStructure::calculateHBonds(), BALL::VIEW::MolecularStructure::chooseAmberFF(), BALL::VIEW::COLORING_ELEMENT, BALL::VIEW::COLORING_RESIDUE_INDEX, BALL::VIEW::COLORING_SECONDARY_STRUCTURE, BALL::VIEW::COLORING_TEMPERATURE_FACTOR, composites_, BALL::VIEW::RegularData3DController::computeIsoContourSurface(), BALL::VIEW::RepresentationManager::createRepresentation(), current_step_, BALL::VIEW::DRAWING_PRECISION_HIGH, BALL::VIEW::DisplayProperties::enableCreationForNewMolecules(), BALL::LogStream::error(), BALL::Path::find(), BALL::VIEW::MolecularStructure::getAmberConfigurationDialog(), BALL::VIEW::DatasetController::getDatasets(), BALL::Exception::FileNotFound::getFilename(), BALL::VIEW::ModularWidget::getFragmentDB(), BALL::VIEW::ModularWidget::getMainControl(), BALL::VIEW::MolecularStructure::getMDSimulationDialog(), BALL::VIEW::MolecularStructure::getMinimizationDialog(), BALL::VIEW::MainControl::getMolecularControlSelection(), BALL::VIEW::RepresentationManager::getNumberOfRepresentations(), BALL::VIEW::MainControl::getRepresentationManager(), BALL::VIEW::RepresentationManager::getRepresentations(), grid_, BALL::VIEW::MainControl::insert(), BALL::VIEW::Representation::insert(), BALL::Log, BALL::VIEW::MolecularStructure::MDSimulation(), BALL::VIEW::MODEL_CARTOON, BALL::VIEW::MODEL_HBONDS, BALL::VIEW::MODEL_SA_SURFACE, BALL::VIEW::MODEL_SE_SURFACE, BALL::VIEW::MODEL_STICK, BALL::VIEW::MODEL_VDW, BALL::VIEW::ConnectionObject::notify_(), BALL::VIEW::MolecularFileDialog::openMolecularFile(), BALL::VIEW::MainControl::remove(), BALL::VIEW::AmberConfigurationDialog::resetOptions(), BALL::VIEW::MolecularStructure::runMinimization(), BALL::VIEW::DisplayProperties::setDrawingPrecision(), BALL::VIEW::ModifyRepresentationDialog::setGrid(), BALL::VIEW::MinimizationDialog::setMaxGradient(), BALL::VIEW::MinimizationDialog::setMaxIterations(), BALL::VIEW::ModifyRepresentationDialog::setMaxValue(), BALL::VIEW::ModifyRepresentationDialog::setMinValue(), BALL::VIEW::ModifyRepresentationDialog::setMode(), BALL::VIEW::Representation::setModelType(), BALL::VIEW::MainControl::setMultithreading(), BALL::VIEW::MolecularDynamicsDialog::setNumberOfSteps(), BALL::VIEW::MinimizationDialog::setRefresh(), BALL::VIEW::ModifyRepresentationDialog::setRepresentation(), BALL::VIEW::MolecularDynamicsDialog::setTimeStep(), surface_, system_, BALL::VIEW::RegularData3DController::type, and BALL::VIEW::MainControl::update().
Referenced by nextStepClicked().
void BALL::VIEW::DemoTutorialDialog::nextStepTutorial_ () [protected]
void BALL::VIEW::DemoTutorialDialog::onNotify (Message * message) [virtual]
Message handling method.
Reimplemented from BALL::VIEW::ConnectionObject.
References demo_mode_, onNotifyDemo_(), and onNotifyTutorial_().
void BALL::VIEW::DemoTutorialDialog::onNotifyDemo_ (Message * message) [protected, virtual]
References BALLVIEW_DEBUG, current_step_, enableNextStep_(), BALL::TRegularData3D< ValueType >::getData(), BALL::VIEW::DatasetMessage::getDataset(), BALL::VIEW::RepresentationMessage::getType(), BALL::VIEW::SceneMessage::getType(), grid_, BALL::VIEW::SceneMessage::REBUILD_DISPLAY_LISTS, BALL::VIEW::RegularData3DController::type, and BALL::VIEW::RepresentationMessage::UPDATE.
Referenced by onNotify().
void BALL::VIEW::DemoTutorialDialog::onNotifyTutorial_ (Message * message) [protected, virtual]
References BALL::VIEW::DatasetMessage::ADD, BALL::VIEW::RepresentationMessage::ADD_TO_GEOMETRIC_CONTROL, BALLVIEW_DEBUG, BALL::VIEW::CompositeMessage::CHANGED_COMPOSITE, current_step_, enableNextStep_(), BALL::LogStream::error(), BALL::VIEW::DatasetMessage::getDataset(), BALL::VIEW::Representation::getModelType(), BALL::VIEW::RepresentationMessage::getRepresentation(), BALL::VIEW::RepresentationMessage::getType(), BALL::VIEW::DatasetMessage::getType(), BALL::VIEW::Dataset::getType(), BALL::VIEW::CompositeMessage::getType(), BALL::Log, BALL::VIEW::MODEL_CONTOUR_SURFACE, BALL::VIEW::MODEL_SE_SURFACE, BALL::VIEW::CompositeMessage::NEW_MOLECULE, BALL::VIEW::TUTORIAL_CS, BALL::VIEW::TUTORIAL_ES, BALL::VIEW::TUTORIAL_HIERARCHY, BALL::VIEW::TUTORIAL_MDS, BALL::VIEW::TUTORIAL_PEPTIDE, BALL::VIEW::TUTORIAL_ROTATE, BALL::VIEW::TUTORIAL_SES, BALL::VIEW::TUTORIAL_SES_COLORING, BALL::VIEW::TUTORIAL_TRAJECTORY, BALL::VIEW::RegularData3DController::type, BALL::VIEW::TrajectoryController::type, and BALL::VIEW::RepresentationMessage::UPDATE.
Referenced by onNotify().
void BALL::VIEW::DemoTutorialDialog::setDemoMode (bool state) [inline]
References demo_mode_.
void BALL::VIEW::DemoTutorialDialog::show () [slot]
Show and raise the dialog.
References current_step_, demo_mode_, initDemo_(), initTutorial_(), and prefix_.
Referenced by initDemo_(), showDemo(), and showTutorial().
void BALL::VIEW::DemoTutorialDialog::showDemo () [slot]
References demo_mode_, and show().
Referenced by initializeWidget().
void BALL::VIEW::DemoTutorialDialog::showTutorial () [slot]
References demo_mode_, and show().
Referenced by initializeWidget(), and nextStepClicked().
Member Data Documentation
List<Composite*> BALL::VIEW::DemoTutorialDialog::composites_ [private]
Referenced by nextStepDemo_().
Position BALL::VIEW::DemoTutorialDialog::current_step_ [private]
Referenced by nextStepClicked(), nextStepDemo_(), onNotifyDemo_(), onNotifyTutorial_(), and show().
QAction* BALL::VIEW::DemoTutorialDialog::demo_action_ [private]
Referenced by checkMenu(), and initializeWidget().
bool BALL::VIEW::DemoTutorialDialog::demo_mode_ [private]
Referenced by nextStepClicked(), onNotify(), setDemoMode(), show(), showDemo(), and showTutorial().
RegularData3D* BALL::VIEW::DemoTutorialDialog::grid_ [private]
Referenced by nextStepDemo_(), and onNotifyDemo_().
String BALL::VIEW::DemoTutorialDialog::prefix_ [private]
Referenced by initDemo_(), initTutorial_(), nextStepClicked(), and show().
Mesh* BALL::VIEW::DemoTutorialDialog::surface_ [private]
Referenced by nextStepDemo_(), and ~DemoTutorialDialog().
System* BALL::VIEW::DemoTutorialDialog::system_ [private]
Referenced by nextStepDemo_().
QAction * BALL::VIEW::DemoTutorialDialog::tutorial_action_ [private]
Referenced by checkMenu(), and initializeWidget().