BALL::Path Class Reference
[Operating system support]
#include <BALL/SYSTEM/path.h>
Public Member Functions
string getDataPath ()
void setDataPath (const string &path)
void addDataPath (const string &path)
string getDefaultDataPath ()
string find (const string &name)
string findStrict (const string &name)
void reset ()
Reset the path variable to its default state (as it was a the start of the application).
Constructors and Destructors
Path ()
Protected Member Functions
void buildPathArray_ ()
Static Protected Attributes
static string path_
static bool path_array_valid_
static bool environment_checked_
static std::vector< std::string > path_array_
static bool initialized_
Detailed Description
Data path management class. This class is intended to provide a unique interface to directories where the data files needed by BALL reside.
Path is a singleton, so there is only one unique application-wide instance of and changes to this will be seen by all classes using path.
Constructor & Destructor Documentation
BALL::Path::Path ()
Default constructor
Member Function Documentation
void BALL::Path::addDataPath (const string & path)
Add a single path to the list of paths.
Parameters:
path the path to be added to the path list
void BALL::Path::buildPathArray_ () [protected]
string BALL::Path::find (const string & name)
Returns the full path to a file residing in one of the data directories. If a file that matches the name is not found, an empty string is returned. Directories are searched in the order of occurence in the data path. If name contains relative path information but no file matching this path could be found, another search is performed as a second step taking in account only the basename of the file.
E.g.:
Specifying data/test.dat will search for data/test.dat in each data directory first. If this search doesn't yield a match, find will search for a file named test.dat in each of the directories.
If this behaviour is not desired, try findStrict instead.
Referenced by BALL::Mainframe::about(), BALL::VIEW::DemoTutorialDialog::getBaseDir_(), BALL::Mainframe::Mainframe(), BALL::VIEW::DemoTutorialDialog::nextStepDemo_(), and BALL::Mainframe::show().
string BALL::Path::findStrict (const string & name)
Returns the full path to a file residing in one of the data directories.
See also:
find
string BALL::Path::getDataPath ()
Return a list of paths to the BALL data directories. This directory is set to a default value at compile time of the library. It may be overridden at runtime by setting the environment variable "BALL_DATA" to the desired value. This value is then prepended to the list of directories. Directories are separated by linefeeds and returned as a single string. To locate files in these directories, find will search the directories in the specified order.
The default path may be accessed using getDefaultDataPath . The path may also be modified at runtime by calling setDataPath .
The path contains a newline ("\n") separated list of paths that are searched in the order of occurence.
string BALL::Path::getDefaultDataPath ()
Returns the default data path compiled into the library. This method ignores possible contents of the environment variable "BALL\_DATA".
void BALL::Path::reset ()
Reset the path variable to its default state (as it was a the start of the application).
void BALL::Path::setDataPath (const string & path)
Modify the data path. This method accepts a newline separated list of paths to specify data paths.
Member Data Documentation
bool BALL::Path::environment_checked_ [static, protected]
bool BALL::Path::initialized_ [static, protected]
string BALL::Path::path_ [static, protected]
std::vector<std::string> BALL::Path::path_array_ [static, protected]
bool BALL::Path::path_array_valid_ [static, protected]