BALL::HashMap< Key, T > Class Template Reference
HashMap class based on the STL map (containing serveral convenience functions).
#include <BALL/DATATYPE/hashMap.h>
Classes
class IllegalKey
HashMap illegal key exception.
Public Types
OpenMS style typedefs
typedef BALL_MAP_NAME Base
typedef Base::value_type ValueType
typedef Key KeyType
typedef Base::value_type * PointerType
typedef Base::iterator Iterator
typedef Base::const_iterator ConstIterator
Public Member Functions
bool has (const Key &key) const
Test whether the map contains the given key.
const T & operator[] (const Key &key) const
Return a constant reference to the element whose key is key.
T & operator[] (const Key &key)
Return a mutable reference to the element whose key is key. If an element with the key key does not exist, it is inserted.
bool operator== (const HashMap< Key, T > &rhs) const
Equality operator. Check whether two two hashmaps contain the same elements. O(n) runtime.
Size size () const
Detailed Description
template<class Key, class T>
class BALL::HashMap< Key, T >
HashMap class based on the STL map (containing serveral convenience functions).
Member Typedef Documentation
template<class Key, class T> typedef BALL_MAP_NAME BALL::HashMap< Key, T >::Base
template<class Key, class T> typedef Base::const_iterator BALL::HashMap< Key, T >::ConstIterator
Reimplemented in BALL::StringHashMap< Value >, BALL::StringHashMap< list< Position > >, BALL::StringHashMap< NameMap >, BALL::StringHashMap< JCAMPValue >, BALL::StringHashMap< Position >, BALL::StringHashMap< Atom::Type >, BALL::StringHashMap< Ring >, BALL::StringHashMap< CreateMethod >, BALL::StringHashMap< Index >, BALL::StringHashMap< List< String >::Iterator >, BALL::StringHashMap< float >, BALL::StringHashMap< double(*)(double)>, BALL::StringHashMap< RuleList >, BALL::StringHashMap< Vector3 >, BALL::StringHashMap< SectionIterator >, BALL::StringHashMap< double * >, BALL::StringHashMap< Elements_ >, BALL::StringHashMap< vector< Position > >, BALL::StringHashMap< vector< Data > >, BALL::StringHashMap< CreationMethod >, BALL::StringHashMap< EmbeddableVector >, BALL::StringHashMap< StringHashMap< StringHashMap< std::multimap< float, AtomNames_ > > > >, BALL::StringHashMap< String >, BALL::StringHashMap< GAFFCESParser * >, BALL::StringHashMap< block >, and BALL::StringHashMap< ColorRGBA >.
template<class Key, class T> typedef Base::iterator BALL::HashMap< Key, T >::Iterator
Reimplemented in BALL::StringHashMap< Value >, BALL::StringHashMap< list< Position > >, BALL::StringHashMap< NameMap >, BALL::StringHashMap< JCAMPValue >, BALL::StringHashMap< Position >, BALL::StringHashMap< Atom::Type >, BALL::StringHashMap< Ring >, BALL::StringHashMap< CreateMethod >, BALL::StringHashMap< Index >, BALL::StringHashMap< List< String >::Iterator >, BALL::StringHashMap< float >, BALL::StringHashMap< double(*)(double)>, BALL::StringHashMap< RuleList >, BALL::StringHashMap< Vector3 >, BALL::StringHashMap< SectionIterator >, BALL::StringHashMap< double * >, BALL::StringHashMap< Elements_ >, BALL::StringHashMap< vector< Position > >, BALL::StringHashMap< vector< Data > >, BALL::StringHashMap< CreationMethod >, BALL::StringHashMap< EmbeddableVector >, BALL::StringHashMap< StringHashMap< StringHashMap< std::multimap< float, AtomNames_ > > > >, BALL::StringHashMap< String >, BALL::StringHashMap< GAFFCESParser * >, BALL::StringHashMap< block >, and BALL::StringHashMap< ColorRGBA >.
template<class Key, class T> typedef Key BALL::HashMap< Key, T >::KeyType
template<class Key, class T> typedef Base::value_type* BALL::HashMap< Key, T >::PointerType
template<class Key, class T> typedef Base::value_type BALL::HashMap< Key, T >::ValueType
Reimplemented in BALL::StringHashMap< Value >, BALL::StringHashMap< list< Position > >, BALL::StringHashMap< NameMap >, BALL::StringHashMap< JCAMPValue >, BALL::StringHashMap< Position >, BALL::StringHashMap< Atom::Type >, BALL::StringHashMap< Ring >, BALL::StringHashMap< CreateMethod >, BALL::StringHashMap< Index >, BALL::StringHashMap< List< String >::Iterator >, BALL::StringHashMap< float >, BALL::StringHashMap< double(*)(double)>, BALL::StringHashMap< RuleList >, BALL::StringHashMap< Vector3 >, BALL::StringHashMap< SectionIterator >, BALL::StringHashMap< double * >, BALL::StringHashMap< Elements_ >, BALL::StringHashMap< vector< Position > >, BALL::StringHashMap< vector< Data > >, BALL::StringHashMap< CreationMethod >, BALL::StringHashMap< EmbeddableVector >, BALL::StringHashMap< StringHashMap< StringHashMap< std::multimap< float, AtomNames_ > > > >, BALL::StringHashMap< String >, BALL::StringHashMap< GAFFCESParser * >, BALL::StringHashMap< block >, and BALL::StringHashMap< ColorRGBA >.
Member Function Documentation
template<class Key, class T> bool BALL::HashMap< Key, T >::has (const Key & key) const [inline]
Test whether the map contains the given key.
Reimplemented in BALL::StringHashMap< Value >, BALL::StringHashMap< list< Position > >, BALL::StringHashMap< NameMap >, BALL::StringHashMap< JCAMPValue >, BALL::StringHashMap< Position >, BALL::StringHashMap< Atom::Type >, BALL::StringHashMap< Ring >, BALL::StringHashMap< CreateMethod >, BALL::StringHashMap< Index >, BALL::StringHashMap< List< String >::Iterator >, BALL::StringHashMap< float >, BALL::StringHashMap< double(*)(double)>, BALL::StringHashMap< RuleList >, BALL::StringHashMap< Vector3 >, BALL::StringHashMap< SectionIterator >, BALL::StringHashMap< double * >, BALL::StringHashMap< Elements_ >, BALL::StringHashMap< vector< Position > >, BALL::StringHashMap< vector< Data > >, BALL::StringHashMap< CreationMethod >, BALL::StringHashMap< EmbeddableVector >, BALL::StringHashMap< StringHashMap< StringHashMap< std::multimap< float, AtomNames_ > > > >, BALL::StringHashMap< String >, BALL::StringHashMap< GAFFCESParser * >, BALL::StringHashMap< block >, and BALL::StringHashMap< ColorRGBA >.
Referenced by BALL::TMolecularGraph< Node, Edge >::deleteEdge(), BALL::TMolecularGraph< Node, Edge >::deleteNode(), BALL::TMolecularGraph< Node, Edge >::has(), BALL::TMolecularGraph< Node, Edge >::newEdge(), BALL::TMolecularGraph< Node, Edge >::newNode(), and BALL::HashMap< Key, T >::operator==().
template<class Key, class T> bool BALL::HashMap< Key, T >::operator== (const HashMap< Key, T > & rhs) const [inline]
Equality operator. Check whether two two hashmaps contain the same elements. O(n) runtime.
References BALL::HashMap< Key, T >::has(), and BALL::HashMap< Key, T >::size().
template<class Key, class T > T & BALL::HashMap< Key, T >::operator[] (const Key & key) [inline]
Return a mutable reference to the element whose key is key. If an element with the key key does not exist, it is inserted.
template<class Key, class T > const T & BALL::HashMap< Key, T >::operator[] (const Key & key) const [inline]
Return a constant reference to the element whose key is key.
Exceptions:
IllegalKey if the given key does not exist
template<class Key, class T> Size BALL::HashMap< Key, T >::size () const [inline]
Referenced by BALL::HashMap< Key, T >::operator==(), and BALL::HashMap< PDB::Integer, PDBAtom * >::size().