BALL::VIEW::RepresentationMessage Class Reference
[Messages]
Base class for all messages concerning a Representation.
#include <BALL/VIEW/KERNEL/message.h>
Public Types
enum RepresentationMessageType {
UNDEFINED = -1, ADD = 0, REMOVE, UPDATE,
SELECTED, STARTED_UPDATE, FINISHED_UPDATE, ADD_TO_GEOMETRIC_CONTROL
}
Types of RepresentationMessage.
Public Member Functions
RepresentationMessage ()
virtual ~RepresentationMessage ()
RepresentationMessage (Representation &rep, RepresentationMessageType type)
void setRepresentation (Representation &rep)
Representation * getRepresentation ()
void setType (RepresentationMessageType type)
RepresentationMessageType getType () const
Private Attributes
Representation * representation_
RepresentationMessageType type_
Detailed Description
Base class for all messages concerning a Representation.
Member Enumeration Documentation
enum BALL::VIEW::RepresentationMessage::RepresentationMessageType
Types of RepresentationMessage.
Enumerator:
UNDEFINED
Default Value.
ADD
Add a Representation.
REMOVE
Remove a Representation.
UPDATE
Update the Representation.
SELECTED
Representation was selected in GeometriControl.
STARTED_UPDATE
Started the update of a Representation, no changes allowed in GeometricControl.
FINISHED_UPDATE
Finished the update of a Representation.
ADD_TO_GEOMETRIC_CONTROL
Add a Representation to GeometricControl, but dont update in Scene.
Constructor & Destructor Documentation
BALL::VIEW::RepresentationMessage::RepresentationMessage ()
virtual BALL::VIEW::RepresentationMessage::~RepresentationMessage () [virtual]
BALL::VIEW::RepresentationMessage::RepresentationMessage (Representation & rep, RepresentationMessageType type)
Member Function Documentation
Representation* BALL::VIEW::RepresentationMessage::getRepresentation () [inline]
Referenced by BALL::VIEW::DemoTutorialDialog::onNotifyTutorial_().
RepresentationMessageType BALL::VIEW::RepresentationMessage::getType () const [inline]
Referenced by BALL::VIEW::DemoTutorialDialog::onNotifyDemo_(), and BALL::VIEW::DemoTutorialDialog::onNotifyTutorial_().
void BALL::VIEW::RepresentationMessage::setRepresentation (Representation & rep) [inline]
void BALL::VIEW::RepresentationMessage::setType (RepresentationMessageType type)
Member Data Documentation
Representation* BALL::VIEW::RepresentationMessage::representation_ [private]
RepresentationMessageType BALL::VIEW::RepresentationMessage::type_ [private]