BALL::NotificationManager_ Class Reference
#include <BALL/CONCEPT/notification.h>
Public Member Functions
~NotificationManager_ ()
Size getSize ()
void insert (void *source, void *target)
void remove (void *source)
void remove (void *source, void *target)
NotificationSource_ * findSource (void *source)
NotificationTarget_ * findFirstTarget (void *source)
NotificationTarget_ * findTarget (void *source, void *target)
NotificationSource_ * findEnabledSource (void *source)
NotificationTarget_ * findEnabledFirstTarget (void *source)
NotificationTarget_ * findEnabledTarget (void *source, void *target)
void destroy ()
void enable ()
void disable ()
bool isEnabled ()
bool isDisabled ()
bool isEmpty ()
bool isInserted (void *source)
bool isInserted (void *source, void *target)
void dump (std::ostream &s)
Static Public Attributes
static const Size INITIAL_NUMBER_OF_SLOTS
Private Member Functions
NotificationManager_ ()
bool needResize_ ()
void resize_ ()
Index hash_ (void *ptr)
Private Attributes
Size number_of_targets_
Size number_of_slots_
NotificationSlot_ * slots_
bool enabled_
Friends
NotificationManager_ & NotificationManager ()
Constructor & Destructor Documentation
BALL::NotificationManager_::~NotificationManager_ ()
BALL::NotificationManager_::NotificationManager_ () [private]
Member Function Documentation
void BALL::NotificationManager_::destroy ()
void BALL::NotificationManager_::disable ()
void BALL::NotificationManager_::dump (std::ostream & s)
void BALL::NotificationManager_::enable ()
NotificationTarget_* BALL::NotificationManager_::findEnabledFirstTarget (void * source)
NotificationSource_* BALL::NotificationManager_::findEnabledSource (void * source)
NotificationTarget_* BALL::NotificationManager_::findEnabledTarget (void * source, void * target)
NotificationTarget_* BALL::NotificationManager_::findFirstTarget (void * source)
NotificationSource_* BALL::NotificationManager_::findSource (void * source)
Referenced by BALL::NotificationSourceDisable(), and BALL::NotificationSourceEnable().
NotificationTarget_* BALL::NotificationManager_::findTarget (void * source, void * target)
Size BALL::NotificationManager_::getSize ()
Index BALL::NotificationManager_::hash_ (void * ptr) [private]
void BALL::NotificationManager_::insert (void * source, void * target)
Referenced by BALL::NotificationRegister(), BALL::NotificationRegister1(), and BALL::NotificationRegister2().
bool BALL::NotificationManager_::isDisabled ()
bool BALL::NotificationManager_::isEmpty ()
bool BALL::NotificationManager_::isEnabled ()
bool BALL::NotificationManager_::isInserted (void * source, void * target)
bool BALL::NotificationManager_::isInserted (void * source)
Referenced by BALL::NotificationIsRegistered().
bool BALL::NotificationManager_::needResize_ () [private]
void BALL::NotificationManager_::remove (void * source, void * target)
void BALL::NotificationManager_::remove (void * source)
Referenced by BALL::NotificationUnregister(), BALL::NotificationUnregister1(), and BALL::NotificationUnregister2().
void BALL::NotificationManager_::resize_ () [private]
Friends And Related Function Documentation
NotificationManager_& NotificationManager () [friend]
Member Data Documentation
bool BALL::NotificationManager_::enabled_ [private]
const Size BALL::NotificationManager_::INITIAL_NUMBER_OF_SLOTS [static]
Size BALL::NotificationManager_::number_of_slots_ [private]
Size BALL::NotificationManager_::number_of_targets_ [private]
NotificationSlot_* BALL::NotificationManager_::slots_ [private]