BALL::ConstForwardIterator< Container, DataType, Position, Traits > Class Template Reference
#include <BALL/CONCEPT/forwardIterator.h>
Public Types
Typedefs
typedef std::forward_iterator_tag iterator_category
typedef BaseIterator
< Container, DataType,
Position, Traits > Base
Public Member Functions
Constructors and Destructors
BALL_INLINE ConstForwardIterator ()
Default constructor.
BALL_INLINE ConstForwardIterator (const ConstForwardIterator &iterator)
Copy constructor.
BALL_INLINE ~ConstForwardIterator ()
Assignment
BALL_INLINE ConstForwardIterator & operator= (const ConstForwardIterator &iterator)
BALL_INLINE void swap (ConstForwardIterator &iterator)
Protected Member Functions
BALL_INLINE ConstForwardIterator (const Container &container)
Iterator methods
BALL_INLINE void toBegin () throw (Exception::Precondition)
Move the iterator to the item at the beginning of the container.
BALL_INLINE bool isBegin () const
Check whether the iterator points to the first item of the container.
BALL_INLINE void toEnd () throw (Exception::Precondition)
Move the iterator behind the last item of the container.
BALL_INLINE bool isEnd () const
Check whether the iterator points behind the last item of the container.
BALL_INLINE ConstForwardIterator & operator++ () throw (Exception::Precondition)
Increment operator.
BALL_INLINE ConstForwardIterator operator++ (int) throw (Exception::Precondition)
Postfix increment operator.
static ConstForwardIterator begin (const Container &container) throw (Exception::Precondition)
Return an iterator pointing to the beginning of the container.
static ConstForwardIterator end (const Container &container) throw (Exception::Precondition)
Return an iterator pointing at the end of the container.
Detailed Description
template<typename Container, typename DataType, typename Position, typename Traits>
class BALL::ConstForwardIterator< Container, DataType, Position, Traits >
Generic non-mutable forward itterator
Member Typedef Documentation
template<typename Container, typename DataType, typename Position, typename Traits> typedef BaseIterator<Container, DataType, Position, Traits> BALL::ConstForwardIterator< Container, DataType, Position, Traits >::Base
Reimplemented in BALL::ConstBidirectionalIterator< Container, DataType, Position, Traits >, BALL::BidirectionalIterator< Container, DataType, Position, Traits >, BALL::ForwardIterator< Container, DataType, Position, Traits >, BALL::ConstRandomAccessIterator< Container, DataType, Position, Traits >, BALL::RandomAccessIterator< Container, DataType, Position, Traits >, BALL::ConstBidirectionalIterator< Container, DataType, Position, Traits >, BALL::ConstBidirectionalIterator< Composite, Composite, Composite *, CompositeIteratorTraits >, BALL::BidirectionalIterator< Composite, Composite, Composite *, CompositeIteratorTraits >, and BALL::ConstRandomAccessIterator< Container, DataType, Position, Traits >.
template<typename Container, typename DataType, typename Position, typename Traits> typedef std::forward_iterator_tag BALL::ConstForwardIterator< Container, DataType, Position, Traits >::iterator_category
Reimplemented from BALL::BaseIterator< Container, DataType, Position, Traits >.
Reimplemented in BALL::ConstBidirectionalIterator< Container, DataType, Position, Traits >, BALL::ConstRandomAccessIterator< Container, DataType, Position, Traits >, BALL::ConstBidirectionalIterator< Container, DataType, Position, Traits >, BALL::ConstBidirectionalIterator< Composite, Composite, Composite *, CompositeIteratorTraits >, and BALL::ConstRandomAccessIterator< Container, DataType, Position, Traits >.
Constructor & Destructor Documentation
template<typename Container, typename DataType, typename Position, typename Traits> BALL_INLINE BALL::ConstForwardIterator< Container, DataType, Position, Traits >::ConstForwardIterator () [inline]
Default constructor.
template<typename Container, typename DataType, typename Position, typename Traits> BALL_INLINE BALL::ConstForwardIterator< Container, DataType, Position, Traits >::ConstForwardIterator (const ConstForwardIterator< Container, DataType, Position, Traits > & iterator) [inline]
Copy constructor.
template<typename Container, typename DataType, typename Position, typename Traits> BALL_INLINE BALL::ConstForwardIterator< Container, DataType, Position, Traits >::~ConstForwardIterator () [inline]
template<typename Container, typename DataType, typename Position, typename Traits> BALL_INLINE BALL::ConstForwardIterator< Container, DataType, Position, Traits >::ConstForwardIterator (const Container & container) [inline, protected]
Member Function Documentation
template<typename Container, typename DataType , typename Position , typename Traits > BALL_INLINE ConstForwardIterator< Container, DataType, Position, Traits > BALL::ConstForwardIterator< Container, DataType, Position, Traits >::begin (const Container & container) throw (Exception::Precondition) [inline, static]
Return an iterator pointing to the beginning of the container.
Reimplemented in BALL::ConstBidirectionalIterator< Container, DataType, Position, Traits >, BALL::BidirectionalIterator< Container, DataType, Position, Traits >, BALL::ForwardIterator< Container, DataType, Position, Traits >, BALL::ConstRandomAccessIterator< Container, DataType, Position, Traits >, BALL::RandomAccessIterator< Container, DataType, Position, Traits >, BALL::ConstBidirectionalIterator< Container, DataType, Position, Traits >, BALL::ConstBidirectionalIterator< Composite, Composite, Composite *, CompositeIteratorTraits >, BALL::BidirectionalIterator< Composite, Composite, Composite *, CompositeIteratorTraits >, and BALL::ConstRandomAccessIterator< Container, DataType, Position, Traits >.
References BALL::ConstForwardIterator< Container, DataType, Position, Traits >::toBegin().
Referenced by BALL::HashSet< Triangle * >::begin(), BALL::Enumerator< Container, SiteIterator, Variant >::begin(), BALL::HashGrid3< Sphere_ >::beginBox(), BALL::HashGridBox3< Sphere_ >::beginBox(), and BALL::HashGridBox3< Sphere_ >::beginData().
template<typename Container, typename DataType , typename Position , typename Traits > BALL_INLINE ConstForwardIterator< Container, DataType, Position, Traits > BALL::ConstForwardIterator< Container, DataType, Position, Traits >::end (const Container & container) throw (Exception::Precondition) [inline, static]
Return an iterator pointing at the end of the container.
Reimplemented in BALL::ConstBidirectionalIterator< Container, DataType, Position, Traits >, BALL::BidirectionalIterator< Container, DataType, Position, Traits >, BALL::ForwardIterator< Container, DataType, Position, Traits >, BALL::ConstRandomAccessIterator< Container, DataType, Position, Traits >, BALL::RandomAccessIterator< Container, DataType, Position, Traits >, BALL::ConstBidirectionalIterator< Container, DataType, Position, Traits >, BALL::ConstBidirectionalIterator< Composite, Composite, Composite *, CompositeIteratorTraits >, BALL::BidirectionalIterator< Composite, Composite, Composite *, CompositeIteratorTraits >, and BALL::ConstRandomAccessIterator< Container, DataType, Position, Traits >.
References BALL::ConstForwardIterator< Container, DataType, Position, Traits >::toEnd().
Referenced by BALL::HashSet< Triangle * >::end(), BALL::Enumerator< Container, SiteIterator, Variant >::end(), BALL::HashGrid3< Sphere_ >::endBox(), BALL::HashGridBox3< Sphere_ >::endBox(), and BALL::HashGridBox3< Sphere_ >::endData().
template<typename Container , typename DataType , typename Position , typename Traits > BALL_INLINE bool BALL::ConstForwardIterator< Container, DataType, Position, Traits >::isBegin () const [inline]
Check whether the iterator points to the first item of the container.
Reimplemented in BALL::ConstBidirectionalIterator< Container, DataType, Position, Traits >, BALL::ConstBidirectionalIterator< Container, DataType, Position, Traits >, and BALL::ConstBidirectionalIterator< Composite, Composite, Composite *, CompositeIteratorTraits >.
References BALL::BaseIterator< Container, DataType, Position, Traits >::getTraits(), and BALL::BaseIterator< Container, DataType, Position, Traits >::isSingular().
template<typename Container , typename DataType , typename Position , typename Traits > BALL_INLINE bool BALL::ConstForwardIterator< Container, DataType, Position, Traits >::isEnd () const [inline]
Check whether the iterator points behind the last item of the container.
Reimplemented in BALL::ConstBidirectionalIterator< Container, DataType, Position, Traits >, BALL::ConstBidirectionalIterator< Container, DataType, Position, Traits >, and BALL::ConstBidirectionalIterator< Composite, Composite, Composite *, CompositeIteratorTraits >.
References BALL::BaseIterator< Container, DataType, Position, Traits >::getTraits(), and BALL::BaseIterator< Container, DataType, Position, Traits >::isSingular().
template<typename Container, typename DataType, typename Position, typename Traits> BALL_INLINE ConstForwardIterator BALL::ConstForwardIterator< Container, DataType, Position, Traits >::operator++ (int) throw (Exception::Precondition) [inline]
Postfix increment operator.
Reimplemented in BALL::ConstBidirectionalIterator< Container, DataType, Position, Traits >, BALL::BidirectionalIterator< Container, DataType, Position, Traits >, BALL::ForwardIterator< Container, DataType, Position, Traits >, BALL::ConstBidirectionalIterator< Container, DataType, Position, Traits >, BALL::ConstBidirectionalIterator< Composite, Composite, Composite *, CompositeIteratorTraits >, and BALL::BidirectionalIterator< Composite, Composite, Composite *, CompositeIteratorTraits >.
template<typename Container, typename DataType, typename Position, typename Traits> BALL_INLINE ConstForwardIterator& BALL::ConstForwardIterator< Container, DataType, Position, Traits >::operator++ () throw (Exception::Precondition) [inline]
Increment operator.
Reimplemented in BALL::ConstBidirectionalIterator< Container, DataType, Position, Traits >, BALL::BidirectionalIterator< Container, DataType, Position, Traits >, BALL::ForwardIterator< Container, DataType, Position, Traits >, BALL::ConstBidirectionalIterator< Container, DataType, Position, Traits >, BALL::ConstBidirectionalIterator< Composite, Composite, Composite *, CompositeIteratorTraits >, and BALL::BidirectionalIterator< Composite, Composite, Composite *, CompositeIteratorTraits >.
template<typename Container, typename DataType, typename Position, typename Traits> BALL_INLINE ConstForwardIterator& BALL::ConstForwardIterator< Container, DataType, Position, Traits >::operator= (const ConstForwardIterator< Container, DataType, Position, Traits > & iterator) [inline]
Referenced by BALL::ConstForwardIterator< Composite, Composite, Composite *, CompositeIteratorTraits >::operator=().
template<typename Container, typename DataType, typename Position, typename Traits> BALL_INLINE void BALL::ConstForwardIterator< Container, DataType, Position, Traits >::swap (ConstForwardIterator< Container, DataType, Position, Traits > & iterator) [inline]
Referenced by BALL::ConstForwardIterator< Composite, Composite, Composite *, CompositeIteratorTraits >::swap().
template<typename Container , typename DataType , typename Position , typename Traits > BALL_INLINE void BALL::ConstForwardIterator< Container, DataType, Position, Traits >::toBegin () throw (Exception::Precondition) [inline]
Move the iterator to the item at the beginning of the container.
Reimplemented in BALL::ConstBidirectionalIterator< Container, DataType, Position, Traits >, BALL::ConstBidirectionalIterator< Container, DataType, Position, Traits >, and BALL::ConstBidirectionalIterator< Composite, Composite, Composite *, CompositeIteratorTraits >.
References BALL_PRECONDITION_EXCEPTION.
Referenced by BALL::ForwardIterator< Container, DataType, Position, Traits >::begin(), and BALL::ConstForwardIterator< Container, DataType, Position, Traits >::begin().
template<typename Container , typename DataType , typename Position , typename Traits > BALL_INLINE void BALL::ConstForwardIterator< Container, DataType, Position, Traits >::toEnd () throw (Exception::Precondition) [inline]
Move the iterator behind the last item of the container.
Reimplemented in BALL::ConstBidirectionalIterator< Container, DataType, Position, Traits >, BALL::ConstBidirectionalIterator< Container, DataType, Position, Traits >, and BALL::ConstBidirectionalIterator< Composite, Composite, Composite *, CompositeIteratorTraits >.
References BALL_PRECONDITION_EXCEPTION.
Referenced by BALL::ForwardIterator< Container, DataType, Position, Traits >::end(), and BALL::ConstForwardIterator< Container, DataType, Position, Traits >::end().