BALL::NotificationTarget2< NotificationSource, T1, T2 > Class Template Reference
#include <BALL/CONCEPT/notification.h>
Public Member Functions
virtual bool onNotify (NotificationSource &, T1, T2)=0
virtual unsigned short countNotificationTypes_ ()
virtual void * getVirtualNotificationType_ ()
Static Public Member Functions
static void * getNotificationType_ ()
template<class NotificationSource, class T1, class T2>
class BALL::NotificationTarget2< NotificationSource, T1, T2 >
Member Function Documentation
template<class NotificationSource, class T1, class T2> virtual unsigned short BALL::NotificationTarget2< NotificationSource, T1, T2 >::countNotificationTypes_ () [inline, virtual]
Referenced by BALL::Notify().
template<class NotificationSource, class T1, class T2> static void* BALL::NotificationTarget2< NotificationSource, T1, T2 >::getNotificationType_ () [inline, static]
Referenced by BALL::NotificationTarget2< NotificationSource, T1, T2 >::getVirtualNotificationType_(), and BALL::Notify().
template<class NotificationSource, class T1, class T2> virtual void* BALL::NotificationTarget2< NotificationSource, T1, T2 >::getVirtualNotificationType_ () [inline, virtual]
References BALL::NotificationTarget2< NotificationSource, T1, T2 >::getNotificationType_().
Referenced by BALL::Notify().
template<class NotificationSource, class T1, class T2> virtual bool BALL::NotificationTarget2< NotificationSource, T1, T2 >::onNotify (NotificationSource & , T1 , T2) [pure virtual]