BALL::TMolecularGraph< Node, Edge > Class Template Reference
#include <BALL/STRUCTURE/molecularGraph.h>
Public Types
typedef NodeItem< Node, Edge > NodeItemType
typedef EdgeItem< Node, Edge > EdgeItemType
typedef std::list
< NodeItemType >::iterator NodeIterator
typedef std::list
< NodeItemType >
::const_iterator NodeConstIterator
typedef std::list
< EdgeItemType >::iterator EdgeIterator
typedef std::list
< EdgeItemType >
::const_iterator EdgeConstIterator
Public Member Functions
TMolecularGraph ()
TMolecularGraph (const Molecule &molecule)
bool newNode (const Atom &atom)
bool newEdge (const Bond &bond)
bool deleteNode (NodeItemType &node)
bool deleteEdge (EdgeItemType &edge)
bool deleteNode (const Atom &atom)
bool deleteEdge (const Bond &bond)
NodeIterator beginNode ()
NodeConstIterator beginNode () const
EdgeIterator beginEdge ()
EdgeConstIterator beginEdge () const
NodeIterator endNode ()
NodeConstIterator endNode () const
EdgeIterator endEdge ()
EdgeConstIterator endEdge () const
bool has (const Atom &atom) const
bool has (const Bond &bond) const
NodeItemType & getNode (Position index)
const NodeItemType & getNode (Position index) const
EdgeItemType & getEdge (Position index)
const EdgeItemType & getEdge (Position index) const
Size getNumberOfNodes () const
Size getNumberOfEdges () const
Protected Attributes
std::list< NodeItemType > nodes_
std::list< EdgeItemType > edges_
HashMap< Atom *, NodeItemType * > atom_to_node_
HashMap< Bond *, EdgeItemType * > bond_to_edge_
template<typename Node, typename Edge>
class BALL::TMolecularGraph< Node, Edge >
Member Typedef Documentation
template<typename Node, typename Edge> typedef std::list<EdgeItemType>::const_iterator BALL::TMolecularGraph< Node, Edge >::EdgeConstIterator
template<typename Node, typename Edge> typedef EdgeItem<Node, Edge> BALL::TMolecularGraph< Node, Edge >::EdgeItemType
template<typename Node, typename Edge> typedef std::list<EdgeItemType>::iterator BALL::TMolecularGraph< Node, Edge >::EdgeIterator
template<typename Node, typename Edge> typedef std::list<NodeItemType>::const_iterator BALL::TMolecularGraph< Node, Edge >::NodeConstIterator
template<typename Node, typename Edge> typedef NodeItem<Node, Edge> BALL::TMolecularGraph< Node, Edge >::NodeItemType
template<typename Node, typename Edge> typedef std::list<NodeItemType>::iterator BALL::TMolecularGraph< Node, Edge >::NodeIterator
Constructor & Destructor Documentation
template<typename Node , typename Edge > BALL::TMolecularGraph< Node, Edge >::TMolecularGraph () [inline]
template<typename Node , typename Edge > BALL::TMolecularGraph< Node, Edge >::TMolecularGraph (const Molecule & molecule) [inline]
References BALL::TMolecularGraph< Node, Edge >::newEdge(), and BALL::TMolecularGraph< Node, Edge >::newNode().
Member Function Documentation
template<typename Node, typename Edge> EdgeConstIterator BALL::TMolecularGraph< Node, Edge >::beginEdge () const [inline]
References BALL::TMolecularGraph< Node, Edge >::edges_.
template<typename Node, typename Edge> EdgeIterator BALL::TMolecularGraph< Node, Edge >::beginEdge () [inline]
References BALL::TMolecularGraph< Node, Edge >::edges_.
Referenced by BALL::operator<<().
template<typename Node, typename Edge> NodeConstIterator BALL::TMolecularGraph< Node, Edge >::beginNode () const [inline]
References BALL::TMolecularGraph< Node, Edge >::nodes_.
template<typename Node, typename Edge> NodeIterator BALL::TMolecularGraph< Node, Edge >::beginNode () [inline]
References BALL::TMolecularGraph< Node, Edge >::nodes_.
template<typename Node , typename Edge > bool BALL::TMolecularGraph< Node, Edge >::deleteEdge (const Bond & bond) [inline]
References BALL::TMolecularGraph< Node, Edge >::bond_to_edge_, BALL::TMolecularGraph< Node, Edge >::deleteEdge(), and BALL::HashMap< Key, T >::has().
template<typename Node, typename Edge> bool BALL::TMolecularGraph< Node, Edge >::deleteEdge (EdgeItemType & edge)
Referenced by BALL::TMolecularGraph< Node, Edge >::deleteEdge().
template<typename Node , typename Edge > bool BALL::TMolecularGraph< Node, Edge >::deleteNode (const Atom & atom) [inline]
References BALL::TMolecularGraph< Node, Edge >::atom_to_node_, BALL::TMolecularGraph< Node, Edge >::deleteNode(), and BALL::HashMap< Key, T >::has().
template<typename Node, typename Edge> bool BALL::TMolecularGraph< Node, Edge >::deleteNode (NodeItemType & node)
Referenced by BALL::TMolecularGraph< Node, Edge >::deleteNode().
template<typename Node, typename Edge> EdgeConstIterator BALL::TMolecularGraph< Node, Edge >::endEdge () const [inline]
References BALL::TMolecularGraph< Node, Edge >::edges_.
template<typename Node, typename Edge> EdgeIterator BALL::TMolecularGraph< Node, Edge >::endEdge () [inline]
References BALL::TMolecularGraph< Node, Edge >::edges_.
Referenced by BALL::operator<<().
template<typename Node, typename Edge> NodeConstIterator BALL::TMolecularGraph< Node, Edge >::endNode () const [inline]
References BALL::TMolecularGraph< Node, Edge >::nodes_.
template<typename Node, typename Edge> NodeIterator BALL::TMolecularGraph< Node, Edge >::endNode () [inline]
References BALL::TMolecularGraph< Node, Edge >::nodes_.
Referenced by BALL::operator<<().
template<typename Node, typename Edge> const EdgeItemType& BALL::TMolecularGraph< Node, Edge >::getEdge (Position index) const [inline]
References BALL::TMolecularGraph< Node, Edge >::edges_.
template<typename Node, typename Edge> EdgeItemType& BALL::TMolecularGraph< Node, Edge >::getEdge (Position index) [inline]
References BALL::TMolecularGraph< Node, Edge >::edges_.
template<typename Node, typename Edge> const NodeItemType& BALL::TMolecularGraph< Node, Edge >::getNode (Position index) const [inline]
References BALL::TMolecularGraph< Node, Edge >::nodes_.
template<typename Node, typename Edge> NodeItemType& BALL::TMolecularGraph< Node, Edge >::getNode (Position index) [inline]
References BALL::TMolecularGraph< Node, Edge >::nodes_.
template<typename Node , typename Edge > BALL_INLINE Size BALL::TMolecularGraph< Node, Edge >::getNumberOfEdges () const [inline]
Return the number of nodes in the graph
References BALL::TMolecularGraph< Node, Edge >::edges_.
template<typename Node , typename Edge > BALL_INLINE Size BALL::TMolecularGraph< Node, Edge >::getNumberOfNodes () const [inline]
Return the number of nodes in the graph
References BALL::TMolecularGraph< Node, Edge >::nodes_.
template<typename Node, typename Edge> bool BALL::TMolecularGraph< Node, Edge >::has (const Bond & bond) const [inline]
References BALL::TMolecularGraph< Node, Edge >::bond_to_edge_, and BALL::HashMap< Key, T >::has().
template<typename Node, typename Edge> bool BALL::TMolecularGraph< Node, Edge >::has (const Atom & atom) const [inline]
References BALL::TMolecularGraph< Node, Edge >::atom_to_node_, and BALL::HashMap< Key, T >::has().
template<typename Node , typename Edge > bool BALL::TMolecularGraph< Node, Edge >::newEdge (const Bond & bond) [inline]
References BALL::NodeItem< Node, Edge >::adjacent_edges_, BALL::TMolecularGraph< Node, Edge >::atom_to_node_, BALL::TMolecularGraph< Node, Edge >::bond_to_edge_, BALL::TMolecularGraph< Node, Edge >::edges_, BALL::Bond::getFirstAtom(), BALL::Bond::getSecondAtom(), and BALL::HashMap< Key, T >::has().
Referenced by BALL::TMolecularGraph< Node, Edge >::TMolecularGraph().
template<typename Node , typename Edge > bool BALL::TMolecularGraph< Node, Edge >::newNode (const Atom & atom) [inline]
References BALL::TMolecularGraph< Node, Edge >::atom_to_node_, BALL::HashMap< Key, T >::has(), and BALL::TMolecularGraph< Node, Edge >::nodes_.
Referenced by BALL::TMolecularGraph< Node, Edge >::TMolecularGraph().
Member Data Documentation
template<typename Node, typename Edge> HashMap<Atom*, NodeItemType*> BALL::TMolecularGraph< Node, Edge >::atom_to_node_ [protected]
Referenced by BALL::TMolecularGraph< Node, Edge >::deleteNode(), BALL::TMolecularGraph< Node, Edge >::has(), BALL::TMolecularGraph< Node, Edge >::newEdge(), and BALL::TMolecularGraph< Node, Edge >::newNode().
template<typename Node, typename Edge> HashMap<Bond*, EdgeItemType*> BALL::TMolecularGraph< Node, Edge >::bond_to_edge_ [protected]
Referenced by BALL::TMolecularGraph< Node, Edge >::deleteEdge(), BALL::TMolecularGraph< Node, Edge >::has(), and BALL::TMolecularGraph< Node, Edge >::newEdge().
template<typename Node, typename Edge> std::list<EdgeItemType> BALL::TMolecularGraph< Node, Edge >::edges_ [protected]
Referenced by BALL::TMolecularGraph< Node, Edge >::beginEdge(), BALL::TMolecularGraph< Node, Edge >::endEdge(), BALL::TMolecularGraph< Node, Edge >::getEdge(), BALL::TMolecularGraph< Node, Edge >::getNumberOfEdges(), and BALL::TMolecularGraph< Node, Edge >::newEdge().
template<typename Node, typename Edge> std::list<NodeItemType> BALL::TMolecularGraph< Node, Edge >::nodes_ [protected]
Referenced by BALL::TMolecularGraph< Node, Edge >::beginNode(), BALL::TMolecularGraph< Node, Edge >::endNode(), BALL::TMolecularGraph< Node, Edge >::getNode(), BALL::TMolecularGraph< Node, Edge >::getNumberOfNodes(), and BALL::TMolecularGraph< Node, Edge >::newNode().