BALL::VIEW::DisplayProperties Class Reference
[QT Dialogs]
#include <BALL/VIEW/DIALOGS/displayProperties.h>
Public Slots
Public slots
void show ()
void selectModel (int index)
void selectMode (int index)
void selectColoringMethod (int index)
void setSurfaceDrawingPrecision (float value)
void setDrawingPrecision (int value)
void setTransparency (int value)
void setCustomColor (const ColorRGBA &color)
virtual void apply ()
void editColor ()
void editSelectionColor ()
void coloringOptionsPressed ()
void modelOptionsPressed ()
void precisionBoxChanged (int index)
void transparencySliderChanged ()
void precisionSliderChanged ()
void coloringUpdatesChanged ()
void modelUpdatesChanged ()
Public Member Functions
Constructors and Destructors
DisplayProperties (QWidget *parent=NULL, const char *name="DisplayProperties")
DisplayProperties (const DisplayProperties &dp)
Copy constructor just implemented for Python Interface, dont use it!
virtual ~DisplayProperties ()
Accessors: inspectors and mutators
virtual void onNotify (Message *message)
virtual void initializeWidget (MainControl &main_control)
virtual void initializePreferencesTab (Preferences &preferences)
Insert the ModelSettingsDialog and the ColoringSettingsDialog into the Preferences.
virtual void finalizePreferencesTab (Preferences &preferences)
Remove the ModelSettingsDialog and the ColoringSettingsDialog from the Preferences.
void applyPreferences ()
virtual void checkMenu (MainControl &main_control)
void createRepresentationMode ()
Switch to the mode, that a new Representation will be created.
void modifyRepresentationMode (Representation *rep)
Switch to the mode, that an existing Representation will be modified.
bool getSettingsFromString (const String &data)
Settings from String.
void createRepresentation (String data_string, const vector< const Composite * > &new_systems)
void enableCreationForNewMolecules (bool state)
Set if Representations are automaticaly created for new Molecules.
Representation * getRepresentation ()
Get the Representation on which DisplayProperties is working on.
virtual Representation * createRepresentation (const List< Composite * > &composites, bool hidden=false)
void setModelSettingsDialog (ModelSettingsDialog *dialog)
void setColoringSettingsDialog (ColoringSettingsDialog *dialog)
Protected Member Functions
void checkDrawingPrecision_ ()
virtual void getAdvancedModelOptions_ ()
virtual void getAdvancedColoringOptions_ ()
virtual void applyModelSettings_ (Representation &rep)
virtual void applyColoringSettings_ (Representation &rep)
void applyTo_ (Representation *rep)
Protected Attributes
ModelSettingsDialog * model_settings_
ColoringSettingsDialog * coloring_settings_
Preferences * preferences_
QAction * id_
Representation * rep_
ColorRGBA custom_color_
bool advanced_options_modified_
bool create_representations_for_new_molecules_
bool changed_selection_color_
const ModelInformation * model_information_
Detailed Description
Dialog for creating and changing representations for a selection of molecular objects. It can create a new Representation for a selection of Composite 's from the MolecularControl. If a Representation is selected in the GeometricControl, it can be modified with this dialog. With the help of various combo boxes it is possible to customize the look of the graphical visualization (the model, the drawing precision, the drawing mode, the coloring method and the custom color). For information about the drawing precision see Representation.
If this dialog is used, it should be created with MainControl as parent.
If you want to add a new coloring method or type of Representation, have a look at VIEW/KERNEL/common.h.
Constructor & Destructor Documentation
BALL::VIEW::DisplayProperties::DisplayProperties (QWidget * parent = NULL, const char * name = "DisplayProperties")
Default Constructor. Calls ModularWidget::registerWidget.
BALL::VIEW::DisplayProperties::DisplayProperties (const DisplayProperties & dp)
Copy constructor just implemented for Python Interface, dont use it!
virtual BALL::VIEW::DisplayProperties::~DisplayProperties () [virtual]
Destructor
Member Function Documentation
virtual void BALL::VIEW::DisplayProperties::apply () [virtual, slot]
Indicates the apply button was pressed. Applies the selected model with its selected properties to the selected Composite objects or modifies an existing Representation. A SceneMessage will be sent to inform the Scene. A RepresentationMessage notifies the GeometricControl.
virtual void BALL::VIEW::DisplayProperties::applyColoringSettings_ (Representation & rep) [protected, virtual]
virtual void BALL::VIEW::DisplayProperties::applyModelSettings_ (Representation & rep) [protected, virtual]
void BALL::VIEW::DisplayProperties::applyPreferences () [virtual]
Apply the preferences of the specific tab. In this method the widget can extract any changed values from its preferences tab (if required). This method is called automatically by the applyPreferencesTab from the MainControl object if the apply button in the Preferences dialog is pressed.
Parameters:
preferences the Preferences dialog of the MainControl
See also:
initializePreferencesTab
finalizePreferencesTab
applyPreferencesTab
Reimplemented from BALL::VIEW::ModularWidget.
void BALL::VIEW::DisplayProperties::applyTo_ (Representation * rep) [protected]
void BALL::VIEW::DisplayProperties::checkDrawingPrecision_ () [protected]
virtual void BALL::VIEW::DisplayProperties::checkMenu (MainControl & main_control) [virtual]
Menu checking method. This method is called by MainControl::checkMenus before a popup menu is shown. The menu entry Display Properties will be checked if this dialog is visible.
Parameters:
main_control the MainControl object whose menus should be checked
Reimplemented from BALL::VIEW::ModularWidget.
void BALL::VIEW::DisplayProperties::coloringOptionsPressed () [slot]
void BALL::VIEW::DisplayProperties::coloringUpdatesChanged () [slot]
virtual Representation* BALL::VIEW::DisplayProperties::createRepresentation (const List< Composite * > & composites, bool hidden = false) [virtual]
void BALL::VIEW::DisplayProperties::createRepresentation (String data_string, const vector< const Composite * > & new_systems)
void BALL::VIEW::DisplayProperties::createRepresentationMode ()
Switch to the mode, that a new Representation will be created.
void BALL::VIEW::DisplayProperties::editColor () [slot]
Opens the dialog for editing the custom color. Opens a QColorDialog from the QT-library.
void BALL::VIEW::DisplayProperties::editSelectionColor () [slot]
Opens the color dialog for the color of selected items.
See also:
BALL_SELECTED_COLOR
void BALL::VIEW::DisplayProperties::enableCreationForNewMolecules (bool state) [inline]
Set if Representations are automaticaly created for new Molecules.
Referenced by BALL::VIEW::DemoTutorialDialog::nextStepDemo_().
virtual void BALL::VIEW::DisplayProperties::finalizePreferencesTab (Preferences & preferences) [virtual]
Remove the ModelSettingsDialog and the ColoringSettingsDialog from the Preferences.
Reimplemented from BALL::VIEW::ModularWidget.
virtual void BALL::VIEW::DisplayProperties::getAdvancedColoringOptions_ () [protected, virtual]
virtual void BALL::VIEW::DisplayProperties::getAdvancedModelOptions_ () [protected, virtual]
Representation* BALL::VIEW::DisplayProperties::getRepresentation () [inline]
Get the Representation on which DisplayProperties is working on.
bool BALL::VIEW::DisplayProperties::getSettingsFromString (const String & data)
Settings from String.
virtual void BALL::VIEW::DisplayProperties::initializePreferencesTab (Preferences & preferences) [virtual]
Insert the ModelSettingsDialog and the ColoringSettingsDialog into the Preferences.
Reimplemented from BALL::VIEW::ModularWidget.
virtual void BALL::VIEW::DisplayProperties::initializeWidget (MainControl & main_control) [virtual]
ModularWidget methods Initialize the popup menu Display with the entry Display Properties, which opens the dialog. This method is called automatically immediately before the main application is started by MainControl::show()
Parameters:
main_control the MainControl object to be initialized
Reimplemented from BALL::VIEW::ModularWidget.
void BALL::VIEW::DisplayProperties::modelOptionsPressed () [slot]
void BALL::VIEW::DisplayProperties::modelUpdatesChanged () [slot]
void BALL::VIEW::DisplayProperties::modifyRepresentationMode (Representation * rep)
Switch to the mode, that an existing Representation will be modified.
virtual void BALL::VIEW::DisplayProperties::onNotify (Message * message) [virtual]
Message handling method. Handles messages sent by other registered ConnectionObject objects. If a CompositeMessage with type NEW_MOLECULE is catched, the chosen graphical visualization will be applied to the Composite object and the follwing Message objects will be sent through the ConnectionObject tree:
CompositeMessage with type CENTER_CAMERA
RepresentationMessage with type NEW
Parameters:
message the pointer to the message that should be processed
Reimplemented from BALL::VIEW::ConnectionObject.
void BALL::VIEW::DisplayProperties::precisionBoxChanged (int index) [slot]
void BALL::VIEW::DisplayProperties::precisionSliderChanged () [slot]
void BALL::VIEW::DisplayProperties::selectColoringMethod (int index) [slot]
Changes the coloring method. This slot is connected to the coloring method combo box and will be automatically called if the content of this combo box is changed.
Parameters:
index the position of the entry in the combobox
Referenced by BALL::Mainframe::reset().
void BALL::VIEW::DisplayProperties::selectMode (int index) [slot]
Changes the drawing mode. This slot is connected to the mode combo box and will be automatically called if the content of this combo box is changed.
Parameters:
index the position of the entry in the combobox
Referenced by BALL::Mainframe::reset().
void BALL::VIEW::DisplayProperties::selectModel (int index) [slot]
Changes the model. This slot is connected to the model combo box and will be automatically called if the content of this combo box is changed.
Parameters:
index the position of the entry in the combobox
Referenced by BALL::Mainframe::reset().
void BALL::VIEW::DisplayProperties::setColoringSettingsDialog (ColoringSettingsDialog * dialog)
void BALL::VIEW::DisplayProperties::setCustomColor (const ColorRGBA & color) [slot]
void BALL::VIEW::DisplayProperties::setDrawingPrecision (int value) [slot]
Referenced by BALL::VIEW::DemoTutorialDialog::nextStepDemo_(), and BALL::Mainframe::reset().
void BALL::VIEW::DisplayProperties::setModelSettingsDialog (ModelSettingsDialog * dialog)
void BALL::VIEW::DisplayProperties::setSurfaceDrawingPrecision (float value) [slot]
Referenced by BALL::Mainframe::reset().
void BALL::VIEW::DisplayProperties::setTransparency (int value) [slot]
Referenced by BALL::Mainframe::reset().
void BALL::VIEW::DisplayProperties::show () [slot]
Starts the dialog. Calls QDialog::raise().
void BALL::VIEW::DisplayProperties::transparencySliderChanged () [slot]
Member Data Documentation
bool BALL::VIEW::DisplayProperties::advanced_options_modified_ [protected]
bool BALL::VIEW::DisplayProperties::changed_selection_color_ [protected]
ColoringSettingsDialog* BALL::VIEW::DisplayProperties::coloring_settings_ [protected]
bool BALL::VIEW::DisplayProperties::create_representations_for_new_molecules_ [protected]
ColorRGBA BALL::VIEW::DisplayProperties::custom_color_ [protected]
QAction* BALL::VIEW::DisplayProperties::id_ [protected]
const ModelInformation* BALL::VIEW::DisplayProperties::model_information_ [protected]
ModelSettingsDialog* BALL::VIEW::DisplayProperties::model_settings_ [protected]
Preferences* BALL::VIEW::DisplayProperties::preferences_ [protected]
Representation* BALL::VIEW::DisplayProperties::rep_ [protected]