BALL::ForwardIterator< Container, DataType, Position, Traits > Class Template Reference
#include <BALL/CONCEPT/forwardIterator.h>
Public Types
Typedefs
typedef DataType & reference
typedef DataType * pointer
typedef ConstForwardIterator
< Container, DataType,
Position, Traits > Base
Public Member Functions
Constructors and Destructors
BALL_INLINE ForwardIterator ()
BALL_INLINE ForwardIterator (const ForwardIterator &iterator)
BALL_INLINE ~ForwardIterator ()
Assignemnt
BALL_INLINE ForwardIterator & operator= (const ForwardIterator &iterator)
BALL_INLINE void swap (ForwardIterator &iterator)
Protected Member Functions
BALL_INLINE ForwardIterator (const Container &container)
Iterator methods
BALL_INLINE reference operator* () const
Convert an iterator to its Datatype by returning a reference to the current data.
BALL_INLINE pointer operator-> () const
Return a pointer to the current data.
BALL_INLINE ForwardIterator & operator++ () throw (Exception::Precondition)
Increment operator.
BALL_INLINE ForwardIterator operator++ (int) throw (Exception::Precondition)
Postfix increment operator.
static ForwardIterator begin (const Container &container) throw (Exception::Precondition)
Return an iterator pointing to the beginning of the container.
static ForwardIterator end (const Container &container) throw (Exception::Precondition)
Return an iterator pointing at the end of the container.
Detailed Description
template<typename Container, typename DataType, typename Position, typename Traits>
class BALL::ForwardIterator< Container, DataType, Position, Traits >
Generic mutable forward iterator class
Member Typedef Documentation
template<typename Container , typename DataType , typename Position , typename Traits > typedef ConstForwardIterator<Container, DataType, Position, Traits> BALL::ForwardIterator< Container, DataType, Position, Traits >::Base
Reimplemented from BALL::ConstForwardIterator< Container, DataType, Position, Traits >.
template<typename Container , typename DataType , typename Position , typename Traits > typedef DataType* BALL::ForwardIterator< Container, DataType, Position, Traits >::pointer
Reimplemented from BALL::BaseIterator< Container, DataType, Position, Traits >.
template<typename Container , typename DataType , typename Position , typename Traits > typedef DataType& BALL::ForwardIterator< Container, DataType, Position, Traits >::reference
Reimplemented from BALL::BaseIterator< Container, DataType, Position, Traits >.
Constructor & Destructor Documentation
template<typename Container , typename DataType , typename Position , typename Traits > BALL_INLINE BALL::ForwardIterator< Container, DataType, Position, Traits >::ForwardIterator () [inline]
template<typename Container , typename DataType , typename Position , typename Traits > BALL_INLINE BALL::ForwardIterator< Container, DataType, Position, Traits >::ForwardIterator (const ForwardIterator< Container, DataType, Position, Traits > & iterator) [inline]
template<typename Container , typename DataType , typename Position , typename Traits > BALL_INLINE BALL::ForwardIterator< Container, DataType, Position, Traits >::~ForwardIterator () [inline]
template<typename Container , typename DataType , typename Position , typename Traits > BALL_INLINE BALL::ForwardIterator< Container, DataType, Position, Traits >::ForwardIterator (const Container & container) [inline, protected]
Member Function Documentation
template<typename Container , typename DataType , typename Position , typename Traits > BALL_INLINE ForwardIterator< Container, DataType, Position, Traits > BALL::ForwardIterator< Container, DataType, Position, Traits >::begin (const Container & container) throw (Exception::Precondition) [inline, static]
Return an iterator pointing to the beginning of the container.
Reimplemented from BALL::ConstForwardIterator< Container, DataType, Position, Traits >.
References BALL::ConstForwardIterator< Container, DataType, Position, Traits >::toBegin().
Referenced by BALL::HashSet< Triangle * >::begin(), BALL::Enumerator< Container, SiteIterator, Variant >::begin(), BALL::HashGrid3< Sphere_ >::beginBox(), BALL::HashGridBox3< Sphere_ >::beginBox(), and BALL::HashGridBox3< Sphere_ >::beginData().
template<typename Container , typename DataType , typename Position , typename Traits > BALL_INLINE ForwardIterator< Container, DataType, Position, Traits > BALL::ForwardIterator< Container, DataType, Position, Traits >::end (const Container & container) throw (Exception::Precondition) [inline, static]
Return an iterator pointing at the end of the container.
Reimplemented from BALL::ConstForwardIterator< Container, DataType, Position, Traits >.
References BALL::ConstForwardIterator< Container, DataType, Position, Traits >::toEnd().
Referenced by BALL::HashSet< Triangle * >::end(), BALL::Enumerator< Container, SiteIterator, Variant >::end(), BALL::HashGrid3< Sphere_ >::endBox(), BALL::HashGridBox3< Sphere_ >::endBox(), and BALL::HashGridBox3< Sphere_ >::endData().
template<typename Container , typename DataType , typename Position , typename Traits > BALL_INLINE reference BALL::ForwardIterator< Container, DataType, Position, Traits >::operator* () const [inline]
Convert an iterator to its Datatype by returning a reference to the current data.
Reimplemented from BALL::BaseIterator< Container, DataType, Position, Traits >.
References BALL::BaseIterator< Container, DataType, Position, Traits >::getTraits().
template<typename Container , typename DataType , typename Position , typename Traits > BALL_INLINE ForwardIterator BALL::ForwardIterator< Container, DataType, Position, Traits >::operator++ (int) throw (Exception::Precondition) [inline]
Postfix increment operator.
Reimplemented from BALL::ConstForwardIterator< Container, DataType, Position, Traits >.
References BALL_PRECONDITION_EXCEPTION, and BALL::BaseIterator< Container, DataType, Position, Traits >::isValid().
template<typename Container , typename DataType , typename Position , typename Traits > BALL_INLINE ForwardIterator& BALL::ForwardIterator< Container, DataType, Position, Traits >::operator++ () throw (Exception::Precondition) [inline]
Increment operator.
Reimplemented from BALL::ConstForwardIterator< Container, DataType, Position, Traits >.
References BALL_PRECONDITION_EXCEPTION, BALL::BaseIterator< Container, DataType, Position, Traits >::getTraits(), and BALL::BaseIterator< Container, DataType, Position, Traits >::isValid().
template<typename Container , typename DataType , typename Position , typename Traits > BALL_INLINE pointer BALL::ForwardIterator< Container, DataType, Position, Traits >::operator-> () const [inline]
Return a pointer to the current data.
Reimplemented from BALL::BaseIterator< Container, DataType, Position, Traits >.
References BALL::BaseIterator< Container, DataType, Position, Traits >::getTraits().
template<typename Container , typename DataType , typename Position , typename Traits > BALL_INLINE ForwardIterator& BALL::ForwardIterator< Container, DataType, Position, Traits >::operator= (const ForwardIterator< Container, DataType, Position, Traits > & iterator) [inline]
template<typename Container , typename DataType , typename Position , typename Traits > BALL_INLINE void BALL::ForwardIterator< Container, DataType, Position, Traits >::swap (ForwardIterator< Container, DataType, Position, Traits > & iterator) [inline]
References BALL::BaseIterator< Container, DataType, Position, Traits >::getTraits().