BALL::UnaryProcessor< T > Class Template Reference
#include <BALL/CONCEPT/processor.h>
Public Member Functions
Constructors and Destructors
UnaryProcessor ()
UnaryProcessor (const UnaryProcessor &)
virtual ~UnaryProcessor ()
Processor specific methods
virtual bool start ()
virtual bool finish ()
virtual Processor::Result operator() (T &)
Detailed Description
template<typename T>
class BALL::UnaryProcessor< T >
Generic Unary Processor Class
Constructor & Destructor Documentation
template<typename T> BALL::UnaryProcessor< T >::UnaryProcessor () [inline]
Default constructor
template<typename T> BALL::UnaryProcessor< T >::UnaryProcessor (const UnaryProcessor< T > &) [inline]
Copy constructor
template<typename T> virtual BALL::UnaryProcessor< T >::~UnaryProcessor () [inline, virtual]
Destructor
Member Function Documentation
template<typename T> virtual bool BALL::UnaryProcessor< T >::finish () [inline, virtual]
finish method
Reimplemented in BALL::ComposedEnergyProcessor, BALL::RuleProcessor, BALL::MMFF94ChargeProcessor, BALL::AnisotropyShiftProcessor, BALL::EFShiftProcessor, BALL::HaighMallionShiftProcessor, BALL::HBondShiftProcessor, BALL::JohnsonBoveyShiftProcessor, BALL::ShiftModel, BALL::ShiftModule, BALL::Pair6_12InteractionEnergyProcessor, BALL::PairExpInteractionEnergyProcessor, BALL::PCMCavFreeEnergyProcessor, BALL::PierottiCavFreeEnergyProcessor, BALL::ReissCavFreeEnergyProcessor, BALL::UhligCavFreeEnergyProcessor, BALL::AssignBondOrderProcessor, BALL::BindingPocketProcessor, BALL::AssignRadiusProcessor, BALL::FragmentDB::NormalizeNamesProcessor, BALL::FragmentDB::BuildBondsProcessor, BALL::BoundingBoxProcessor, BALL::GeometricCenterProcessor, BALL::FragmentDistanceCollector, BALL::HBondProcessor, BALL::ReconstructFragmentProcessor, BALL::ResidueChecker, BALL::SurfaceProcessor, and BALL::VIEW::AtomDistanceColorProcessor.
Referenced by BALL::List< EnergyProcessor * >::apply(), BALL::HashSet< Key >::apply(), BALL::HashGrid3< Item >::apply(), and BALL::HashGridBox3< Item >::apply().
template<typename T> virtual Processor::Result BALL::UnaryProcessor< T >::operator() (T &) [inline, virtual]
operator ()
Reimplemented in BALL::EnergyProcessor, BALL::Selector, BALL::GAFFTypeProcessor, BALL::AssignTypeProcessor, BALL::AssignTypeNameProcessor, BALL::ChargeRuleProcessor, BALL::RadiusRuleProcessor, BALL::TypenameRuleProcessor, BALL::TypeRuleProcessor, BALL::MMFF94ChargeProcessor, BALL::AnisotropyShiftProcessor, BALL::AssignShiftProcessor, BALL::ClearShiftProcessor, BALL::CreateSpectrumProcessor, BALL::EFShiftProcessor, BALL::SimpleExperiment1D, BALL::HaighMallionShiftProcessor, BALL::HBondShiftProcessor, BALL::JohnsonBoveyShiftProcessor, BALL::RandomCoilShiftProcessor, BALL::ShiftModel, BALL::AromaticityProcessor, BALL::Descriptor, BALL::PartialChargeProcessor, BALL::RingPerceptionProcessor, BALL::AddHydrogenProcessor, BALL::AssignBondOrderProcessor, BALL::BindingPocketProcessor, BALL::BuildBondsProcessor, BALL::ClearChargeProcessor, BALL::ClearRadiusProcessor, BALL::AssignRadiusProcessor, BALL::AssignChargeProcessor, BALL::FragmentDB::NormalizeNamesProcessor, BALL::FragmentDB::BuildBondsProcessor, BALL::BoundingBoxProcessor, BALL::GeometricCenterProcessor, BALL::FragmentDistanceCollector, BALL::TranslationProcessor, BALL::TransformationProcessor, BALL::HBondProcessor, BALL::HybridisationProcessor, BALL::ReconstructFragmentProcessor, BALL::ResidueChecker, BALL::SecondaryStructureProcessor, BALL::SurfaceProcessor, BALL::VIEW::AtomOverview::OverviewProcessor, BALL::VIEW::AtomOverview::ApplyProcessor, BALL::VIEW::AtomBondModelBaseProcessor, BALL::VIEW::AddBackboneModel, BALL::VIEW::AddBallAndStickModel, BALL::VIEW::ColorProcessor, BALL::VIEW::ForceModel, BALL::VIEW::HBondModelProcessor, BALL::VIEW::LabelModel, BALL::VIEW::AddLineModel, BALL::VIEW::AtomDistanceColorProcessor, BALL::VIEW::AddSurfaceModel, and BALL::VIEW::AddVanDerWaalsModel.
template<typename T> virtual bool BALL::UnaryProcessor< T >::start () [inline, virtual]
start method
Reimplemented in BALL::EnergyProcessor, BALL::Selector, BALL::RuleProcessor, BALL::MMFF94ChargeProcessor, BALL::AssignShiftProcessor, BALL::CreateSpectrumProcessor, BALL::EFShiftProcessor, BALL::SimpleExperiment1D, BALL::HBondShiftProcessor, BALL::JohnsonBoveyShiftProcessor, BALL::ShiftModel, BALL::ShiftModule, BALL::AromaticityProcessor, BALL::AddHydrogenProcessor, BALL::AssignBondOrderProcessor, BALL::BuildBondsProcessor, BALL::AssignRadiusProcessor, BALL::AssignChargeProcessor, BALL::FragmentDB::NormalizeNamesProcessor, BALL::FragmentDB::BuildBondsProcessor, BALL::BoundingBoxProcessor, BALL::GeometricCenterProcessor, BALL::FragmentDistanceCollector, BALL::HybridisationProcessor, BALL::ReconstructFragmentProcessor, BALL::ResidueChecker, BALL::SurfaceProcessor, BALL::VIEW::AddBackboneModel, BALL::VIEW::ColorProcessor, BALL::VIEW::InterpolateColorProcessor, BALL::VIEW::ResidueNumberColorProcessor, and BALL::VIEW::PositionColorProcessor.
Referenced by BALL::List< EnergyProcessor * >::apply(), BALL::HashSet< Key >::apply(), BALL::HashGrid3< Item >::apply(), and BALL::HashGridBox3< Item >::apply().