BALL::NotificationTarget1< NotificationSource, T1 > Class Template Reference
#include <BALL/CONCEPT/notification.h>
Public Member Functions
virtual bool onNotify (NotificationSource &, T1)=0
virtual unsigned short countNotificationTypes_ ()
virtual void * getVirtualNotificationType ()
Static Public Member Functions
static void * getNotificationType_ ()
template<class NotificationSource, class T1>
class BALL::NotificationTarget1< NotificationSource, T1 >
Member Function Documentation
template<class NotificationSource, class T1> virtual unsigned short BALL::NotificationTarget1< NotificationSource, T1 >::countNotificationTypes_ () [inline, virtual]
Referenced by BALL::Notify().
template<class NotificationSource, class T1> static void* BALL::NotificationTarget1< NotificationSource, T1 >::getNotificationType_ () [inline, static]
Referenced by BALL::NotificationTarget1< NotificationSource, T1 >::getVirtualNotificationType(), and BALL::Notify().
template<class NotificationSource, class T1> virtual void* BALL::NotificationTarget1< NotificationSource, T1 >::getVirtualNotificationType () [inline, virtual]
References BALL::NotificationTarget1< NotificationSource, T1 >::getNotificationType_().
template<class NotificationSource, class T1> virtual bool BALL::NotificationTarget1< NotificationSource, T1 >::onNotify (NotificationSource & , T1) [pure virtual]