BALL::NotificationTarget< NotificationSource > Class Template Reference
#include <BALL/CONCEPT/notification.h>
Public Member Functions
virtual ~NotificationTarget ()
virtual bool onNotify (NotificationSource &source)=0
virtual unsigned short countNotificationTypes_ ()
virtual void * getVirtualNotificationType_ ()
Static Public Member Functions
static void * getNotificationType_ ()
Detailed Description
template<class NotificationSource>
class BALL::NotificationTarget< NotificationSource >
Notification Target Class.
Constructor & Destructor Documentation
template<class NotificationSource> virtual BALL::NotificationTarget< NotificationSource >::~NotificationTarget () [inline, virtual]
Member Function Documentation
template<class NotificationSource> virtual unsigned short BALL::NotificationTarget< NotificationSource >::countNotificationTypes_ () [inline, virtual]
Referenced by BALL::Notify().
template<class NotificationSource> static void* BALL::NotificationTarget< NotificationSource >::getNotificationType_ () [inline, static]
Referenced by BALL::NotificationTarget< NotificationSource >::getVirtualNotificationType_(), and BALL::Notify().
template<class NotificationSource> virtual void* BALL::NotificationTarget< NotificationSource >::getVirtualNotificationType_ () [inline, virtual]
References BALL::NotificationTarget< NotificationSource >::getNotificationType_().
Referenced by BALL::Notify().
template<class NotificationSource> virtual bool BALL::NotificationTarget< NotificationSource >::onNotify (NotificationSource & source) [pure virtual]
The method to be invoked upon receiving a notification
Referenced by BALL::Notify().