BALL::VIEW::DatasetMessage Class Reference
[Messages]
#include <BALL/VIEW/KERNEL/message.h>
Public Types
enum Type {
UNDEFINED = -1, ADD = 0, REMOVE, UPDATE,
SELECTED, VISUALIZE, VISUALIZE_END = 100
}
Message type enumeration.
Public Member Functions
DatasetMessage (Dataset *set=0, Type type=UNDEFINED)
DatasetMessage (const DatasetMessage &msg)
Type getType () const
void setType (Type type)
Dataset * getDataset () const
void setDataset (Dataset *set)
bool isValid () const
Protected Attributes
Dataset * dataset_
Type type_
String dataset_type_
Detailed Description
Message to notify about changes in a Dataset. This message can be e.g. used to notify all ModularWidget about a new DockResult, Trajectory or any other kind of dataset. The Dataset contains the information on the kind of data it contains. The receiving widget thus has to query the type of the message and the the type of the Dataset.
See also:
Dataset
DatasetController
DatasetControl
Member Enumeration Documentation
enum BALL::VIEW::DatasetMessage::Type
Message type enumeration.
Enumerator:
UNDEFINED
Default Value.
ADD
To add.
REMOVE
To be removed.
UPDATE
Update.
SELECTED
Was selected in Control.
VISUALIZE
VISUALIZE_END
Allow >90 different kinds of visualization.
Constructor & Destructor Documentation
BALL::VIEW::DatasetMessage::DatasetMessage (Dataset * set = 0, Type type = UNDEFINED)
BALL::VIEW::DatasetMessage::DatasetMessage (const DatasetMessage & msg)
Member Function Documentation
Dataset* BALL::VIEW::DatasetMessage::getDataset () const [inline]
References dataset_.
Referenced by BALL::VIEW::DemoTutorialDialog::onNotifyDemo_(), and BALL::VIEW::DemoTutorialDialog::onNotifyTutorial_().
Type BALL::VIEW::DatasetMessage::getType () const [inline]
References type_.
Referenced by BALL::VIEW::DemoTutorialDialog::onNotifyTutorial_().
bool BALL::VIEW::DatasetMessage::isValid () const
void BALL::VIEW::DatasetMessage::setDataset (Dataset * set) [inline]
References dataset_.
void BALL::VIEW::DatasetMessage::setType (Type type) [inline]
References type_.
Member Data Documentation
Dataset* BALL::VIEW::DatasetMessage::dataset_ [protected]
Referenced by getDataset(), and setDataset().
String BALL::VIEW::DatasetMessage::dataset_type_ [protected]
Type BALL::VIEW::DatasetMessage::type_ [protected]
Referenced by getType(), and setType().