BALL::ConstBidirectionalIterator< Container, DataType, Position, Traits > Class Template Reference
#include <BALL/CONCEPT/bidirectionalIterator.h>
Public Types
Typedefs
typedef
std::bidirectional_iterator_tag iterator_category
typedef ConstForwardIterator
< Container, DataType,
Position, Traits > Base
Public Member Functions
Constructors and destructor.
BALL_INLINE ConstBidirectionalIterator ()
BALL_INLINE ConstBidirectionalIterator (const ConstBidirectionalIterator &iterator)
BALL_INLINE ~ConstBidirectionalIterator ()
Protected Member Functions
BALL_INLINE ConstBidirectionalIterator (const Container &container)
Construct an iterator bound to a specific container.
Iterator methods
BALL_INLINE void toBegin () throw (Exception::Precondition)
Move the iterator to the beginning of the container.
BALL_INLINE bool isBegin () const
Check whether the iterator points to the item at the beginning of the container.
void toEnd () throw (Exception::Precondition)
Move the iterator to the position after the last item of the container.
BALL_INLINE bool isEnd () const
Check whether the iterator points to the position after the last item of the container.
void toRBegin () throw (Exception::Precondition)
Move the iterator to the "reverse" beginning of the container.
BALL_INLINE bool isRBegin () const
Test whether the iterator points to the "reverse" first element of the container.
void toREnd () throw (Exception::Precondition)
Move the iterator to the position before the first element.
BALL_INLINE bool isREnd () const
Test wheter the iterator points to the position before the first element.
BALL_INLINE
ConstBidirectionalIterator & operator++ () throw (Exception::Precondition)
Increment operator.
BALL_INLINE
ConstBidirectionalIterator operator++ (int) throw (Exception::Precondition)
Postfix increment operator.
BALL_INLINE
ConstBidirectionalIterator & operator-- () throw (Exception::Precondition)
Decrement operator.
BALL_INLINE
ConstBidirectionalIterator operator-- (int) throw (Exception::Precondition)
Postfix decrement operator.
static ConstBidirectionalIterator begin (const Container &container) throw (Exception::Precondition)
Return an iterator pointingto the first item of the container.
static ConstBidirectionalIterator end (const Container &container) throw (Exception::Precondition)
Return an iterator pointing to the position after the last element.
static ConstBidirectionalIterator rbegin (const Container &container) throw (Exception::Precondition)
Return an iterator pointing to the last element.
static ConstBidirectionalIterator rend (const Container &container) throw (Exception::Precondition)
Return an iterator pointing to the positon before the first element.
Detailed Description
template<typename Container, typename DataType, typename Position, typename Traits>
class BALL::ConstBidirectionalIterator< Container, DataType, Position, Traits >
Constant Bidirectional Iterator.
Member Typedef Documentation
template<typename Container, typename DataType, typename Position, typename Traits> typedef ConstForwardIterator<Container, DataType, Position, Traits> BALL::ConstBidirectionalIterator< Container, DataType, Position, Traits >::Base
Reimplemented from BALL::ConstForwardIterator< Container, DataType, Position, Traits >.
Reimplemented in BALL::BidirectionalIterator< Container, DataType, Position, Traits >, BALL::ConstRandomAccessIterator< Container, DataType, Position, Traits >, BALL::RandomAccessIterator< Container, DataType, Position, Traits >, BALL::BidirectionalIterator< Composite, Composite, Composite *, CompositeIteratorTraits >, and BALL::ConstRandomAccessIterator< Container, DataType, Position, Traits >.
template<typename Container, typename DataType, typename Position, typename Traits> typedef std::bidirectional_iterator_tag BALL::ConstBidirectionalIterator< Container, DataType, Position, Traits >::iterator_category
Reimplemented from BALL::ConstForwardIterator< Container, DataType, Position, Traits >.
Reimplemented in BALL::ConstRandomAccessIterator< Container, DataType, Position, Traits >, and BALL::ConstRandomAccessIterator< Container, DataType, Position, Traits >.
Constructor & Destructor Documentation
template<typename Container, typename DataType, typename Position, typename Traits> BALL_INLINE BALL::ConstBidirectionalIterator< Container, DataType, Position, Traits >::ConstBidirectionalIterator () [inline]
template<typename Container, typename DataType, typename Position, typename Traits> BALL_INLINE BALL::ConstBidirectionalIterator< Container, DataType, Position, Traits >::ConstBidirectionalIterator (const ConstBidirectionalIterator< Container, DataType, Position, Traits > & iterator) [inline]
template<typename Container, typename DataType, typename Position, typename Traits> BALL_INLINE BALL::ConstBidirectionalIterator< Container, DataType, Position, Traits >::~ConstBidirectionalIterator () [inline]
template<typename Container, typename DataType, typename Position, typename Traits> BALL_INLINE BALL::ConstBidirectionalIterator< Container, DataType, Position, Traits >::ConstBidirectionalIterator (const Container & container) [inline, protected]
Construct an iterator bound to a specific container.
Member Function Documentation
template<typename Container, typename DataType , typename Position , typename Traits > BALL_INLINE ConstBidirectionalIterator< Container, DataType, Position, Traits > BALL::ConstBidirectionalIterator< Container, DataType, Position, Traits >::begin (const Container & container) throw (Exception::Precondition) [inline, static]
Return an iterator pointingto the first item of the container.
Reimplemented from BALL::ConstForwardIterator< Container, DataType, Position, Traits >.
Reimplemented in BALL::BidirectionalIterator< Container, DataType, Position, Traits >, BALL::ConstRandomAccessIterator< Container, DataType, Position, Traits >, BALL::RandomAccessIterator< Container, DataType, Position, Traits >, BALL::BidirectionalIterator< Composite, Composite, Composite *, CompositeIteratorTraits >, and BALL::ConstRandomAccessIterator< Container, DataType, Position, Traits >.
References BALL::ConstBidirectionalIterator< Container, DataType, Position, Traits >::toBegin().
template<typename Container, typename DataType , typename Position , typename Traits > BALL_INLINE ConstBidirectionalIterator< Container, DataType, Position, Traits > BALL::ConstBidirectionalIterator< Container, DataType, Position, Traits >::end (const Container & container) throw (Exception::Precondition) [inline, static]
Return an iterator pointing to the position after the last element.
Reimplemented from BALL::ConstForwardIterator< Container, DataType, Position, Traits >.
Reimplemented in BALL::BidirectionalIterator< Container, DataType, Position, Traits >, BALL::ConstRandomAccessIterator< Container, DataType, Position, Traits >, BALL::RandomAccessIterator< Container, DataType, Position, Traits >, BALL::BidirectionalIterator< Composite, Composite, Composite *, CompositeIteratorTraits >, and BALL::ConstRandomAccessIterator< Container, DataType, Position, Traits >.
References BALL::ConstBidirectionalIterator< Container, DataType, Position, Traits >::toEnd().
template<typename Container, typename DataType, typename Position, typename Traits> BALL_INLINE bool BALL::ConstBidirectionalIterator< Container, DataType, Position, Traits >::isBegin () const [inline]
Check whether the iterator points to the item at the beginning of the container.
Reimplemented from BALL::ConstForwardIterator< Container, DataType, Position, Traits >.
template<typename Container, typename DataType, typename Position, typename Traits> BALL_INLINE bool BALL::ConstBidirectionalIterator< Container, DataType, Position, Traits >::isEnd () const [inline]
Check whether the iterator points to the position after the last item of the container.
Reimplemented from BALL::ConstForwardIterator< Container, DataType, Position, Traits >.
Referenced by BALL::get5Prime().
template<typename Container, typename DataType, typename Position, typename Traits> BALL_INLINE bool BALL::ConstBidirectionalIterator< Container, DataType, Position, Traits >::isRBegin () const [inline]
Test whether the iterator points to the "reverse" first element of the container.
template<typename Container, typename DataType, typename Position, typename Traits> BALL_INLINE bool BALL::ConstBidirectionalIterator< Container, DataType, Position, Traits >::isREnd () const [inline]
Test wheter the iterator points to the position before the first element.
Referenced by BALL::CompositeIteratorTraits::isREnd().
template<typename Container , typename DataType , typename Position , typename Traits > BALL_INLINE ConstBidirectionalIterator< Container, DataType, Position, Traits > BALL::ConstBidirectionalIterator< Container, DataType, Position, Traits >::operator++ (int) throw (Exception::Precondition) [inline]
Postfix increment operator.
Reimplemented from BALL::ConstForwardIterator< Container, DataType, Position, Traits >.
Reimplemented in BALL::BidirectionalIterator< Container, DataType, Position, Traits >, and BALL::BidirectionalIterator< Composite, Composite, Composite *, CompositeIteratorTraits >.
References BALL_PRECONDITION_EXCEPTION, BALL::BaseIterator< Container, DataType, Position, Traits >::getTraits(), and BALL::BaseIterator< Container, DataType, Position, Traits >::isValid().
template<typename Container , typename DataType , typename Position , typename Traits > BALL_INLINE ConstBidirectionalIterator< Container, DataType, Position, Traits > & BALL::ConstBidirectionalIterator< Container, DataType, Position, Traits >::operator++ () throw (Exception::Precondition) [inline]
Increment operator.
Reimplemented from BALL::ConstForwardIterator< Container, DataType, Position, Traits >.
Reimplemented in BALL::BidirectionalIterator< Container, DataType, Position, Traits >, and BALL::BidirectionalIterator< Composite, Composite, Composite *, CompositeIteratorTraits >.
References BALL_PRECONDITION_EXCEPTION.
template<typename Container , typename DataType , typename Position , typename Traits > BALL_INLINE ConstBidirectionalIterator< Container, DataType, Position, Traits > BALL::ConstBidirectionalIterator< Container, DataType, Position, Traits >::operator-- (int) throw (Exception::Precondition) [inline]
Postfix decrement operator.
Reimplemented in BALL::BidirectionalIterator< Container, DataType, Position, Traits >, and BALL::BidirectionalIterator< Composite, Composite, Composite *, CompositeIteratorTraits >.
References BALL_PRECONDITION_EXCEPTION, BALL::BaseIterator< Container, DataType, Position, Traits >::getTraits(), and BALL::BaseIterator< Container, DataType, Position, Traits >::isSingular().
template<typename Container , typename DataType , typename Position , typename Traits > BALL_INLINE ConstBidirectionalIterator< Container, DataType, Position, Traits > & BALL::ConstBidirectionalIterator< Container, DataType, Position, Traits >::operator-- () throw (Exception::Precondition) [inline]
Decrement operator.
Reimplemented in BALL::BidirectionalIterator< Container, DataType, Position, Traits >, and BALL::BidirectionalIterator< Composite, Composite, Composite *, CompositeIteratorTraits >.
References BALL_PRECONDITION_EXCEPTION.
template<typename Container, typename DataType , typename Position , typename Traits > BALL_INLINE ConstBidirectionalIterator< Container, DataType, Position, Traits > BALL::ConstBidirectionalIterator< Container, DataType, Position, Traits >::rbegin (const Container & container) throw (Exception::Precondition) [inline, static]
Return an iterator pointing to the last element.
Reimplemented in BALL::BidirectionalIterator< Container, DataType, Position, Traits >, BALL::ConstRandomAccessIterator< Container, DataType, Position, Traits >, BALL::RandomAccessIterator< Container, DataType, Position, Traits >, BALL::BidirectionalIterator< Composite, Composite, Composite *, CompositeIteratorTraits >, and BALL::ConstRandomAccessIterator< Container, DataType, Position, Traits >.
References BALL::ConstBidirectionalIterator< Container, DataType, Position, Traits >::toRBegin().
template<typename Container, typename DataType , typename Position , typename Traits > BALL_INLINE ConstBidirectionalIterator< Container, DataType, Position, Traits > BALL::ConstBidirectionalIterator< Container, DataType, Position, Traits >::rend (const Container & container) throw (Exception::Precondition) [inline, static]
Return an iterator pointing to the positon before the first element.
Reimplemented in BALL::BidirectionalIterator< Container, DataType, Position, Traits >, BALL::ConstRandomAccessIterator< Container, DataType, Position, Traits >, BALL::RandomAccessIterator< Container, DataType, Position, Traits >, BALL::BidirectionalIterator< Composite, Composite, Composite *, CompositeIteratorTraits >, and BALL::ConstRandomAccessIterator< Container, DataType, Position, Traits >.
References BALL::ConstBidirectionalIterator< Container, DataType, Position, Traits >::toREnd().
template<typename Container , typename DataType , typename Position , typename Traits > BALL_INLINE void BALL::ConstBidirectionalIterator< Container, DataType, Position, Traits >::toBegin () throw (Exception::Precondition) [inline]
Move the iterator to the beginning of the container.
Reimplemented from BALL::ConstForwardIterator< Container, DataType, Position, Traits >.
References BALL_PRECONDITION_EXCEPTION.
Referenced by BALL::RandomAccessIterator< Container, DataType, Position, Traits >::begin(), BALL::ConstRandomAccessIterator< Container, DataType, Position, Traits >::begin(), BALL::BidirectionalIterator< Container, DataType, Position, Traits >::begin(), and BALL::ConstBidirectionalIterator< Container, DataType, Position, Traits >::begin().
template<typename Container , typename DataType , typename Position , typename Traits > BALL_INLINE void BALL::ConstBidirectionalIterator< Container, DataType, Position, Traits >::toEnd () throw (Exception::Precondition) [inline]
Move the iterator to the position after the last item of the container.
Reimplemented from BALL::ConstForwardIterator< Container, DataType, Position, Traits >.
References BALL_PRECONDITION_EXCEPTION, BALL::BaseIterator< Container, DataType, Position, Traits >::getTraits(), and BALL::BaseIterator< Container, DataType, Position, Traits >::isSingular().
Referenced by BALL::RandomAccessIterator< Container, DataType, Position, Traits >::end(), BALL::ConstRandomAccessIterator< Container, DataType, Position, Traits >::end(), BALL::BidirectionalIterator< Container, DataType, Position, Traits >::end(), BALL::ConstBidirectionalIterator< Container, DataType, Position, Traits >::end(), and BALL::CompositeIteratorTraits::toEnd().
template<typename Container , typename DataType , typename Position , typename Traits > BALL_INLINE void BALL::ConstBidirectionalIterator< Container, DataType, Position, Traits >::toRBegin () throw (Exception::Precondition) [inline]
Move the iterator to the "reverse" beginning of the container.
References BALL_PRECONDITION_EXCEPTION.
Referenced by BALL::RandomAccessIterator< Container, DataType, Position, Traits >::rbegin(), BALL::ConstRandomAccessIterator< Container, DataType, Position, Traits >::rbegin(), BALL::BidirectionalIterator< Container, DataType, Position, Traits >::rbegin(), and BALL::ConstBidirectionalIterator< Container, DataType, Position, Traits >::rbegin().
template<typename Container , typename DataType , typename Position , typename Traits > BALL_INLINE void BALL::ConstBidirectionalIterator< Container, DataType, Position, Traits >::toREnd () throw (Exception::Precondition) [inline]
Move the iterator to the position before the first element.
References BALL_PRECONDITION_EXCEPTION, BALL::BaseIterator< Container, DataType, Position, Traits >::getTraits(), and BALL::BaseIterator< Container, DataType, Position, Traits >::isSingular().
Referenced by BALL::RandomAccessIterator< Container, DataType, Position, Traits >::rend(), BALL::ConstRandomAccessIterator< Container, DataType, Position, Traits >::rend(), BALL::BidirectionalIterator< Container, DataType, Position, Traits >::rend(), BALL::ConstBidirectionalIterator< Container, DataType, Position, Traits >::rend(), and BALL::CompositeIteratorTraits::toREnd().