BALL::GeometricCenterProcessor Class Reference
[Geometric property processors.]
#include <BALL/STRUCTURE/geometricProperties.h>
Public Member Functions
Processor related methods
virtual bool start ()
virtual bool finish ()
virtual Processor::Result operator() (Atom &atom)
virtual Processor::Result operator() (const Vector3 &v)
Accessors
Vector3 & getCenter ()
Private Attributes
Vector3 center_
Size n_
Detailed Description
Calculates the geometric center of a given Composite object. This processor calculates the geometric center of the atom coordinates of a given molecular object.
The geometric center is calculated as follows:
\[ {C} = {1}{N} {i}{N} {r_i} \] Where ${r_i}$ represents the coordinates of the ith atom.
Member Function Documentation
virtual bool BALL::GeometricCenterProcessor::finish () [virtual]
finish method
Reimplemented from BALL::UnaryProcessor< Atom >.
Vector3& BALL::GeometricCenterProcessor::getCenter ()
Returns the center of the object
virtual Processor::Result BALL::GeometricCenterProcessor::operator() (const Vector3 & v) [virtual]
virtual Processor::Result BALL::GeometricCenterProcessor::operator() (Atom &) [inline, virtual]
operator ()
Reimplemented from BALL::UnaryProcessor< Atom >.
References BALL::Atom::getPosition(), and operator()().
Referenced by operator()().
virtual bool BALL::GeometricCenterProcessor::start () [virtual]
start method
Reimplemented from BALL::UnaryProcessor< Atom >.
Member Data Documentation
Vector3 BALL::GeometricCenterProcessor::center_ [private]
Size BALL::GeometricCenterProcessor::n_ [private]