BALL::Atom Class Reference
[Molecular Datastructures]
#include <BALL/KERNEL/atom.h>
Classes
class AttributeVector
class BondIteratorTraits
class StaticAtomAttributes
Public Types
Enumerations
enum { UNKNOWN_TYPE = -1, ANY_TYPE = 0, MAX_NUMBER_OF_BONDS = 12 }
enum Property { NUMBER_OF_PROPERTIES = 0 }
enum FullNameType {
NO_VARIANT_EXTENSIONS, ADD_VARIANT_EXTENSIONS, ADD_RESIDUE_ID, ADD_VARIANT_EXTENSIONS_AND_ID,
ADD_CHAIN_RESIDUE_ID, ADD_VARIANT_EXTENSIONS_AND_CHAIN_RESIDUE_ID
}
Public Member Functions
Constructors
Atom ()
Atom (const Atom &atom, bool deep=true)
Atom (Element &element, const String &name, const String &type_name=BALL_ATOM_DEFAULT_TYPE_NAME, Type atom_type=BALL_ATOM_DEFAULT_TYPE, const Vector3 &position=Vector3(BALL_ATOM_DEFAULT_POSITION), const Vector3 &velocity=Vector3(BALL_ATOM_DEFAULT_VELOCITY), const Vector3 &force=Vector3(BALL_ATOM_DEFAULT_FORCE), float charge=BALL_ATOM_DEFAULT_CHARGE, float radius=BALL_ATOM_DEFAULT_RADIUS, Index formal_charge=BALL_ATOM_DEFAULT_FORMAL_CHARGE)
Destructors
virtual ~Atom ()
virtual void clear ()
virtual void destroy ()
Persistence
virtual void persistentWrite (PersistenceManager &pm, const char *name=0) const throw (Exception::GeneralException)
virtual void persistentRead (PersistenceManager &pm) throw (Exception::GeneralException)
Assignment methods
void set (const Atom &atom, bool deep=true)
void get (Atom &atom, bool deep=true) const
Atom & operator= (const Atom &atom)
void swap (Atom &atom)
bool operator== (const Atom &atom) const
bool operator!= (const Atom &atom) const
Accessors
void setElement (const Element &element)
Assign the atom's element.
const Element & getElement () const
Return the atom's element.
void setCharge (float charge)
float getCharge () const
void setFormalCharge (Index formal_charge)
Set the atom's formal charge.
Index getFormalCharge () const
Return the atom's formal charge.
const Molecule * getMolecule () const
Molecule * getMolecule ()
Return the molecule the atom is contained in (mutable).
const Fragment * getFragment () const
Fragment * getFragment ()
Return the fragment the atom is contained in (mutable).
const Residue * getResidue () const
Residue * getResidue ()
Return the residue the atom is contained in (mutable).
const SecondaryStructure * getSecondaryStructure () const
SecondaryStructure * getSecondaryStructure ()
Return the secondary structure the atom is contained in (mutable).
const Chain * getChain () const
Chain * getChain ()
Return the chain the atom is contained in (mutable).
void setName (const String &name)
Set the atom name.
const String & getName () const
Return the atom name.
String getFullName (FullNameType type=ADD_VARIANT_EXTENSIONS) const
void setPosition (const Vector3 &position)
Vector3 & getPosition ()
Return the atom coordinates (mutable).
const Vector3 & getPosition () const
Return the atom coordinates (const).
void setRadius (float radius)
float getRadius () const
Return the atom radius.
void setType (Type atom_type)
Assign the numerical atom type.
Type getType () const
Return the (numerical) atom type.
String getTypeName () const
Return the atom type name.
void setTypeName (const String &name)
Assign the atom type name.
void setVelocity (const Vector3 &velocity)
const Vector3 & getVelocity () const
void setForce (const Vector3 &force)
const Vector3 & getForce () const
Return the atom's force vector (const).
Vector3 & getForce ()
Return the atom's force vector (mutable).
Size countBonds () const
Return the number of bonds.
Bond * getBond (Position index) throw (Exception::IndexOverflow)
const Bond * getBond (Position index) const throw (Exception::IndexOverflow)
Bond * getBond (const Atom &atom)
const Bond * getBond (const Atom &atom) const
Miscellaneous
Bond * createBond (Atom &atom) throw (Exception::TooManyBonds)
Bond * createBond (Bond &bond, Atom &atom) throw (Exception::TooManyBonds)
Bond * cloneBond (Bond &bond, Atom &atom)
bool destroyBond (const Atom &atom)
void destroyBonds ()
Atom * getPartnerAtom (Position i) throw (Exception::IndexOverflow)
const Atom * getPartnerAtom (Position i) const throw (Exception::IndexOverflow)
float getDistance (const Atom &a) const
Predicates
bool hasBond (const Bond &bond) const
bool isBoundTo (const Atom &atom) const
bool isBound () const
bool isGeminal (const Atom &atom) const
bool isVicinal (const Atom &atom) const
Debuggers and diagnostics
virtual bool isValid () const
virtual void dump (std::ostream &s=std::cout, Size depth=0) const
Internal iteration
bool applyBonds (UnaryProcessor< Bond > &processor)
Private Member Functions
void clear_ ()
void swapLastBond_ (const Atom *atom)
Static Private Member Functions
static Position nextIndex_ ()
Return the next unallocated index in the static attribute array.
static void freeIndex_ (Position index)
Free an index in the static attribute array.
Class friends
class Bond
typedef short Type
class Bond
External iteration
typedef Index BondIteratorPosition
typedef RandomAccessIterator
< Atom, Bond,
BondIteratorPosition,
BondIteratorTraits > BondIterator
typedef
ConstRandomAccessIterator
< Atom, Bond,
BondIteratorPosition,
BondIteratorTraits > BondConstIterator
Constant random access iterator for bonds.
typedef std::reverse_iterator
< BondIterator > BondReverseIterator
Reverse random access iterator for bonds.
typedef std::reverse_iterator
< BondConstIterator > BondConstReverseIterator
Constant reverse random access iterator for bonds.
class BondIteratorTraits
BondIterator beginBond ()
Return a bond iterator pointing to the first bond of the atom.
BondIterator endBond ()
Return a past-the-end bond iterator.
BondConstIterator beginBond () const
Return a constant bond iterator pointing to the first bond.
BondConstIterator endBond () const
Return a constant past-the-end bond iterator.
BondReverseIterator rbeginBond ()
Return a reverse bond iterator pointing to the last bond.
BondReverseIterator rendBond ()
Return a past-the-end bond iterator for reverse traversal.
BondConstReverseIterator rbeginBond () const
Return a constant reverse bond iterator pointing to the first atom.
BondConstReverseIterator rendBond () const
Return a constant past-the-end bond iterator for reverse traversal.
Efficient handling of atom attributes
typedef std::list< Atom * > AtomPtrList
typedef std::list< Position > AtomIndexList
Position getIndex () const
StaticAtomAttributes * getAttributePtr ()
const StaticAtomAttributes * getAttributePtr () const
static Position compact (const AtomIndexList &indices) throw (Exception::OutOfRange)
static AttributeVector & getAttributes ()
static const PreciseTime & getAttributesModificationTime ()
Attributes
static AttributeVector static_attributes_
static AtomIndexList free_list_
static PreciseTime attributes_changed_time_
time of the last resize of the attributes vector
Position index_
const Element * element_
String name_
String type_name_
float radius_
unsigned char number_of_bonds_
Bond * bond_ [MAX_NUMBER_OF_BONDS]
Detailed Description
Atom class. A class representing atoms. During each runtime instance of a program an atom is unique and identified by a Object::Handle . Atom equality is defined as atom identity, so there cannot be any two identical atoms. A linear ordering of atoms is defined as the linear order of the Object::Handle s.
Two atoms can be connected via a Bond . There can be only one bond between any two atoms (double bonds etc. are expressed via the bond order attribute of the bond) and the total number of bonds of an atom is limited to eight (can be changed at compile time, see MAX_NUMBER_OF_BONDS).
Since Atom is derived from ProperyManager , it may contain arbitrary, user-defined properties. An atom may be inserted in a Fragment instance ("parent fragment"). The "state" of an atom is defined by its attributes:
"element" - an instance of Element
"formal charge" - the formal charge of the atom
"charge" - the charge in multiples of the the proton charge
"name" - a string identifier
"type name" - a string identifier, meaningful in the the context of a forcefield only
"position" - the absolute position in cartesian coordinates (Angstrom)
"radius" - the radius (Angstrom)
"type" - an integer type, meaningful only in the context of a forcefield
"velocity" - velocity the velocity of the atom (Angstrom/ps)
"force" - the force experienced by the atom (for forcefield calculations, in units of Newton)
"bonds" - up to MAX_NUMBER_OF_BONDS bonds to other atoms
See also:
Bond
Molecule
AtomContainer
Member Typedef Documentation
typedef std::list<Position> BALL::Atom::AtomIndexList
typedef std::list<Atom*> BALL::Atom::AtomPtrList
typedef ConstRandomAccessIterator<Atom, Bond, BondIteratorPosition, BondIteratorTraits> BALL::Atom::BondConstIterator
Constant random access iterator for bonds.
typedef std::reverse_iterator<BondConstIterator> BALL::Atom::BondConstReverseIterator
Constant reverse random access iterator for bonds.
typedef RandomAccessIterator<Atom, Bond, BondIteratorPosition, BondIteratorTraits> BALL::Atom::BondIterator
Random access iterator for bonds.
typedef Index BALL::Atom::BondIteratorPosition
typedef std::reverse_iterator<BondIterator> BALL::Atom::BondReverseIterator
Reverse random access iterator for bonds.
typedef short BALL::Atom::Type
Atom type.
Member Enumeration Documentation
anonymous enum
Unnamed enumeration of all non-categorized constants.
Enumerator:
UNKNOWN_TYPE
Unknown atom type. The type assigned for default-constructed atoms.
ANY_TYPE
Any atom type. Used as a wild card in the context of forcefields mainly
MAX_NUMBER_OF_BONDS
Maximum number of bonds of an atom.
enum BALL::Atom::FullNameType
The type of name used for getFullName.
See also:
getFullName
Enumerator:
NO_VARIANT_EXTENSIONS
ADD_VARIANT_EXTENSIONS
ADD_RESIDUE_ID
ADD_VARIANT_EXTENSIONS_AND_ID
ADD_CHAIN_RESIDUE_ID
ADD_VARIANT_EXTENSIONS_AND_CHAIN_RESIDUE_ID
enum BALL::Atom::Property
Predefined properties. Enumeration of all properties that are used by the BALL kernel.
Enumerator:
NUMBER_OF_PROPERTIES
Reimplemented in BALL::PDBAtom.
Constructor & Destructor Documentation
BALL::Atom::Atom ()
Default constructor. The state of this instance is:
element type is unknown (Element::UNKNOWN)
formal charge is 0
charge is 0
name is empty string
type name is "?"
position is Vector3 (0,0,0)
radius is 0
type INVALID_TYPE
velocity is Vector3 (0,0,0)
force is Vector3 (0,0,0)
bond table is empty (atom has no bonds)
Returns:
Atom - new atom
See also:
Composite::Composite
PropertyManager::PropertyManager
BALL::Atom::Atom (const Atom & atom, bool deep = true)
Copy constructor. The copy is either deep (default) or shallow.
Note: Deep copying of atoms does not include bond cloning.
Parameters:
atom the atom to be copied (cloned)
deep make a deep (=true) or shallow (=false) copy of atom
Returns:
Atom - new constructed atom cloned from atom
See also:
Composite::Composite
PropertyManager::PropertyManager
BALL::Atom::Atom (Element & element, const String & name, const String & type_name = BALL_ATOM_DEFAULT_TYPE_NAME, Type atom_type = BALL_ATOM_DEFAULT_TYPE, const Vector3 & position = Vector3(BALL_ATOM_DEFAULT_POSITION), const Vector3 & velocity = Vector3(BALL_ATOM_DEFAULT_VELOCITY), const Vector3 & force = Vector3(BALL_ATOM_DEFAULT_FORCE), float charge = BALL_ATOM_DEFAULT_CHARGE, float radius = BALL_ATOM_DEFAULT_RADIUS, Index formal_charge = BALL_ATOM_DEFAULT_FORMAL_CHARGE)
Detailed state initializing constructor. The item bond table is empty (atom has no bonds).
Parameters:
element element type of the constructed atom
name name of the constructed atom
type_name type name name of the constructed atom
atom_type type of the constructed atom
position position of the constructed atom
velocity velocity of the constructed atom
force force acting upon the constructed atom
charge charge of the constructed atom
formal_charge formal charge of the constructed atom
radius radius of the constructed atom
Returns:
Atom - new constructed atom
See also:
Composite::Composite
PropertyManager::PropertyManager
virtual BALL::Atom::~Atom () [virtual]
Destructor. If the atom has bonds in common with an other atom that atom is disconnected and the associated Bond instance is destroyed. Calls Atom::destroy .
See also:
Atom::destroy
Member Function Documentation
bool BALL::Atom::applyBonds (UnaryProcessor< Bond > & processor)
Application of an unary processor on every contained bond.
Parameters:
processor a typed unary processor for Bond instances
Returns:
bool - true if application has been terminated successfully, false otherwise
BondConstIterator BALL::Atom::beginBond () const [inline]
Return a constant bond iterator pointing to the first bond.
BondIterator BALL::Atom::beginBond () [inline]
Return a bond iterator pointing to the first bond of the atom.
virtual void BALL::Atom::clear () [virtual]
Explicit default initialization. Calls Composite::clear and resets the attributes to the default values. In contrast to destroy , the atom is not removed from any composite structure, i.e. its parent fragment pointer remains unchanged.
See also:
Composite::clear
destroy
Reimplemented from BALL::Composite.
Reimplemented in BALL::PDBAtom.
void BALL::Atom::clear_ () [private]
Reimplemented in BALL::PDBAtom.
Bond* BALL::Atom::cloneBond (Bond & bond, Atom & atom)
Create a copy of a bond. This is mostly for internal use and should not be required by most users.
static Position BALL::Atom::compact (const AtomIndexList & indices) throw (Exception::OutOfRange) [static]
Compact memory for a list of atoms. This method packs the static attributes of the atom in the given range into a contiguous memory segment in order to increase locality.
Size BALL::Atom::countBonds () const
Return the number of bonds.
Bond* BALL::Atom::createBond (Bond & bond, Atom & atom) throw (Exception::TooManyBonds)
Create a new bond from an already existing instance of Bond. Initialize the bond bond to connect this instance to atom . Calls Bond::createBond . The state of the bond is initialzed to the default values.
Note: This method is recommended for use if a subclass of the Bond is to be used as the new bond. This permits extensibility of bonds to the framework client.
Returns:
Bond* - default initialized bond bond that connects this instance to atom
See also:
Bond::createBond
Bond* BALL::Atom::createBond (Atom & atom) throw (Exception::TooManyBonds)
Create a new bond to an atom. Create a new instance of Bond connecting this instance to atom . Calls Bond::createBond . The state of the bond is initialized to the default values.
Returns:
Bond* - default initialized Bond instance that connects this instance to atom
See also:
Bond::createBond
virtual void BALL::Atom::destroy () [virtual]
Explicit destructor. Destroy this instance explicitly and reset its attributes to the default values.
See also:
Composite::clear
Reimplemented from BALL::Composite.
Reimplemented in BALL::PDBAtom.
bool BALL::Atom::destroyBond (const Atom & atom)
Explicit bond destruction. Destroy the bond connecting {*this atom} and atom explicitly. If the bond is auto-deletable the default destructor is called otherwise Bond::destroy .
Note: This method is recommended to destroy a bond of an atom explicitly instead of using the keyword delete. This is due to erroneous explicit destruction of statically allocated bonds.
Parameters:
atom the atom that should be disconnected from this instance
See also:
AutoDeletable
Bond::destroy
void BALL::Atom::destroyBonds ()
Explicit bond table destruction. Destroy all the bonds connecting {*this atom} with another atom explicitly. If the bonds are auto-deletable the default destructors are called otherwise Bond::destroy .
Note: This method is recommended to destroy all bonds of an atom explicitly instead of using the keyword delete. This is due to erroneous explicit destruction of statically allocated bonds.
Parameters:
atom the atom that should be disconnected from this instance
See also:
AutoDeletable
Bond::destroy
virtual void BALL::Atom::dump (std::ostream & s = std::cout, Size depth = 0) const [virtual]
Internal state dump. Dump the current internal state of this instance to the output ostream s with dumping depth depth . For debugging purposes only.
Parameters:
s - output stream where to output the internal state
depth - the dumping depth
Reimplemented from BALL::Composite.
Reimplemented in BALL::PDBAtom.
BondConstIterator BALL::Atom::endBond () const [inline]
Return a constant past-the-end bond iterator.
BondIterator BALL::Atom::endBond () [inline]
Return a past-the-end bond iterator.
static void BALL::Atom::freeIndex_ (Position index) [static, private]
Free an index in the static attribute array.
void BALL::Atom::get (Atom & atom, bool deep = true) const
Deep/shallow assignment. The inverse operation to set , behaves identically.
Parameters:
atom the atom to be assigned to
See also:
Atom::set
const StaticAtomAttributes* BALL::Atom::getAttributePtr () const
StaticAtomAttributes* BALL::Atom::getAttributePtr ()
static AttributeVector& BALL::Atom::getAttributes () [static]
Access to the static attribute array
Referenced by BALL::AmberTorsion::SingleAmberTorsion::SingleAmberTorsion().
static const PreciseTime& BALL::Atom::getAttributesModificationTime () [inline, static]
Get the time, when the attributes vector was last modified. This needed for the GeometricObject 's in VIEW, because they store pointer to the position of atoms. These have to be updated, after a resize of the vector.
const Bond* BALL::Atom::getBond (const Atom & atom) const
Return a bond by its partner atom (mutable) The reference is 0 if this instance does not have a bond with atom .
Parameters:
atom the atom that is considered to have a bond with this instance
Returns:
Bond* - constant pointer to the bond that connects atom with this instance, 0 if this instance does not have a bond with atom
See also:
Atom::createBond
Bond* BALL::Atom::getBond (const Atom & atom)
Return a bond by its partner atom (const). The reference is 0 if this instance does not have a bond with atom .
Parameters:
atom the atom that is considered to have a bond with this instance
Returns:
Bond* - mutable pointer to the bond that connects atom with this instance, 0 if this instance does not have a bond with atom
See also:
Atom::createBond
const Bond* BALL::Atom::getBond (Position index) const throw (Exception::IndexOverflow)
Return a bond by its index (const).
Exceptions:
IndexOverflow if index >= MAX_NUMBER_OF_BONDS
Bond* BALL::Atom::getBond (Position index) throw (Exception::IndexOverflow)
Return a bond by its index (mutable). The reference is 0 if this instance does not have a bond with index index .
Note: No corresponding mutator Atom::setBond exists to consider design of contract - an atom may not insert a bond in its bond table at a given index. The atom's bond table is an implementation detail that is not relevant to and should not be relied on by the client programmer. A bond must always be created via Bond::Bond or Atom::createBond .
Parameters:
index the index of the bond to be accessed to
Returns:
Bond* - mutable pointer to the bond that is indexed in this instance's bond table, 0 if this instance does not have a bond with index index
Exceptions:
IndexOverflow if index >= MAX_NUMBER_OF_BONDS
Chain* BALL::Atom::getChain ()
Return the chain the atom is contained in (mutable).
Reimplemented in BALL::PDBAtom.
const Chain* BALL::Atom::getChain () const
Return the chain the atom is contained in (const). A NULL pointer is returned if this atom is not part of a chain.
Returns:
Chain* - constant pointer to the chain
Reimplemented in BALL::PDBAtom.
Referenced by BALL::PDB::Structure::AtomEntry::AtomEntry().
float BALL::Atom::getCharge () const
Return the atom's (partial) charge. Charges should be assigned in multiples of the proton charge (elementary charge).
float BALL::Atom::getDistance (const Atom & a) const
A convenience function for computing the distance between two atoms. This is equivalent to calling this->getPosition().getDistance(a.getPosition())
Parameters:
a the atom to which to compute the distance
const Element& BALL::Atom::getElement () const
Return the atom's element.
Vector3& BALL::Atom::getForce ()
Return the atom's force vector (mutable).
const Vector3& BALL::Atom::getForce () const
Return the atom's force vector (const).
Index BALL::Atom::getFormalCharge () const
Return the atom's formal charge.
Reimplemented in BALL::SmilesParser::SPAtom.
Fragment* BALL::Atom::getFragment ()
Return the fragment the atom is contained in (mutable).
const Fragment* BALL::Atom::getFragment () const
Return the fragment the atom is contained in (const). A NULL pointer is returned if this atom is not part of a fragment.
Use Fragment::insert to insert an atom into a fragment and Fragment::remove to remove it.
Returns:
Fragment* - constant pointer to the fragment
String BALL::Atom::getFullName (FullNameType type = ADD_VARIANT_EXTENSIONS) const
Assemble a fully specified atom name. This method returns at fully specified atom name as used for charge and type assignments. The name consists of the name of the residue the atom is contained in, a colon, and the atom name. Blanks are removed from both names. For example, for the alpha carbon atom of isoleucine getFullName will return the name ILE:CA. For N terminal residues, -N is appended to the residue name, for C terminal residues -C. If the residue is a CYS involved in a disulphide bridge, an additional -S or S (for terminal residue) is appended. For single amino acids (C and N terminal) -M is added.
If the atom is not contained in a residue, the name of the parent fragment is taken instead of the residue name. If there is no parent fragment, the name of the parent molecule is taken. If the atom is not contained in any superstructure, getFullname returns getName.
Overview of the returned strings:
<residue>:<atom> -- if contained in a residue
<residue>-C:<atom> -- for C terminal residues
<residue>-N:<atom> -- for N terminal residues
CYS-S:<atom> -- for CYS residues involved in a SS bond
CYS-NS:<atom> -- for N terminal CYS residues involved in a SS bond
CYS-CS:<atom> -- for C terminal CYS residues involved in a SS bond
<fragment>:atom -- for atoms contained in a fragment, but not in a residue
<molecule>:atom -- for atoms contained in a molecule, but not in a fragment
Parameters:
type if type is set to Atom::NO_VARIANT_EXTENSIONS, the variant extension (-XX) is omitted
Returns:
String the full name
Position BALL::Atom::getIndex () const
Return the index in the static attribute array
Referenced by BALL::AmberTorsion::SingleAmberTorsion::SingleAmberTorsion().
Molecule* BALL::Atom::getMolecule ()
Return the molecule the atom is contained in (mutable).
const Molecule* BALL::Atom::getMolecule () const
Return the molecule the atom is contained in (const). A NULL pointer is returned if this atom is not part of a molecule.
Use Molecule::insert to insert an atom into a molecule and Molecule::remove to remove it.
Returns:
Molecule* - constant pointer to the parent molecule
const String& BALL::Atom::getName () const
Return the atom name.
const Atom* BALL::Atom::getPartnerAtom (Position i) const throw (Exception::IndexOverflow)
Returns the Atom bound at the i-th bond. This is a convenience function for: getBond(i)->getBoundAtom(*this)
Parameters:
i The index of the partner atom
Atom* BALL::Atom::getPartnerAtom (Position i) throw (Exception::IndexOverflow)
Returns the Atom bound at the i-th bond. This is a convenience function for: getBond(i)->getBoundAtom(*this)
Parameters:
i The index of the partner atom
Exceptions:
Exception::IndexOverflow is thrown if i >= countBonds(). This exception originates from getBond(i)
const Vector3& BALL::Atom::getPosition () const
Return the atom coordinates (const).
Vector3& BALL::Atom::getPosition ()
Return the atom coordinates (mutable).
Referenced by BALL::GeometricCenterProcessor::operator()(), and BALL::BoundingBoxProcessor::operator()().
float BALL::Atom::getRadius () const
Return the atom radius.
Residue* BALL::Atom::getResidue ()
Return the residue the atom is contained in (mutable).
Reimplemented in BALL::PDBAtom.
const Residue* BALL::Atom::getResidue () const
Return the residue the atom is contained in (const). A NULL pointer is returned if this atom is not part of a residue.
Use Residue::insert to insert an atom into a residue and Residue::remove to remove it.
Returns:
Residue* - constant pointer to the residue
Reimplemented in BALL::PDBAtom.
Referenced by BALL::PDB::Structure::AtomEntry::AtomEntry().
SecondaryStructure* BALL::Atom::getSecondaryStructure ()
Return the secondary structure the atom is contained in (mutable).
const SecondaryStructure* BALL::Atom::getSecondaryStructure () const
Return the secondary structure the atom is contained in (const). A NULL pointer is returned if this atom is not part of a secondary structure.
Returns:
SecondaryStructure* - constant pointer to the secondary structure
Referenced by BALL::PDB::Structure::AtomEntry::AtomEntry().
Type BALL::Atom::getType () const
Return the (numerical) atom type.
String BALL::Atom::getTypeName () const
Return the atom type name.
const Vector3& BALL::Atom::getVelocity () const
Return the atom velocity. BALL uses units of for the velocity.
bool BALL::Atom::hasBond (const Bond & bond) const
Determine whether the atom takes part in a certain bond.
Parameters:
bond the bond in question
Returns:
bool true if the bond bond connects this instance with another atom, false otherwise
See also:
Atom::hasBond
bool BALL::Atom::isBound () const
Determine whether the atom has any bond.
Returns:
bool - true if an atom is bound to this instance, false otherwise
See also:
Atom::hasBond
bool BALL::Atom::isBoundTo (const Atom & atom) const
Determine whether there exists a bond to another atom. Calls Atom::getBond . Hydrogen bonds (type = Bond::TYPE__HYDROGEN) are ignored.
Parameters:
atom the atom in question
Returns:
bool - true if bond connects atom with {*this atom}, false otherwise
See also:
Atom::getBond
bool BALL::Atom::isGeminal (const Atom & atom) const
True if the two atoms are geminal. Two atoms are geminal if they do not share a common bond but both have a bond to a third atom. For example the two hydrogen atoms in water are geminal. Hydrogen bonds (type = Bond::TYPE__HYDROGEN) are ignored.
Parameters:
atom the second atom
Returns:
bool - true if atom is geminal to this instance
virtual bool BALL::Atom::isValid () const [virtual]
Internal state and consistency self-validation.
Returns:
bool - true if the internal state of this instance is correct (self-validated) and consistent, false otherwise
Reimplemented from BALL::Composite.
bool BALL::Atom::isVicinal (const Atom & atom) const
True if the two atoms are vicinal. Two atoms are vicinal if they are separated by three bonds (1-4 position). Hydrogen bonds (type = Bond::TYPE__HYDROGEN) are ignored.
Parameters:
atom the second atom
Returns:
bool - true if atom is vicinal to this instance
static Position BALL::Atom::nextIndex_ () [static, private]
Return the next unallocated index in the static attribute array.
bool BALL::Atom::operator!= (const Atom & atom) const
Inequality operator
See also:
operator ==
Atom& BALL::Atom::operator= (const Atom & atom)
Assignment operator. The assignment is always deep. Calls Atom::set .
Note: Bonds are not copied
Parameters:
atom the atom to be copied
Returns:
Atom& - this instance
See also:
Atom::set
bool BALL::Atom::operator== (const Atom & atom) const
Predicates Equality operator. Two atoms are equal if they have the same handle.
See also:
Object::operator ==
virtual void BALL::Atom::persistentRead (PersistenceManager & pm) throw (Exception::GeneralException) [virtual]
Read an Atom from a persistent stream.
Parameters:
pm the persistence manager
Reimplemented from BALL::Composite.
Reimplemented in BALL::PDBAtom.
virtual void BALL::Atom::persistentWrite (PersistenceManager & pm, const char * name = 0) const throw (Exception::GeneralException) [virtual]
Write an Atom to a persistent stream.
Parameters:
pm the persistence manager
Reimplemented from BALL::Composite.
Reimplemented in BALL::PDBAtom.
BondConstReverseIterator BALL::Atom::rbeginBond () const [inline]
Return a constant reverse bond iterator pointing to the first atom.
BondReverseIterator BALL::Atom::rbeginBond () [inline]
Return a reverse bond iterator pointing to the last bond.
BondConstReverseIterator BALL::Atom::rendBond () const [inline]
Return a constant past-the-end bond iterator for reverse traversal.
BondReverseIterator BALL::Atom::rendBond () [inline]
Return a past-the-end bond iterator for reverse traversal.
void BALL::Atom::set (const Atom & atom, bool deep = true)
Deep/shallow assignment. The assignment is either deep or shallow (default is deep). In the case of a deep assignment, all composites contained in atom are copied as well.
Caveat: Bonds are not copied!
Parameters:
atom the atom to be copied
deep make a deep (=true) or shallow (=false) copy of atom
void BALL::Atom::setCharge (float charge)
Set the atom's (partial) charge. Charges should be assigned in multiples of the proton charge (elementary charge).
void BALL::Atom::setElement (const Element & element)
Assign the atom's element.
void BALL::Atom::setForce (const Vector3 & force)
Assign the atom's force vevtor. BALL uses units of Newton (1 N = 1 J/m) as the unit of force.
void BALL::Atom::setFormalCharge (Index formal_charge)
Set the atom's formal charge.
Reimplemented in BALL::SmilesParser::SPAtom.
void BALL::Atom::setName (const String & name)
Set the atom name.
void BALL::Atom::setPosition (const Vector3 & position)
Assign the atom coordinates. BALL uses units of Angstrom for atom coordinates.
void BALL::Atom::setRadius (float radius)
Set the atom radius. BALL uses units of Angstrom for the atom radii.
void BALL::Atom::setType (Type atom_type)
Assign the numerical atom type.
void BALL::Atom::setTypeName (const String & name)
Assign the atom type name.
void BALL::Atom::setVelocity (const Vector3 & velocity)
Set the atom velocity BALL uses units of for the velocity.
void BALL::Atom::swap (Atom & atom)
Swap the contents of two atoms. The static attributes are swapped by exchanging the indices of the two atoms!
Parameters:
atom the atom being swapped with this instance
void BALL::Atom::swapLastBond_ (const Atom * atom) [private]
Friends And Related Function Documentation
friend class Bond [friend]
Reimplemented in BALL::PDBAtom.
friend class BondIteratorTraits [friend]
Member Data Documentation
PreciseTime BALL::Atom::attributes_changed_time_ [static, protected]
time of the last resize of the attributes vector
Bond* BALL::Atom::bond_[MAX_NUMBER_OF_BONDS] [protected]
const Element* BALL::Atom::element_ [protected]
AtomIndexList BALL::Atom::free_list_ [static, protected]
Position BALL::Atom::index_ [protected]
String BALL::Atom::name_ [protected]
unsigned char BALL::Atom::number_of_bonds_ [protected]
float BALL::Atom::radius_ [protected]
AttributeVector BALL::Atom::static_attributes_ [static, protected]
String BALL::Atom::type_name_ [protected]