BALL Namespace Reference
Namespaces
namespace Constants
namespace Exception
namespace Maths
namespace MolmecSupport
namespace PDB
namespace Peptides
namespace RTTI
namespace SysInfo
namespace VIEW
Classes
class HashFunction
class GlobalInitializer
class Limits
class Limits< float >
class Limits< double >
class Limits< bool >
class Limits< char >
class Limits< signed char >
class Limits< unsigned char >
class Limits< short >
class Limits< unsigned short >
class Limits< int >
class Limits< unsigned int >
class Limits< long >
class Limits< unsigned long >
class LogStreamBuf
class LogStreamNotifier
class LogStream
class VersionInfo
class AutoDeletable
class UnaryFunctor
class BinaryFunctor
class BaseIterator
class ConstBidirectionalIterator
class BidirectionalIterator
Mutable bidirectional iterator.
class Client
class Comparator
class Composite
class Embeddable
class EnumeratorIndex
class Enumerator
class Factory
class ConstForwardIterator
class ForwardIterator
class MolecularInformation
class MoleculeObjectCreator
class NotificationTarget_
class NotificationSource_
class NotificationSlot_
class NotificationManager_
class NotificationTarget
class NotificationTarget1
class NotificationTarget2
class Object
class ObjectCreator
class PersistenceManager
class PersistentObject
class UnaryPredicate
class BinaryPredicate
class PreferencesObject
class Processor
class UnaryProcessor
class BinaryProcessor
class NamedProperty
class PropertyManager
class ConstRandomAccessIterator
class RandomAccessIterator
class Selectable
class TextPersistenceManager
class PreciseTime
class TimeStamp
class Visitor
class XDRPersistenceManager
class Bit
class BitVector
class TContour
class TContourLine
class TContourSurface
class HashGridBox3
class HashGrid3
class HashMap
HashMap class based on the STL map (containing serveral convenience functions).
class HashSet
class List
class Options
class Quadruple
class TRegularData1D
class TRegularData2D
class TRegularData3D
class RegularExpression
class String
class Substring
class StringHashMap
class Triple
class ComposedEnergyProcessor
class EnergyProcessor
class Bruker1DFile
class Bruker2DFile
class DCDFile
class DSN6File
class GAMESSDatFile
class GAMESSLogFile
class GenericMolFile
class HINFile
class INIFile
class JCAMPFile
class KCFFile
class LineBasedFile
class MOL2File
class MOLFile
class MolFileFactory
struct NMRAtomData
struct SampleCondition
struct ShiftReferenceElement
struct ShiftReferenceSet
struct NMRAtomDataSet
class NMRStarFile
class Parameters
class ParameterSection
class PDBFile
class PDBInfo
class PDBRecords
class ResourceEntry
class ResourceFile
class SCWRLRotamerFile
Reads Dunbrack/SCWRL rotamer library files.
class SDFile
class TrajectoryFile
class TRRFile
class XYZFile
class Atom
class AtomContainer
class AtomContainerIteratorTraits
class AtomIteratorTraits
class Bond
class Chain
class ChainIteratorTraits
class Expression
class ExpressionParser
class ExpressionPredicate
class ExpressionTree
class Fragment
class FragmentIteratorTraits
class CompositeIteratorTraits
class Molecule
class MoleculeIteratorTraits
class NucleicAcid
class NucleicAcidIteratorTraits
class Nucleotide
class NucleotideIteratorTraits
class PDBAtom
class PDBAtomIteratorTraits
class KernelPredicate
Kernel predicate class.
class Protein
class ProteinIteratorTraits
class Element
class PTE_
class Residue
class ResidueIteratorTraits
class SecondaryStructure
class SecondaryStructureIteratorTraits
class Selector
class TruePredicate
class FalsePredicate
class SelectedPredicate
class AtomNamePredicate
class AtomTypePredicate
class ElementPredicate
class ResiduePredicate
class ResidueIDPredicate
class ProteinPredicate
class ChainPredicate
class SecondaryStructurePredicate
class SolventPredicate
class MoleculePredicate
class BackBonePredicate
class NucleicAcidPredicate
class NucleotidePredicate
class InRingPredicate
class NumberOfBondsPredicate
class SingleBondsPredicate
class DoubleBondsPredicate
class TripleBondsPredicate
class AromaticBondsPredicate
class ConnectedToPredicate
class SpHybridizedPredicate
class Sp2HybridizedPredicate
class Sp3HybridizedPredicate
class ChargePredicate
class AxialPredicate
class Conformation4C1Predicate
class RingFinder
class SMARTSPredicate
class System
class TAngle
class TBox3
class TCircle3
class TFFT1D
class TFFT2D
class TFFT3D
struct DoubleTraits
struct FloatTraits
struct LongDoubleTraits
class ConstantFunction
class MutableConstant
class Addition
class Subtraction
class Product
class Division
class Reciprocal
class SquareFunction
class CubicFunction
class MutablePower
class TLine3
class TMatrix4x4
class NumericalIntegrator
class ParsedFunction
class PiecewiseFunction
class PiecewisePolynomial
class TPlane3
class TQuaternion
class RandomNumberGenerator
class RombergIntegrator
class TSimpleBox3
class TSphere3
class TSurface
class TVector2
class TVector3
class TVector4
class AmberFF
class AmberBend
class AmberNonBonded
class AmberStretch
class AmberTorsion
class GAFFCESParser
class GAFFTypeProcessor
class CharmmFF
class CharmmBend
class CharmmImproperTorsion
class CharmmNonBonded
class CharmmStretch
class CharmmTorsion
class AssignBaseProcessor
Only used for deriving interface.
class AssignTypeProcessor
class AssignTypeNameProcessor
class AtomVector
class ChargeRuleProcessor
class ForceField
class ForceFieldComponent
class Gradient
class PeriodicBoundary
class RadiusRuleProcessor
class RuleEvaluator
class RuleProcessor
class SnapShot
class SnapShotManager
class TypenameRuleProcessor
class TypeRuleProcessor
class CanonicalMD
class MicroCanonicalMD
class MolecularDynamics
class ConjugateGradientMinimizer
class EnergyMinimizer
class LineSearch
class ShiftedLVMMMinimizer
class SteepestDescentMinimizer
class StrangLBFGSMinimizer
class MMFF94
class MMFF94NonBonded
class MMFF94OutOfPlaneBend
class MMFF94ParametersBase
class MMFF94AtomTypeEquivalences
struct MMFF94AtomType
Class to store the values of an atom type from MMFFPROP.PAR.
class MMFF94AtomTypes
class MMFF94StretchParameters
class MMFF94BendParameters
class MMFF94StretchBendParameters
class MMFF94TorsionParameters
class MMFF94PlaneParameters
class MMFF94VDWParameters
class MMFF94ESParameters
class MMFF94AtomTyper
class MMFF94ChargeProcessor
class MMFF94StretchBend
class MMFF94Torsion
class AtomTypes
class CharmmEEF1
class CosineTorsion
class ForceFieldParameters
class LennardJones
class Potential1210
class QuadraticAngleBend
class QuadraticBondStretch
class QuadraticImproperTorsion
class ResidueTorsions
class Templates
class AnisotropyShiftProcessor
class AssignShiftProcessor
class ClearShiftProcessor
class CreateSpectrumProcessor
class EFShiftProcessor
class Experiment
class SimpleExperiment1D
class HaighMallionShiftProcessor
class HBondShiftProcessor
class JohnsonBoveyShiftProcessor
class Peak
class PeakList
class RandomCoilShiftProcessor
class ShiftModel
class ShiftModule
class Spectrum
class BALLPlugin
class PluginHandler
class PluginManager
class PyColorRGBAVector
class PyCompositeList
class Constant
class PyDatasetVector
class PyIndexList
class PyInterpreter
class AromaticityProcessor
class ConnectivityBase
class ZagrebIndex
class BalabanIndexJ
class Descriptor
class PartialChargeBase
class TotalPositivePartialCharge
class TotalNegativePartialCharge
class RelPositivePartialCharge
class RelNegativePartialCharge
class PartialChargeProcessor
class RingPerceptionProcessor
class SimpleBase
class MolecularWeight
class NumberOfBonds
class NumberOfSingleBonds
class NumberOfDoubleBonds
class NumberOfTripleBonds
class NumberOfAromaticBonds
class NumberOfAtoms
class NumberOfBoron
class NumberOfCarbon
class NumberOfNitrogen
class NumberOfOxygen
class NumberOfFlourine
class NumberOfPhosphorus
class NumberOfSulfur
class NumberOfChlorine
class NumberOfBromine
class NumberOfIodine
class NumberOfHydrogen
class FormalCharge
class NumberOfHeavyAtoms
class MeanAtomInformationContent
class AtomInformationContent
class NumberOfRotatableSingleBonds
class RelNumberOfRotatableSingleBonds
class NumberOfAromaticAtoms
class NumberOfHeavyBonds
class NumberOfRotatableBonds
class RelNumberOfRotatableBonds
class VertexAdjacency
class VertexAdjacencyEquality
class NumberOfHydrogenBondAcceptors
class NumberOfHydrogenBondDonors
class NumberOfHydrophobicAtoms
class BondPolarizabilities
class AtomicPolarizabilities
class SizeOfSSSR
class PrincipalMomentOfInertia
class PrincipalMomentOfInertiaX
class PrincipalMomentOfInertiaY
class PrincipalMomentOfInertiaZ
class SurfaceBase
class PositiveVdWSurface
class NegativeVdWSurface
class PositivePolarVdWSurface
class NegativePolarVdWSurface
class HydrophobicVdWSurface
class PolarVdWSurface
class RelPositiveVdWSurface
class RelNegativeVdWSurface
class RelPositivePolarVdWSurface
class RelNegativePolarVdWSurface
class RelHydrophobicVdWSurface
class RelPolarVdWSurface
class VdWVolume
class Density
class VdWSurface
class ScoringBaseFunction
class FermiBaseFunction
class LinearBaseFunction
class ScoringComponent
class ScoringFunction
class ScoringTypes
class AromaticRingStacking
class BuriedPolar
class CHPI
class HydrogenBond
class Lipophilic
class ChemScoreMetal
class NonpolarSolvation
class PolarSolvation
class RotationalEntropyLoss
class VanDerWaals
class SLICKEnergy
class SLICKScore
class FresnoTypes
class ClaverieParameter
class ElectrostaticPotentialCalculator
class GeneralizedBornModel
class Pair6_12InteractionEnergyProcessor
class Pair6_12RDFIntegrator
class PairExpInteractionEnergyProcessor
class PairExpRDFIntegrator
class PCMCavFreeEnergyProcessor
class PierottiCavFreeEnergyProcessor
class FDPB
class ReissCavFreeEnergyProcessor
class SolventAtomDescriptor
class SolventDescriptor
class SolventParameter
class UhligCavFreeEnergyProcessor
class AddHydrogenProcessor
class AssignBondOrderProcessor
class AtomBijection
class AtomTyper
class BindingPocketProcessor
class BuildBondsProcessor
class ChainBuilder
This class provides methods for analysis of the chains in a molecule.
class ClearChargeProcessor
class ClearRadiusProcessor
class AssignRadiusProcessor
class AssignChargeProcessor
class DNAMutator
class AmberEvaluation
class ConformationSet
class DockingAlgorithm
class DockResult
class EnergeticEvaluation
class ForceFieldEvaluation
class GeometricFit
class RandomEvaluation
class FragmentDB
class BoundingBoxProcessor
class GeometricCenterProcessor
class FragmentDistanceCollector
class TranslationProcessor
class TransformationProcessor
class GraphEdge
class GraphFace
class GraphTriangle
class GraphVertex
class HBondProcessor
class HybridisationProcessor
class Kekuliser
class NodeItem
class EdgeItem
class TMolecularGraph
class MoleculeAssembler
class, providing methods for the assembly of a structure diagram
class NumericalSAS
class RadialDistributionFunction
class RDFIntegrator
class RDFParameter
class RDFSection
class ReconstructFragmentProcessor
class ReducedSurface
class RSComputer
class ResidueChecker
class Rotamer
class ResidueRotamerSet
class RingAnalyser
class, providing methods for the analysis of the structure of ringsystems
class RingClusterer
class, providing a method for agglomerative clustering of single rings to ringsystems
class RMSDMinimizer
class RotamerLibrary
Rotamer Library Class.
class RSConstructor
class, performing the prefabication of ringsystems (i.e. providing them with relative 2D-coordinates)
class RSEdge
class RSFace
class RSVertex
class SASEdge
class SASFace
class SASVertex
class SDGenerator
The main class, provides methods for analysis of the input.
class SecondaryStructureProcessor
class SESEdge
class SESFace
class SESVertex
class SmartsMatcher
class SmartsParser
class SmilesParser
class SolventAccessibleSurface
class SolventExcludedSurface
class SESComputer
class SESSingularityCleaner
class StructureMapper
class SurfaceProcessor
class Triangle
class TriangleEdge
class TrianglePoint
class TriangulatedSAS
class SASTriangulator
class TriangulatedSES
class SESTriangulator
class TriangulatedSurface
class TriangulatedSphere
class UCK
class Directory
class TransformationManager
class File
class BinaryFileAdaptor
class FileSystem
class TMutex
class TMutex< QMutex >
class TMutexLocker
class TReadWriteLock
class TReadWriteLock< QReadWriteLock >
class TReadLocker
class TWriteLocker
class TCPIOStream
class TCPServer
class TCPServerThread
class Path
class TCPTransfer
class Timer
class Mainframe
Typedefs
typedef int(* ComparatorType)(const void *, const void *)
typedef TContour< float > Contour
typedef TContourLine< float > ContourLine
typedef Index FacetArray [256][12]
typedef TContourSurface< float > ContourSurface
Default type.
typedef TRegularData1D< float > RegularData1D
typedef TRegularData2D< float > RegularData2D
typedef TRegularData3D< float > RegularData3D
typedef HashSet< String > StringHashSet
typedef List< EnergyProcessor * > EnergyProcessorList
typedef BidirectionalIterator
< Composite, Fragment,
Composite::CompositeIterator,
FragmentIteratorTraits > FragmentIterator
typedef
ConstBidirectionalIterator
< Composite, Fragment,
Composite::CompositeIterator,
FragmentIteratorTraits > FragmentConstIterator
typedef std::reverse_iterator
< FragmentIterator > FragmentReverseIterator
typedef std::reverse_iterator
< FragmentConstIterator > FragmentConstReverseIterator
typedef BidirectionalIterator
< Composite, Molecule,
Composite::CompositeIterator,
MoleculeIteratorTraits > MoleculeIterator
typedef
ConstBidirectionalIterator
< Composite, Molecule,
Composite::CompositeIterator,
MoleculeIteratorTraits > MoleculeConstIterator
typedef std::reverse_iterator
< MoleculeIterator > MoleculeReverseIterator
typedef std::reverse_iterator
< MoleculeConstIterator > MoleculeConstReverseIterator
typedef BidirectionalIterator
< Composite, NucleicAcid,
Composite::CompositeIterator,
NucleicAcidIteratorTraits > NucleicAcidIterator
typedef
ConstBidirectionalIterator
< Composite, NucleicAcid,
Composite::CompositeIterator,
NucleicAcidIteratorTraits > NucleicAcidConstIterator
typedef std::reverse_iterator
< NucleicAcidIterator > NucleicAcidReverseIterator
typedef std::reverse_iterator
< NucleicAcidConstIterator > NucleicAcidConstReverseIterator
typedef BidirectionalIterator
< Composite, Nucleotide,
Composite::CompositeIterator,
NucleotideIteratorTraits > NucleotideIterator
typedef
ConstBidirectionalIterator
< Composite, Nucleotide,
Composite::CompositeIterator,
NucleotideIteratorTraits > NucleotideConstIterator
typedef std::reverse_iterator
< NucleotideIterator > NucleotideReverseIterator
typedef std::reverse_iterator
< NucleotideConstIterator > NucleotideConstReverseIterator
typedef BidirectionalIterator
< Composite, Protein,
Composite::CompositeIterator,
ProteinIteratorTraits > ProteinIterator
typedef
ConstBidirectionalIterator
< Composite, Protein,
Composite::CompositeIterator,
ProteinIteratorTraits > ProteinConstIterator
typedef std::reverse_iterator
< ProteinIterator > ProteinReverseIterator
typedef std::reverse_iterator
< ProteinConstIterator > ProteinConstReverseIterator
typedef BidirectionalIterator
< Composite, Residue,
Composite::CompositeIterator,
ResidueIteratorTraits > ResidueIterator
typedef
ConstBidirectionalIterator
< Composite, Residue,
Composite::CompositeIterator,
ResidueIteratorTraits > ResidueConstIterator
typedef std::reverse_iterator
< ResidueIterator > ResidueReverseIterator
typedef std::reverse_iterator
< ResidueConstIterator > ResidueConstReverseIterator
typedef BidirectionalIterator
< Composite,
SecondaryStructure,
Composite::CompositeIterator,
SecondaryStructureIteratorTraits > SecondaryStructureIterator
typedef
ConstBidirectionalIterator
< Composite,
SecondaryStructure,
Composite::CompositeIterator,
SecondaryStructureIteratorTraits > SecondaryStructureConstIterator
typedef std::reverse_iterator
< SecondaryStructureIterator > SecondaryStructureReverseIterator
typedef std::reverse_iterator
< SecondaryStructureConstIterator > SecondaryStructureConstReverseIterator
typedef TAngle< float > Angle
typedef TBox3< float > Box3
typedef TCircle3< float > Circle3
typedef std::complex
< BALL_COMPLEX_PRECISION > Complex
typedef TFFT1D
< BALL_FFTW_DEFAULT_TRAITS > FFT1D
typedef TFFT2D
< BALL_FFTW_DEFAULT_TRAITS > FFT2D
typedef TFFT3D
< BALL_FFTW_DEFAULT_TRAITS > FFT3D
typedef TLine3< float > Line3
typedef TMatrix4x4< float > Matrix4x4
typedef std::vector< double > Coefficients
typedef std::pair< double, double > Interval
typedef TPlane3< float > Plane3
typedef TQuaternion< float > Quaternion
typedef TSphere3< float > Sphere3
typedef TSurface< float > Surface
typedef TVector2< float > Vector2
typedef TVector3< float > Vector3
typedef TVector4< float > Vector4
typedef List< RegularData3D * > RegularData3DList
typedef TMolecularGraph< Index,
Index > MolecularGraph
typedef TMutex
< BALL_DEFAULT_MUTEX_TYPE > Mutex
typedef TReadWriteLock
< BALL_DEFAULT_READWRITELOCK_TYPE > ReadWriteLock
typedef TMutexLocker
< BALL_DEFAULT_MUTEXLOCKER_TYPE,
BALL_DEFAULT_MUTEX_TYPE > MutexLocker
typedef TReadLocker
< BALL_DEFAULT_READLOCKER_TYPE,
BALL_DEFAULT_READWRITELOCK_TYPE > ReadLocker
typedef TWriteLocker
< BALL_DEFAULT_WRITELOCKER_TYPE,
BALL_DEFAULT_READWRITELOCK_TYPE > WriteLocker
Type aliases defined by BALL.
These predefined types are used in BALL for portability and comprehensibility.
typedef BALL_INDEX_TYPE Distance
typedef BALL_SIZE_TYPE Handle
typedef BALL_INDEX_TYPE Index
typedef BALL_SIZE_TYPE Size
typedef BALL_LONG64_TYPE LongIndex
typedef BALL_ULONG64_TYPE LongSize
typedef time_t Time
typedef BALL_SIZE_TYPE HashIndex
typedef BALL_SIZE_TYPE Position
typedef float Real
typedef double DoubleReal
typedef BALL_SIZE_TYPE Property
typedef BALL_INDEX_TYPE ErrorCode
typedef unsigned char Byte
typedef BALL_POINTERSIZEUINT_TYPE PointerSizeUInt
Iterator type definitions for the various AtomContainerIterators.
typedef BidirectionalIterator
< Composite, AtomContainer,
Composite::CompositeIterator,
AtomContainerIteratorTraits > AtomContainerIterator
typedef
ConstBidirectionalIterator
< Composite, AtomContainer,
Composite::CompositeIterator,
AtomContainerIteratorTraits > AtomContainerConstIterator
typedef std::reverse_iterator
< AtomContainerIterator > AtomContainerReverseIterator
A mutable reverse bidirectional iterator for the AtomContainer class.
typedef std::reverse_iterator
< AtomContainerConstIterator > AtomContainerConstReverseIterator
A constant reverse bidirectional iterator for the AtomContainer class.
Iterator type definitions for the various AtomIterators
typedef BidirectionalIterator
< Composite, Atom,
Composite::CompositeIterator,
AtomIteratorTraits > AtomIterator
typedef
ConstBidirectionalIterator
< Composite, Atom,
Composite::CompositeIterator,
AtomIteratorTraits > AtomConstIterator
typedef std::reverse_iterator
< AtomIterator > AtomReverseIterator
A mutable reverse bidirectional iterator for the Atom class.
typedef std::reverse_iterator
< AtomConstIterator > AtomConstReverseIterator
A constant reverse bidirectional iterator for the Atom class.
Typedefs for the various BondIterators
typedef Atom::BondIterator AtomBondIterator
typedef Atom::BondConstIterator AtomBondConstIterator
typedef Atom::BondReverseIterator AtomBondReverseIterator
typedef
Atom::BondConstReverseIterator AtomBondConstReverseIterator
Iterator type definitions for the various ChainIterators
typedef BidirectionalIterator
< Composite, Chain,
Composite::CompositeIterator,
ChainIteratorTraits > ChainIterator
A mutable bidirectional iterator for the Chain class.
typedef
ConstBidirectionalIterator
< Composite, Chain,
Composite::CompositeIterator,
ChainIteratorTraits > ChainConstIterator
A constant bidirectional iterator for the Chain class.
typedef std::reverse_iterator
< ChainIterator > ChainReverseIterator
A mutable reverse bidirectional iterator for the Chain class.
typedef std::reverse_iterator
< ChainConstIterator > ChainConstReverseIterator
A constant reverse bidirectional iterator for the Chain class.
typedef std::list< Atom * > AtomList
typedef std::list< Bond * > BondList
typedef std::list
< AtomContainer * > AtomContainerList
typedef std::list< PDBAtom * > PDBAtomList
typedef std::list< Residue * > ResidueList
typedef std::list< Fragment * > FragmentList
typedef std::list< Molecule * > MoleculeList
typedef std::list< Protein * > ProteinList
typedef std::list
< SecondaryStructure * > SecondaryStructureList
typedef std::list< Chain * > ChainList
typedef std::list< Nucleotide * > NucleotideList
typedef std::list< NucleicAcid * > NucleicAcidList
Iterator type definitions for the various PDBAtomIterators
typedef BidirectionalIterator
< Composite, PDBAtom,
Composite::CompositeIterator,
PDBAtomIteratorTraits > PDBAtomIterator
A mutable bidirectional iterator for the PDBAtom class.
typedef
ConstBidirectionalIterator
< Composite, PDBAtom,
Composite::CompositeIterator,
PDBAtomIteratorTraits > PDBAtomConstIterator
A constant bidirectional iterator for the PDBAtom class.
typedef std::reverse_iterator
< PDBAtomIterator > PDBAtomReverseIterator
A mutable reverse bidirectional iterator for the PDBAtom class.
typedef std::reverse_iterator
< PDBAtomConstIterator > PDBAtomConstReverseIterator
A constant reverse bidirectional iterator for the PDBAtom class.
KernelPredicates Kernel predicates
This chapter describes a set of unary predicates acting on Composite instances, that can be used to identify the class type of a composite at runtime.
This predicates are functionally similar to the RTTI:isKindOf function. They decide whether a given composite is an instance of a certain class (or of a class derived thereof). For instance, the application of a MoleculePredicate to a composite will yield true, if the given composite was an instance of Molecule (or Protein , as Protein is derived from Molecule). Otherwise false is returned.
Each KernelPredicate possesses three methods:
-operator (const Composite&) -operator (const Composite&) const
The two operators are functionally identical (two methods are needed, because the class is derived from TUnaryPredicate and we want to make sure both methods are overwritten). operator() returns true, if the given composite is a kind of the class corresponding to the respective predicate, false otherwise.
See also:
UnaryPredicate
RTTI
typedef UnaryPredicate< Composite > KernelPredicateType
Convenience typedefs
typedef Experiment< PeakList1D > Experiment1D
typedef Experiment< PeakList3D > Experiment3D
Convenience typedefs
typedef Peak< float > Peak1D
typedef Peak< Vector2 > Peak2D
typedef Peak< Vector3 > Peak3D
Standard typedefs
typedef PeakList< Peak< float > > PeakList1D
1D peak list
typedef PeakList< Peak< Vector2 > > PeakList2D
2D peak list
typedef PeakList< Peak< Vector3 > > PeakList3D
3D peak list
typedef Spectrum
< RegularData1D, Peak1D > Spectrum1D
One-dimensional spectrum.
typedef Spectrum
< RegularData1D, Peak2D > Spectrum2D
Two-dimensional spectrum.
typedef Spectrum
< RegularData1D, Peak3D > Spectrum3D
Three-dimensional spectrum.
Enumerations
enum ASCII {
ASCII__BACKSPACE = '\b', ASCII__BELL = '\a', ASCII__CARRIAGE_RETURN = '\r', ASCII__HORIZONTAL_TAB = '\t',
ASCII__NEWLINE = '\n', ASCII__RETURN = ASCII__NEWLINE, ASCII__SPACE = ' ', ASCII__TAB = ASCII__HORIZONTAL_TAB,
ASCII__VERTICAL_TAB = '\v', ASCII__COLON = ':', ASCII__COMMA = ',', ASCII__EXCLAMATION_MARK = '!',
ASCII__POINT = '.', ASCII__QUESTION_MARK = '?', ASCII__SEMICOLON = ';'
}
Functions
BALL_EXPORT std::ostream & operator<< (std::ostream &os, const Exception::GeneralException &e)
BALL_EXPORT string streamClassName (const std::type_info &t)
template<typename Container , typename DataType , typename Position , typename Traits >
ConstRandomAccessIterator
< Container, DataType,
Position, Traits > operator+ (Distance distance, const ConstRandomAccessIterator< Container, DataType, Position, Traits > &iterator) throw (Exception::InvalidIterator)
template<>
BALL_EXPORT HashIndex Hash (const std::pair< Position, Position > &p)
BALL_EXPORT const FacetArray & getContourSurfaceFacetData (double threshold)
BALL_EXPORT double calculateACE (const AtomContainer &atom_container, const string &type_filename="energy/ACE_types.dat", const string &parameter_filename="energy/ACE_parameters.dat")
BALL_EXPORT double calculateCoulomb (const AtomContainer &atoms)
BALL_EXPORT double calculateDistanceCoulomb (const AtomContainer &fragment)
BALL_EXPORT HashIndex Hash (const PDBFile::ResidueQuadruple &quadruple)
BALL_EXPORT std::ostream & operator<< (std::ostream &s, const Quadruple< String, PDB::Character, PDB::Integer, PDB::AChar > &)
template<class AtomContainerType >
void cloneBonds (const AtomContainerType &atom_container, AtomContainerType &cloned)
template<class NucleotideContainerType >
const Nucleotide * get5Prime (const NucleotideContainerType &nucleotide_container)
template<class NucleotideContainerType >
const Nucleotide * get3Prime (const NucleotideContainerType &nucleotide_container)
BALL_EXPORT std::ostream & operator<< (std::ostream &s, const Element &element)
template<class ResidueContainerType >
const Residue * getNTerminal (const ResidueContainerType &residue_container)
template<class ResidueContainerType >
const Residue * getCTerminal (const ResidueContainerType &residue_container)
template<typename T >
BALL_INLINE T getDeterminant_ (const T *m, Size dim)
template<typename T >
T getDeterminant (const T *m, Size dim)
template<typename T >
BALL_INLINE T getDeterminant2 (const T *m)
template<typename T >
BALL_INLINE T getDeterminant2 (const T &m00, const T &m01, const T &m10, const T &m11)
template<typename T >
BALL_INLINE T getDeterminant3 (const T *m)
template<typename T >
BALL_INLINE T getDeterminant3 (const T &m00, const T &m01, const T &m02, const T &m10, const T &m11, const T &m12, const T &m20, const T &m21, const T &m22)
template<typename T >
bool SolveSystem (const T *m, T *x, const Size dim)
template<typename T >
BALL_INLINE bool SolveSystem2 (const T &a1, const T &b1, const T &c1, const T &a2, const T &b2, const T &c2, T &x1, T &x2)
template<typename T >
short SolveQuadraticEquation (const T &a, const T &b, const T &c, T &x1, T &x2)
template<typename T >
BALL_INLINE TVector3< T > GetPartition (const TVector3< T > &a, const TVector3< T > &b)
template<typename T >
BALL_INLINE TVector3< T > GetPartition (const TVector3< T > &a, const TVector3< T > &b, const T &r, const T &s) throw (Exception::DivisionByZero)
template<typename T >
BALL_INLINE T GetDistance (const TVector3< T > &a, const TVector3< T > &b)
template<typename T >
BALL_INLINE T GetDistance (const TLine3< T > &line, const TVector3< T > &point) throw (Exception::DivisionByZero)
template<typename T >
BALL_INLINE T GetDistance (const TVector3< T > &point, const TLine3< T > &line) throw (Exception::DivisionByZero)
template<typename T >
T GetDistance (const TLine3< T > &a, const TLine3< T > &b) throw (Exception::DivisionByZero)
template<typename T >
BALL_INLINE T GetDistance (const TVector3< T > &point, const TPlane3< T > &plane) throw (Exception::DivisionByZero)
template<typename T >
BALL_INLINE T GetDistance (const TPlane3< T > &plane, const TVector3< T > &point) throw (Exception::DivisionByZero)
template<typename T >
BALL_INLINE T GetDistance (const TLine3< T > &line, const TPlane3< T > &plane) throw (Exception::DivisionByZero)
template<typename T >
BALL_INLINE T GetDistance (const TPlane3< T > &plane, const TLine3< T > &line) throw (Exception::DivisionByZero)
template<typename T >
BALL_INLINE T GetDistance (const TPlane3< T > &a, const TPlane3< T > &b) throw (Exception::DivisionByZero)
template<typename T >
BALL_INLINE bool GetAngle (const TVector3< T > &a, const TVector3< T > &b, TAngle< T > &intersection_angle)
template<typename T >
BALL_INLINE bool GetAngle (const TLine3< T > &a, const TLine3< T > &b, TAngle< T > &intersection_angle)
template<typename T >
BALL_INLINE bool GetAngle (const TPlane3< T > &plane, const TVector3< T > &vector, TAngle< T > &intersection_angle)
template<typename T >
BALL_INLINE bool GetAngle (const TVector3< T > &vector, const TPlane3< T > &plane, TAngle< T > &intersection_angle)
template<typename T >
BALL_INLINE bool GetAngle (const TPlane3< T > &plane, const TLine3< T > &line, TAngle< T > &intersection_angle)
template<typename T >
BALL_INLINE bool GetAngle (const TLine3< T > &line, const TPlane3< T > &plane, TAngle< T > &intersection_angle)
template<typename T >
BALL_INLINE bool GetAngle (const TPlane3< T > &a, const TPlane3< T > &b, TAngle< T > &intersection_angle)
template<typename T >
bool GetIntersection (const TLine3< T > &a, const TLine3< T > &b, TVector3< T > &point)
template<typename T >
BALL_INLINE bool GetIntersection (const TPlane3< T > &plane, const TLine3< T > &line, TVector3< T > &intersection_point)
template<typename T >
BALL_INLINE bool GetIntersection (const TLine3< T > &line, const TPlane3< T > &plane, TVector3< T > &intersection_point)
template<typename T >
bool GetIntersection (const TPlane3< T > &plane1, const TPlane3< T > &plane2, TLine3< T > &line)
template<typename T >
bool GetIntersection (const TSphere3< T > &sphere, const TLine3< T > &line, TVector3< T > &intersection_point1, TVector3< T > &intersection_point2)
template<typename T >
BALL_INLINE bool GetIntersection (const TLine3< T > &line, const TSphere3< T > &sphere, TVector3< T > &intersection_point1, TVector3< T > &intersection_point2)
template<typename T >
bool GetIntersection (const TSphere3< T > &sphere, const TPlane3< T > &plane, TCircle3< T > &intersection_circle)
template<typename T >
BALL_INLINE bool GetIntersection (const TPlane3< T > &plane, const TSphere3< T > &sphere, TCircle3< T > &intersection_circle)
template<typename T >
bool GetIntersection (const TSphere3< T > &a, const TSphere3< T > &b, TCircle3< T > &intersection_circle)
template<class T >
bool GetIntersection (const TSphere3< T > &s1, const TSphere3< T > &s2, const TSphere3< T > &s3, TVector3< T > &p1, TVector3< T > &p2, bool test=true)
template<typename T >
BALL_INLINE bool isCollinear (const TVector3< T > &a, const TVector3< T > &b)
template<typename T >
BALL_INLINE bool isComplanar (const TVector3< T > &a, const TVector3< T > &b, const TVector3< T > &c)
template<typename T >
BALL_INLINE bool isComplanar (const TVector3< T > &a, const TVector3< T > &b, const TVector3< T > &c, const TVector3< T > &d)
template<typename T >
BALL_INLINE bool isOrthogonal (const TVector3< T > &a, const TVector3< T > &b)
template<typename T >
BALL_INLINE bool isOrthogonal (const TVector3< T > &vector, const TLine3< T > &line)
template<typename T >
BALL_INLINE bool isOrthogonal (const TLine3< T > &line, const TVector3< T > &vector)
template<typename T >
BALL_INLINE bool isOrthogonal (const TLine3< T > &a, const TLine3< T > &b)
template<typename T >
BALL_INLINE bool isOrthogonal (const TVector3< T > &vector, const TPlane3< T > &plane)
template<typename T >
BALL_INLINE bool isOrthogonal (const TPlane3< T > &plane, const TVector3< T > &vector)
template<typename T >
BALL_INLINE bool isOrthogonal (const TPlane3< T > &a, const TPlane3< T > &b)
template<typename T >
BALL_INLINE bool isIntersecting (const TVector3< T > &point, const TLine3< T > &line)
template<typename T >
BALL_INLINE bool isIntersecting (const TLine3< T > &line, const TVector3< T > &point)
template<typename T >
BALL_INLINE bool isIntersecting (const TLine3< T > &a, const TLine3< T > &b)
template<typename T >
BALL_INLINE bool isIntersecting (const TVector3< T > &point, const TPlane3< T > &plane)
template<typename T >
BALL_INLINE bool isIntersecting (const TPlane3< T > &plane, const TVector3< T > &point)
template<typename T >
BALL_INLINE bool isIntersecting (const TLine3< T > &line, const TPlane3< T > &plane)
template<typename T >
BALL_INLINE bool isIntersecting (const TPlane3< T > &plane, const TLine3< T > &line)
template<typename T >
BALL_INLINE bool isIntersecting (const TPlane3< T > &a, const TPlane3< T > &b)
template<typename T >
BALL_INLINE bool isParallel (const TLine3< T > &line, const TPlane3< T > &plane)
template<typename T >
BALL_INLINE bool isParallel (const TPlane3< T > &plane, const TLine3< T > &line)
template<typename T >
BALL_INLINE bool isParallel (const TPlane3< T > &a, const TPlane3< T > &b)
template<typename T >
TAngle< T > getOrientedAngle (const T &ax, const T &ay, const T &az, const T &bx, const T &by, const T &bz, const T &nx, const T &ny, const T &nz) throw (Exception::DivisionByZero)
template<typename T >
BALL_INLINE TAngle< T > getOrientedAngle (const TVector3< T > &a, const TVector3< T > &b, const TVector3< T > &normal) throw (Exception::DivisionByZero)
template<typename T >
TAngle< T > getTorsionAngle (const T &ax, const T &ay, const T &az, const T &bx, const T &by, const T &bz, const T &cx, const T &cy, const T &cz, const T &dx, const T &dy, const T &dz) throw (Exception::DivisionByZero)
template<typename T >
BALL_INLINE TAngle< T > operator* (const T &val, const TAngle< T > &angle)
template<typename T >
BALL_INLINE TAngle< T > operator+ (const T &val, const TAngle< T > &angle)
template<typename T >
BALL_INLINE TAngle< T > operator- (const T &val, const TAngle< T > &angle)
template<typename T >
std::istream & operator>> (std::istream &s, TAngle< T > &angle)
template<typename T >
std::ostream & operator<< (std::ostream &s, const TAngle< T > &angle)
template<typename ComplexTraits >
const RegularData1D & operator<< (RegularData1D &to, const TFFT1D< ComplexTraits > &from)
template<typename ComplexTraits >
const TRegularData2D< typename
TFFT2D< ComplexTraits >
::Complex > & operator<< (TRegularData2D< typename TFFT2D< ComplexTraits >::Complex > &to, const TFFT2D< ComplexTraits > &from)
template<typename ComplexTraits >
const RegularData2D & operator<< (RegularData2D &to, const TFFT2D< ComplexTraits > &from)
template<typename ComplexTraits >
const TRegularData3D< typename
TFFT3D< ComplexTraits >
::Complex > & operator<< (TRegularData3D< typename TFFT3D< ComplexTraits >::Complex > &to, const TFFT3D< ComplexTraits > &from)
template<typename ComplexTraits >
const RegularData3D & operator<< (RegularData3D &to, const TFFT3D< ComplexTraits > &from)
template<typename T >
TMatrix4x4< T > operator* (const T &scalar, const TMatrix4x4< T > &m)
template<typename T >
TVector3< T > operator* (const TMatrix4x4< T > &matrix, const TVector3< T > &vector)
template<typename T >
std::istream & operator>> (std::istream &s, TQuaternion< T > &q)
template<typename T >
std::ostream & operator<< (std::ostream &s, const TQuaternion< T > &q)
template<typename T >
BALL_INLINE TVector4< T > operator* (const T &scalar, const TVector4< T > &v)
template<typename T >
BALL_INLINE TVector4< T > operator* (const TVector4< T > &v, const T &scalar)
::std::ostream & operator<< (::std::ostream &os, const SnapShot &ss)
Output stream operator for SnapShots.
::std::istream & operator>> (::std::istream &is, SnapShot &ss)
Input stream operator for SnapShots.
Position getMMFF94Index (Position atom_type1, Position atom_type2)
BALL_EXPORT const RegularData1D & operator<< (RegularData1D &data, const PeakList1D &peak_list)
template<typename PositionType >
std::ostream & operator<< (std::ostream &os, const Peak< PositionType > &peak)
template<typename DataT , typename PeakT , typename PositionT >
double operator- (const Spectrum< DataT, PeakT, PositionT > &s1, const Spectrum< DataT, PeakT, PositionT > &s2)
PyObject * pyMapBALLObjectToSip (Composite &object)
BALL_EXPORT TRegularData3D
< char > * calculateSESGrid (const Vector3 &lower, const Vector3 &upper, float spacing, const System &system, float probe_radius)
BALL_EXPORT TRegularData3D
< char > * calculateSASGrid (const Vector3 &lower, const Vector3 &upper, float spacing, const System &system, float probe_radius)
BALL_EXPORT double calculateOoiEnergy (AtomContainer &atoms)
BALL_EXPORT float calculateSESAtomAreas (const AtomContainer &fragment, HashMap< const Atom *, float > &atom_areas, float probe_radius=1.5)
BALL_EXPORT float calculateSESArea (const AtomContainer &fragment, float probe_radius=1.5)
BALL_EXPORT float calculateSESVolume (const AtomContainer &fragment, float probe_radius=1.5)
std::ostream & operator<< (std::ostream &out, const DockResult &dock_res)
std::istream & operator>> (std::istream &in, DockResult &dock_res)
template<typename Node , typename Edge >
std::ostream & operator<< (std::ostream &os, const TMolecularGraph< Node, Edge > &G)
template<typename T >
std::ostream & operator<< (std::ostream &os, const BinaryFileAdaptor< T > &data)
Output stream for BinaryFileAdaptors.
template<typename T >
std::istream & operator>> (std::istream &is, BinaryFileAdaptor< T > &data)
Input stream for BinaryFileAdaptors.
template<typename T >
BALL_INLINE void swapBytes (T &t)
BALL_EXPORT void sleepFor (Size mseconds)
Specialized Hash Functions.
BALL_EXPORT HashIndex hashPointer (void *const ptr)
BALL_EXPORT HashIndex hashString (const char *str)
BALL_EXPORT HashIndex hashPJWString (const char *str)
BALL_EXPORT HashIndex hashElfString (const char *str)
template<typename T >
HashIndex Hash (const T &key)
BALL_EXPORT HashIndex Hash (const string &s)
BALL_EXPORT HashIndex Hash (const String &s)
BALL_EXPORT HashIndex Hash (void *const &ptr)
BALL_EXPORT HashIndex getNextPrime (HashIndex l)
Notification Management.
Using the notification management, objects may exchange data and notify each other of events by invoking methods of the other object (remotely similar to the signal/slot mechanism of QT).
NotificationManager_ & NotificationManager ()
void NotificationManagerEnable ()
void NotificationManagerDisable ()
bool NotificationManagerIsEnabled ()
bool NotificationManagerIsDisabled ()
template<class NotificationSource >
void NotificationSourceEnable (NotificationSource &notification_source)
template<class NotificationSource >
void NotificationSourceDisable (NotificationSource &notification_source)
template<class NotificationSource >
bool NotificationSourceIsEnabled (NotificationSource &notification_source)
template<class NotificationSource >
bool NotificationSourceIsDisabled (NotificationSource &notification_source)
template<class Source , class Target >
void NotificationRegister (const Source &source, const Target &target)
template<class Source , class Target , class T1 >
void NotificationRegister1 (const Source &source, const Target &target, const T1 &)
template<class NotificationSource , class NotificationTarget , class T1 , class T2 >
void NotificationRegister2 (const NotificationSource &notification_source, const NotificationTarget &notification_target, const T1 &, const T2 &)
void NotificationUnregisterAll ()
template<class NotificationSource >
void NotificationUnregister (const NotificationSource &notification_source)
template<class Source , class Target >
void NotificationUnregister (const Source &source, const Target &target)
template<class NotificationSource , class NotificationTarget , class T1 >
void NotificationUnregister1 (const NotificationSource &notification_source, const NotificationTarget &notification_target, const T1 &)
template<class NotificationSource , class NotificationTarget , class T1 , class T2 >
void NotificationUnregister2 (const NotificationSource &notification_source, const NotificationTarget &notification_target, const T1 &, const T2 &)
template<class NotificationSource >
bool NotificationIsRegistered (const NotificationSource &notification_source)
template<class Source , class Target >
bool NotificationIsRegistered (const Source &source, const Target &target)
template<class NotificationSource >
bool Notify (NotificationSource &notification_source)
template<class NotificationSource , class T1 >
bool Notify (NotificationSource &notification_source, const T1 &data1)
template<class NotificationSource , class T1 , class T2 >
bool Notify (NotificationSource &notification_source, const T1 &data1, const T2 &data2)
BALL_EXPORT std::ostream & operator<< (std::ostream &os, const PreciseTime &time)
BALL_EXPORT std::ostream & operator<< (std::ostream &os, const TimeStamp &stamp)
Stream I/O
template<typename ValueType >
std::ostream & operator<< (std::ostream &os, const TRegularData1D< ValueType > &data)
Output operator.
template<typename ValueType >
std::istream & operator>> (std::istream &is, TRegularData1D< ValueType > &grid)
Input operator.
Stream I/O
template<typename ValueType >
std::ostream & operator<< (std::ostream &os, const TRegularData2D< ValueType > &data)
Output operator.
template<typename ValueType >
std::istream & operator>> (std::istream &is, TRegularData2D< ValueType > &grid)
Input operator.
Stream I/O
template<typename ValueType >
std::ostream & operator<< (std::ostream &os, const TRegularData3D< ValueType > &grid)
Output operator.
template<typename ValueType >
std::istream & operator>> (std::istream &is, TRegularData3D< ValueType > &grid)
Input operator.
std::ostream & operator<< (std::ostream &s, const NMRAtomData &ad)
std::ostream & operator<< (std::ostream &s, const SampleCondition &sc)
std::ostream & operator<< (std::ostream &s, const ShiftReferenceElement &sre)
std::ostream & operator<< (std::ostream &s, const ShiftReferenceSet &sr)
std::ostream & operator<< (std::ostream &s, const NMRAtomDataSet &set)
BALL_EXPORT AtomList atoms (const AtomContainer &fragment, const String &expression=String())
BALL_EXPORT AtomList atoms (const AtomList &atoms, const String &expression)
BALL_EXPORT PDBAtomList PDBAtoms (const AtomContainer &fragment, const String &expression=String())
BALL_EXPORT BondList bonds (const AtomContainer &fragment, bool selected_only=false)
BALL_EXPORT BondList bonds (const Atom &atom)
BALL_EXPORT AtomContainerList atomContainers (const AtomContainer &fragment, bool selected_only=false)
BALL_EXPORT ResidueList residues (const AtomContainer &fragment, bool selected_only=false)
BALL_EXPORT FragmentList fragments (const AtomContainer &fragment, bool selected_only=false)
BALL_EXPORT MoleculeList molecules (const AtomContainer &fragment, bool selected_only=false)
BALL_EXPORT ProteinList proteins (const AtomContainer &fragment, bool selected_only=false)
BALL_EXPORT SecondaryStructureList secondaryStructures (const AtomContainer &fragment, bool selected_only=false)
BALL_EXPORT ChainList chains (const AtomContainer &fragment, bool selected_only=false)
BALL_EXPORT NucleicAcidList nucleicAcids (const AtomContainer &fragment, bool selected_only=false)
BALL_EXPORT NucleotideList nucleotides (const AtomContainer &fragment, bool selected_only=false)
Storers
template<typename T >
std::istream & operator>> (std::istream &s, TBox3< T > &box)
template<typename T >
std::ostream & operator<< (std::ostream &s, const TBox3< T > &box)
Storers
template<typename T >
std::istream & operator>> (std::istream &s, TCircle3< T > &circle)
template<typename T >
std::ostream & operator<< (std::ostream &s, const TCircle3< T > &circle)
Storers
Stream operators of Line3
template<typename T >
std::ostream & operator<< (std::ostream &s, const TLine3< T > &line)
template<typename T >
std::istream & operator>> (std::istream &s, TLine3< T > &line)
Storers
template<typename T >
std::istream & operator>> (std::istream &s, TMatrix4x4< T > &m)
template<typename T >
std::ostream & operator<< (std::ostream &s, const TMatrix4x4< T > &m)
Storers
Stream operators for class TPlane3
template<typename T >
std::istream & operator>> (std::istream &s, TPlane3< T > &plane)
template<typename T >
std::ostream & operator<< (std::ostream &s, const TPlane3< T > &plane)
Storers
Stream operators for the class Sphere
template<typename T >
std::istream & operator>> (std::istream &s, TSphere3< T > &sphere)
template<typename T >
std::ostream & operator<< (std::ostream &s, const TSphere3< T > &sphere)
Global binary operator functions for two dimensional vectors.
template<typename T >
BALL_INLINE TVector2< T > operator* (const T &scalar, const TVector2< T > &vector)
template<typename T >
std::istream & operator>> (std::istream &s, TVector2< T > &vector)
template<typename T >
std::ostream & operator<< (std::ostream &s, const TVector2< T > &vector)
Global binary operators for three-dimensional vectors.
template<typename T >
BALL_INLINE TVector3< T > operator* (const T &a, const TVector3< T > &b)
template<typename T >
std::istream & operator>> (std::istream &s, TVector3< T > &vector)
template<typename T >
std::ostream & operator<< (std::ostream &s, const TVector3< T > &vector)
Global binary operators for three-dimensional vectors.
template<typename T >
BALL_INLINE TVector4< T > operator+ (const TVector4< T > &a, const TVector4< T > &b)
template<typename T >
BALL_INLINE TVector4< T > operator- (const TVector4< T > &a, const TVector4< T > &b)
template<typename T >
std::istream & operator>> (std::istream &s, TVector4< T > &vector)
template<typename T >
std::ostream & operator<< (std::ostream &s, const TVector4< T > &vector)
Angle Calculation
BALL_EXPORT Angle calculateTorsionAngle (const Atom &a1, const Atom &a2, const Atom &a3, const Atom &a4) throw (Exception::IllegalPosition)
BALL_EXPORT Angle calculateBondAngle (const Atom &a1, const Atom &a2, const Atom &a3) throw (Exception::IllegalPosition)
Fast Numerical Calculation of Solvent Accessible Surface Area.
These functions are loosely based on the algorithm by Eisenhaber, Lijnzaad, Argos, Sander, and Scharf ("The Double Cubic Lattice Method: Efficient Approaches to numerical Integration of Surface Area and Volume and to Dot Surface Contouring of Molecular Assemblies", J. Comput. Chem. (1995), 15 , 273-284) and Eisenhaber and Argos ("Improved Strategy in Analytic Surface Calculation for Molecular Systems: Handling of Singularities and Computational Efficiency" J. Comput. Chem. (1993), 14 , 1272-1280).
BALL_EXPORT BALL_DEPRECATED float calculateSASArea (const AtomContainer &fragment, float probe_radius=1.5, Size number_of_dots=400)
BALL_EXPORT BALL_DEPRECATED float calculateSASVolume (const AtomContainer &fragment, float probe_radius=1.5, Size number_of_dots=400)
BALL_EXPORT BALL_DEPRECATED float calculateSASAtomAreas (const AtomContainer &fragment, HashMap< const Atom *, float > &atom_areas, float probe_radius=1.5, Size number_of_dots=400)
BALL_EXPORT BALL_DEPRECATED float calculateSASPoints (const AtomContainer &fragment, Surface &surface_points, float probe_radius=1.5, Size number_of_dots=400)
BALL_EXPORT BALL_DEPRECATED float calculateSASAtomPoints (const AtomContainer &fragment, std::vector< std::pair< Vector3, Surface > > &atom_surfaces, float probe_radius=1.5, Size number_of_dots=400)
Storers
BALL_EXPORT std::ostream & operator<< (std::ostream &s, const ReducedSurface &rs)
Storers
BALL_EXPORT std::ostream & operator<< (std::ostream &s, const RSEdge &rsedge)
Storers
BALL_EXPORT std::ostream & operator<< (std::ostream &s, const RSFace &rsface)
Storers
BALL_EXPORT std::ostream & operator<< (std::ostream &s, const RSVertex &rsvertex)
Storers
BALL_EXPORT std::ostream & operator<< (std::ostream &s, const SASEdge &sasedge)
Storers
BALL_EXPORT std::ostream & operator<< (std::ostream &s, const SASFace &sasface)
Storers
BALL_EXPORT std::ostream & operator<< (std::ostream &s, const SASVertex &sasvertex)
Storers
BALL_EXPORT std::ostream & operator<< (std::ostream &s, const SESEdge &sesedge)
Storers
BALL_EXPORT std::ostream & operator<< (std::ostream &s, const SESFace &sesface)
Storers
BALL_EXPORT std::ostream & operator<< (std::ostream &s, const SESVertex &sesvertex)
Storers
BALL_EXPORT std::ostream & operator<< (std::ostream &s, const SolventAccessibleSurface &sas)
Storers
BALL_EXPORT std::ostream & operator<< (std::ostream &s, const SolventExcludedSurface &ses)
Storers
BALL_EXPORT std::ostream & operator<< (std::ostream &s, const Triangle &triangle)
Storers
BALL_EXPORT std::ostream & operator<< (std::ostream &s, const TriangleEdge &edge)
Storers
BALL_EXPORT std::ostream & operator<< (std::ostream &s, const TrianglePoint &point)
Storers
BALL_EXPORT std::ostream & operator<< (std::ostream &s, const TriangulatedSurface &surface)
Variables
static const Distance INVALID_DISTANCE = INT_MIN
static const Distance DISTANCE_MIN = (INT_MIN + 1)
static const Distance DISTANCE_MAX = INT_MAX
static const Handle INVALID_HANDLE = INT_MAX
static const Handle HANDLE_MIN = 0
static const Handle HANDLE_MAX = INT_MAX - 1
static const Index INVALID_INDEX = -1
static const Index INDEX_MIN = 0
static const Index INDEX_MAX = INT_MAX
static const Position INVALID_POSITION = INT_MAX
static const Position POSITION_MIN = 0
static const Position POSITION_MAX = INT_MAX - 1
static const Size INVALID_SIZE = INT_MAX
static const Size SIZE_MIN = 0
static const Size SIZE_MAX = INT_MAX - 1
bool clone_bonds
BALL_EXPORT PTE_ PTE
StringHashMap< double * > * ParsedFunctionConstants
StringHashMap< double(*)(double)> * ParsedFunctionFunctions
static const double INFINITY = Limits<double>::max()
Size MMFF94_number_atom_types
hold the maximum number of MMFF94 atom types + 1 (wildcard)
BALL_EXPORT const char CCONN__INSIDE
BALL_EXPORT const char CCONN__OUTSIDE
BALL_EXPORT const char CCONN__INSIDE_PROBE
Log streams
Logging, filtering, and storing messages. Many programs emit warning messages, error messages, or simply informations and remarks to their users. The LogStream class provides a convenient and straight-forward interface to classify these messages according to their importance (via the loglevel), filter and store them in files or write them to streams.
As the LogStream class is derived from ostream, it behaves as any ostream object. Additionally you may associate streams with each LogStream object that catch only messages of certain loglevels. So the user might decide to redirect all error messages to cerr, all warning messages to cout and all informations to a file.
Along with each message its time of creation and its loglevel is stored. So the user might also decide to store all errors he got in the last two hours or alike.
The LogStream class heavily relies on the LogStreamBuf class, which does the actual buffering and storing, but is only of interest if you want to implement a derived class, as the actual user interface is implemented in the LogStream class.
BALL_EXPORT LogStream Log
Storers
typedef TSimpleBox3< float > SimpleBox3
template<typename T >
std::istream & operator>> (std::istream &s, TSimpleBox3< T > &box)
template<typename T >
std::ostream & operator<< (std::ostream &s, const TSimpleBox3< T > &box)
Typedef Documentation
typedef TAngle<float> BALL::Angle
The Default Angle Type. If double precision is not needed, TAngle<float> should be used. It is predefined as Angle for convenience.
typedef Atom::BondConstIterator BALL::AtomBondConstIterator
A constant iterator for atom bonds.
typedef Atom::BondConstReverseIterator BALL::AtomBondConstReverseIterator
A constant reverse iterator for atom bonds.
typedef Atom::BondIterator BALL::AtomBondIterator
A mutable iterator for atom bonds.
typedef Atom::BondReverseIterator BALL::AtomBondReverseIterator
A mutable reverse iterator for atom bonds.
typedef ConstBidirectionalIterator<Composite, Atom, Composite::CompositeIterator, AtomIteratorTraits> BALL::AtomConstIterator
A constant bidirectional iterator for the Atom class.
typedef std::reverse_iterator<AtomConstIterator> BALL::AtomConstReverseIterator
A constant reverse bidirectional iterator for the Atom class.
typedef ConstBidirectionalIterator<Composite, AtomContainer, Composite::CompositeIterator, AtomContainerIteratorTraits> BALL::AtomContainerConstIterator
A constant bidirectional iterator for the AtomContainer class.
typedef std::reverse_iterator<AtomContainerConstIterator> BALL::AtomContainerConstReverseIterator
A constant reverse bidirectional iterator for the AtomContainer class.
typedef BidirectionalIterator<Composite, AtomContainer, Composite::CompositeIterator, AtomContainerIteratorTraits> BALL::AtomContainerIterator
A mutable bidirectional iterator for the AtomContainer class.
typedef std::reverse_iterator<AtomContainerIterator> BALL::AtomContainerReverseIterator
A mutable reverse bidirectional iterator for the AtomContainer class.
typedef BidirectionalIterator<Composite, Atom, Composite::CompositeIterator, AtomIteratorTraits> BALL::AtomIterator
A mutable bidirectional iterator for the Atom class.
typedef std::reverse_iterator<AtomIterator> BALL::AtomReverseIterator
A mutable reverse bidirectional iterator for the Atom class.
typedef unsigned char BALL::Byte
Byte type. Use this type to represent byte data (8 bit length). A Byte is always unsigned.
Size: 8 bit
persistent
typedef ConstBidirectionalIterator<Composite, Chain, Composite::CompositeIterator, ChainIteratorTraits> BALL::ChainConstIterator
A constant bidirectional iterator for the Chain class.
typedef std::reverse_iterator<ChainConstIterator> BALL::ChainConstReverseIterator
A constant reverse bidirectional iterator for the Chain class.
typedef BidirectionalIterator<Composite, Chain, Composite::CompositeIterator, ChainIteratorTraits> BALL::ChainIterator
A mutable bidirectional iterator for the Chain class.
typedef std::reverse_iterator<ChainIterator> BALL::ChainReverseIterator
A mutable reverse bidirectional iterator for the Chain class.
typedef int(* BALL::ComparatorType)(const void *, const void *)
typedef std::complex<BALL_COMPLEX_PRECISION> BALL::Complex
typedef TContourLine<float> BALL::ContourLine
Default type
typedef TContourSurface<float> BALL::ContourSurface
Default type.
typedef BALL_INDEX_TYPE BALL::Distance
Distance type. Use this type to represent distances in indices. Signed.
Size: 32 bit
persistent
typedef double BALL::DoubleReal
Double-precision real type. Use this type to represent double precision floating point numbers.
Size: 64 bit
persistent
typedef BALL_INDEX_TYPE BALL::ErrorCode
Error code property type. Use this type to represent (signed) error codes.
Size: 32 bit
persistent
See also:
PropertyManager
typedef Experiment<PeakList1D> BALL::Experiment1D
1D NMR experiment
typedef Experiment<PeakList3D> BALL::Experiment3D
2D NMR experiment 3D NMR experiment
typedef Index BALL::FacetArray[256][12]
typedef TFFT1D<BALL_FFTW_DEFAULT_TRAITS> BALL::FFT1D
Default type
typedef TFFT2D<BALL_FFTW_DEFAULT_TRAITS> BALL::FFT2D
Default type
typedef TFFT3D<BALL_FFTW_DEFAULT_TRAITS> BALL::FFT3D
Default type
typedef ConstBidirectionalIterator<Composite, Fragment, Composite::CompositeIterator, FragmentIteratorTraits> BALL::FragmentConstIterator
typedef std::reverse_iterator<FragmentConstIterator> BALL::FragmentConstReverseIterator
typedef BidirectionalIterator<Composite, Fragment, Composite::CompositeIterator, FragmentIteratorTraits> BALL::FragmentIterator
typedef std::reverse_iterator<FragmentIterator> BALL::FragmentReverseIterator
typedef BALL_SIZE_TYPE BALL::Handle
Handle type. Use this type to represent handles. Handles are used for the non-ambiguous identification of objects (e.g. object derived from Object). Handles are unsigned.
Size: 32 bit
persistent
typedef BALL_SIZE_TYPE BALL::HashIndex
HashIndex type. Use this type to access the result of a hash functions. HashIndex is unsigned.
Size: 32 bit
persistent
typedef BALL_INDEX_TYPE BALL::Index
Index type. Use this type to represent indices (e.g. in strings or other sequences). Theses indices may be signed, contrary to the Size type.
Size: 32 bit
persistent
typedef std::pair<double,double> BALL::Interval
An interval is defined by its limits
typedef UnaryPredicate<Composite> BALL::KernelPredicateType
typedef BALL_LONG64_TYPE BALL::LongIndex
Long index type. Use this type to represent very long (64 bit) indices. Theses indices may be signed, contrary to the LongSize type.
Size: 64 bit
persistent
Long signed int type. This type holds unsigned 64 bit numbers and is used to store pointers in a portable fashion (for both 32-bit and 64-bit systems).
Size: 64 bit
persistent
typedef BALL_ULONG64_TYPE BALL::LongSize
Long size type. Use this type to represent sizes of containers, sequences or alike. Variables of type LongSize are unsigned.
Size: 64 bit
persistent
Long unsigned int type. This type holds unsigned 64 bit integer numbers and is used to store pointers in a portable fashion (for both 32-bit and 64-bit systems).
Size: 64 bit
persistent
typedef TMolecularGraph<Index, Index> BALL::MolecularGraph
Default molecular graph type. Each edge and node has a label of type Index .
typedef ConstBidirectionalIterator<Composite, Molecule, Composite::CompositeIterator, MoleculeIteratorTraits> BALL::MoleculeConstIterator
typedef std::reverse_iterator<MoleculeConstIterator> BALL::MoleculeConstReverseIterator
typedef BidirectionalIterator<Composite, Molecule, Composite::CompositeIterator, MoleculeIteratorTraits> BALL::MoleculeIterator
typedef std::reverse_iterator<MoleculeIterator> BALL::MoleculeReverseIterator
typedef TMutex<BALL_DEFAULT_MUTEX_TYPE> BALL::Mutex
typedef TMutexLocker<BALL_DEFAULT_MUTEXLOCKER_TYPE, BALL_DEFAULT_MUTEX_TYPE> BALL::MutexLocker
typedef ConstBidirectionalIterator<Composite, NucleicAcid, Composite::CompositeIterator, NucleicAcidIteratorTraits> BALL::NucleicAcidConstIterator
typedef std::reverse_iterator<NucleicAcidConstIterator> BALL::NucleicAcidConstReverseIterator
typedef BidirectionalIterator<Composite, NucleicAcid, Composite::CompositeIterator, NucleicAcidIteratorTraits> BALL::NucleicAcidIterator
typedef std::reverse_iterator<NucleicAcidIterator> BALL::NucleicAcidReverseIterator
typedef ConstBidirectionalIterator<Composite, Nucleotide, Composite::CompositeIterator, NucleotideIteratorTraits> BALL::NucleotideConstIterator
typedef std::reverse_iterator<NucleotideConstIterator> BALL::NucleotideConstReverseIterator
typedef BidirectionalIterator<Composite, Nucleotide, Composite::CompositeIterator, NucleotideIteratorTraits> BALL::NucleotideIterator
typedef std::reverse_iterator<NucleotideIterator> BALL::NucleotideReverseIterator
typedef ConstBidirectionalIterator<Composite, PDBAtom, Composite::CompositeIterator, PDBAtomIteratorTraits> BALL::PDBAtomConstIterator
A constant bidirectional iterator for the PDBAtom class.
typedef std::reverse_iterator<PDBAtomConstIterator> BALL::PDBAtomConstReverseIterator
A constant reverse bidirectional iterator for the PDBAtom class.
typedef BidirectionalIterator<Composite, PDBAtom, Composite::CompositeIterator, PDBAtomIteratorTraits> BALL::PDBAtomIterator
A mutable bidirectional iterator for the PDBAtom class.
typedef std::reverse_iterator<PDBAtomIterator> BALL::PDBAtomReverseIterator
A mutable reverse bidirectional iterator for the PDBAtom class.
typedef Peak<float> BALL::Peak1D
typedef Peak<Vector2> BALL::Peak2D
typedef Peak<Vector3> BALL::Peak3D
typedef PeakList<Peak<float> > BALL::PeakList1D
1D peak list
typedef PeakList<Peak<Vector2> > BALL::PeakList2D
2D peak list
typedef PeakList<Peak<Vector3> > BALL::PeakList3D
3D peak list
typedef BALL_POINTERSIZEUINT_TYPE BALL::PointerSizeUInt
Unsigned int with the same size as a pointer. Used for internal conversion issues mostly. Size: 32/64 bit (platform dependent)
typedef BALL_SIZE_TYPE BALL::Position
Position type. Use this type to represent positions (e.g. in a container) that cannot be negative (contrary to Index).
Size: 32 bit
persistent
typedef BALL_SIZE_TYPE BALL::Property
Unnamed property type. Use this type to represent (unnamed) properties.
Size: 32 bit
persistent
See also:
PropertyManager
typedef ConstBidirectionalIterator<Composite, Protein, Composite::CompositeIterator, ProteinIteratorTraits> BALL::ProteinConstIterator
typedef std::reverse_iterator<ProteinConstIterator> BALL::ProteinConstReverseIterator
typedef BidirectionalIterator<Composite, Protein, Composite::CompositeIterator,ProteinIteratorTraits> BALL::ProteinIterator
typedef std::reverse_iterator<ProteinIterator> BALL::ProteinReverseIterator
typedef TQuaternion<float> BALL::Quaternion
typedef TReadLocker<BALL_DEFAULT_READLOCKER_TYPE, BALL_DEFAULT_READWRITELOCK_TYPE> BALL::ReadLocker
typedef TReadWriteLock<BALL_DEFAULT_READWRITELOCK_TYPE> BALL::ReadWriteLock
typedef float BALL::Real
Real type. Use this type to represent standard floating point numbers.
Size: 32 bit
persistent
typedef TRegularData1D<float> BALL::RegularData1D
Default type
typedef TRegularData2D<float> BALL::RegularData2D
Default type
typedef TRegularData3D<float> BALL::RegularData3D
Default type
typedef List<RegularData3D*> BALL::RegularData3DList
typedef ConstBidirectionalIterator<Composite, Residue, Composite::CompositeIterator, ResidueIteratorTraits> BALL::ResidueConstIterator
typedef std::reverse_iterator<ResidueConstIterator> BALL::ResidueConstReverseIterator
typedef BidirectionalIterator<Composite, Residue, Composite::CompositeIterator, ResidueIteratorTraits> BALL::ResidueIterator
typedef std::reverse_iterator<ResidueIterator> BALL::ResidueReverseIterator
typedef ConstBidirectionalIterator<Composite, SecondaryStructure, Composite::CompositeIterator, SecondaryStructureIteratorTraits> BALL::SecondaryStructureConstIterator
typedef std::reverse_iterator<SecondaryStructureConstIterator> BALL::SecondaryStructureConstReverseIterator
typedef BidirectionalIterator<Composite, SecondaryStructure, Composite::CompositeIterator, SecondaryStructureIteratorTraits> BALL::SecondaryStructureIterator
typedef std::reverse_iterator<SecondaryStructureIterator> BALL::SecondaryStructureReverseIterator
typedef BALL_SIZE_TYPE BALL::Size
Size type. Use this type to represent sizes of containers, sequences or alike. Variables of type Size are unsigned.
Size: 32 bit
persistent
typedef time_t BALL::Time
Time type. Use this type to represent a point in time (as a replaecement for time_t).
Size: platform dependent
not persistent
typedef TVector3<float> BALL::Vector3
Default three-dimensional vector class. This is the class used in BALL kernel to represent points, coordinates.
typedef TWriteLocker<BALL_DEFAULT_WRITELOCKER_TYPE, BALL_DEFAULT_READWRITELOCK_TYPE> BALL::WriteLocker
Enumeration Type Documentation
enum BALL::ASCII
Enumerator:
ASCII__BACKSPACE
ASCII__BELL
ASCII__CARRIAGE_RETURN
ASCII__HORIZONTAL_TAB
ASCII__NEWLINE
ASCII__RETURN
ASCII__SPACE
ASCII__TAB
ASCII__VERTICAL_TAB
ASCII__COLON
ASCII__COMMA
ASCII__EXCLAMATION_MARK
ASCII__POINT
ASCII__QUESTION_MARK
ASCII__SEMICOLON
Function Documentation
BALL_EXPORT Angle BALL::calculateBondAngle (const Atom & a1, const Atom & a2, const Atom & a3) throw (Exception::IllegalPosition)
Calculate the bond angle between three atoms
BALL_EXPORT BALL_DEPRECATED float BALL::calculateSASArea (const AtomContainer & fragment, float probe_radius = 1.5, Size number_of_dots = 400)
Calculate the solvent accessible surface area numerically. This method returns the total Solvent Accessible Surface (SAS) of a BALL kernel object. Atoms with a radius of 0 are ignored.
Parameters:
fragment the kernel object containing the atoms
probe_radius the probe radius used for the SAS
number_of_dots the number of dots used per atom
Returns:
the total SAS area in $ A^2$
Deprecated:
Use NumericalSAS::getTotalArea() instead
BALL_EXPORT BALL_DEPRECATED float BALL::calculateSASAtomAreas (const AtomContainer & fragment, HashMap< const Atom *, float > & atom_areas, float probe_radius = 1.5, Size number_of_dots = 400)
Calculate the Solvent Accessible Surface area for each atom. This method returns the surface fraction of each atom at the Solvent Accessible Surface (SAS). Atoms with a radius of 0 are ignored. All areas are in $ A^2$.
Parameters:
atom_areas a hash map containing the areas of the atoms (returned)
fragment the kernel object containing the atoms
probe_radius the probe radius used for the SAS
number_of_dots the number of dots used per atom
Returns:
the total SAS area in $ A^2$
Deprecated:
Use NumericalSAS::getAtomAreas() instead
BALL_EXPORT BALL_DEPRECATED float BALL::calculateSASAtomPoints (const AtomContainer & fragment, std::vector< std::pair< Vector3, Surface > > & atom_surfaces, float probe_radius = 1.5, Size number_of_dots = 400)
Calculate a point set on the Solvent Accessible Surface for each atom. This method returns the point sets on the SAS used to calculate the surface area for each atom.
See also:
calculateSASAtomAreas
Parameters:
fragment the kernel object containing the atoms
atom_surfaces a hashmap of atoms and Surface objects containing the point sets for each atom (returned)
probe_radius the probe radius used for the SAS
number_of_dots the number of dots used per atom
Returns:
the total SAS area in $ A^2$
Deprecated:
Use NumericalSAS::getSurfaceMap() instead
BALL_EXPORT BALL_DEPRECATED float BALL::calculateSASPoints (const AtomContainer & fragment, Surface & surface_points, float probe_radius = 1.5, Size number_of_dots = 400)
Calculate a point set on the Solvent Accessible Surface. This method returns the points on the Solvent Accessible Surface (SAS) used to calculate the surface area. The Surface object holds just the vertices, it does not contain any triangles. The normals for each point normals to the SAS in that point, their length equals the fraction of the surface area represented by this point in $ A^2$:
Atoms with a radius of 0 are ignored.
Parameters:
surface_points a surface object containing the point coordinates and their normals (returned)
fragment the kernel object containing the atoms
probe_radius the probe radius used for the SAS
number_of_dots the number of dots used per atom
Returns:
the total SAS area in $ A^2$
Deprecated:
Use NumericalSAS::getSurface() instead
BALL_EXPORT BALL_DEPRECATED float BALL::calculateSASVolume (const AtomContainer & fragment, float probe_radius = 1.5, Size number_of_dots = 400)
Calculate the solvent accessible volume numerically. This method returns the total volume enclosd by the Solvent Accessible Surface (SAS) of a BALL kernel object. Atoms with a radius of 0 are ignored.
Parameters:
fragment the kernel object containing the atoms
probe_radius the probe radius used for the SAS
number_of_dots the number of dots used per atom
Returns:
the volume in $ A^3$
Deprecated:
Use NumericalSAS::getTotalVolume() instead
BALL_EXPORT Angle BALL::calculateTorsionAngle (const Atom & a1, const Atom & a2, const Atom & a3, const Atom & a4) throw (Exception::IllegalPosition)
Calculate the torsion angle between four atoms
template<class NucleotideContainerType > const Nucleotide* BALL::get3Prime (const NucleotideContainerType & nucleotide_container) [inline]
template<class NucleotideContainerType > const Nucleotide* BALL::get5Prime (const NucleotideContainerType & nucleotide_container) [inline]
References BALL::ConstBidirectionalIterator< Container, DataType, Position, Traits >::isEnd().
BALL_EXPORT const FacetArray& BALL::getContourSurfaceFacetData (double threshold)
Referenced by BALL::TContourSurface< T >::operator<<().
template<class ResidueContainerType > const Residue* BALL::getCTerminal (const ResidueContainerType & residue_container) [inline]
Position BALL::getMMFF94Index (Position atom_type1, Position atom_type2)
BALL_EXPORT HashIndex BALL::getNextPrime (HashIndex l)
Calculate the next prime number. This method returns the first prime number that is greater or equal to the number given as the argument. Only odd prime numbers are returned, the lowest number returned is 3.
Referenced by BALL::HashSet< Key >::rehash().
template<class ResidueContainerType > const Residue* BALL::getNTerminal (const ResidueContainerType & residue_container) [inline]
template<> BALL_EXPORT HashIndex BALL::Hash (const std::pair< Position, Position > & p) [inline]
BALL_EXPORT HashIndex BALL::Hash (void *const & ptr) [inline]
Pointer hash function. Use this function to hash pointers to objects.
References hashPointer().
BALL_EXPORT HashIndex BALL::Hash (const String & s) [inline]
String hash function. This method is optimized for the hashing of BALL strings. In fact, it is only an inline wrapper around hashString .
References hashString().
BALL_EXPORT HashIndex BALL::Hash (const string & s) [inline]
String hash function. This method is optimized for the hashing of STL strings. In fact, it is only an inline wrapper around hashString .
References hashString().
template<typename T > HashIndex BALL::Hash (const T & key) [inline]
General default hash function. This method converts a given key to a HashIndex by calling (HashIndex)key. If the key type T is not convertible to HashIndex by default, a converter should be defined (operator HashIndex).
Parameters:
key the key to be hashed
Returns:
HashIndex the hash index
Referenced by BALL::HashSet< Key >::hash(), and BALL::HashFunction< T >::operator()().
BALL_EXPORT HashIndex BALL::hashElfString (const char * str)
BALL_EXPORT HashIndex BALL::hashPJWString (const char * str)
BALL_EXPORT HashIndex BALL::hashPointer (void *const ptr)
Referenced by Hash().
BALL_EXPORT HashIndex BALL::hashString (const char * str)
Referenced by Hash().
template<class Source , class Target > bool BALL::NotificationIsRegistered (const Source & source, const Target & target) [inline]
References BALL::NotificationManager_::isInserted(), and NotificationManager().
template<class NotificationSource > bool BALL::NotificationIsRegistered (const NotificationSource & notification_source) [inline]
References BALL::NotificationManager_::isInserted(), and NotificationManager().
NotificationManager_& BALL::NotificationManager ()
Referenced by NotificationIsRegistered(), NotificationRegister(), NotificationRegister1(), NotificationRegister2(), NotificationSourceDisable(), NotificationSourceEnable(), NotificationSourceIsDisabled(), NotificationSourceIsEnabled(), NotificationUnregister(), NotificationUnregister1(), NotificationUnregister2(), and Notify().
void BALL::NotificationManagerDisable ()
void BALL::NotificationManagerEnable ()
bool BALL::NotificationManagerIsDisabled ()
bool BALL::NotificationManagerIsEnabled ()
template<class Source , class Target > void BALL::NotificationRegister (const Source & source, const Target & target) [inline]
References BALL::NotificationManager_::insert(), and NotificationManager().
template<class Source , class Target , class T1 > void BALL::NotificationRegister1 (const Source & source, const Target & target, const T1 &) [inline]
References BALL::NotificationManager_::insert(), and NotificationManager().
template<class NotificationSource , class NotificationTarget , class T1 , class T2 > void BALL::NotificationRegister2 (const NotificationSource & notification_source, const NotificationTarget & notification_target, const T1 & , const T2 &) [inline]
References BALL::NotificationManager_::insert(), and NotificationManager().
template<class NotificationSource > void BALL::NotificationSourceDisable (NotificationSource & notification_source) [inline]
References BALL::NotificationSource_::disable(), BALL::NotificationManager_::findSource(), and NotificationManager().
template<class NotificationSource > void BALL::NotificationSourceEnable (NotificationSource & notification_source) [inline]
References BALL::NotificationSource_::enable(), BALL::NotificationManager_::findSource(), and NotificationManager().
template<class NotificationSource > bool BALL::NotificationSourceIsDisabled (NotificationSource & notification_source) [inline]
References NotificationManager().
template<class NotificationSource > bool BALL::NotificationSourceIsEnabled (NotificationSource & notification_source) [inline]
References NotificationManager().
template<class Source , class Target > void BALL::NotificationUnregister (const Source & source, const Target & target) [inline]
References NotificationManager(), and BALL::NotificationManager_::remove().
template<class NotificationSource > void BALL::NotificationUnregister (const NotificationSource & notification_source) [inline]
References NotificationManager(), and BALL::NotificationManager_::remove().
template<class NotificationSource , class NotificationTarget , class T1 > void BALL::NotificationUnregister1 (const NotificationSource & notification_source, const NotificationTarget & notification_target, const T1 &) [inline]
References NotificationManager(), and BALL::NotificationManager_::remove().
template<class NotificationSource , class NotificationTarget , class T1 , class T2 > void BALL::NotificationUnregister2 (const NotificationSource & notification_source, const NotificationTarget & notification_target, const T1 & , const T2 &) [inline]
References NotificationManager(), and BALL::NotificationManager_::remove().
void BALL::NotificationUnregisterAll ()
template<class NotificationSource , class T1 , class T2 > bool BALL::Notify (NotificationSource & notification_source, const T1 & data1, const T2 & data2) [inline]
References BALL::NotificationTarget2< NotificationSource, T1, T2 >::countNotificationTypes_(), BALL::NotificationTarget2< NotificationSource, T1, T2 >::getNotificationType_(), BALL::NotificationTarget2< NotificationSource, T1, T2 >::getVirtualNotificationType_(), and NotificationManager().
template<class NotificationSource , class T1 > bool BALL::Notify (NotificationSource & notification_source, const T1 & data1) [inline]
References BALL::NotificationTarget1< NotificationSource, T1 >::countNotificationTypes_(), BALL::NotificationTarget1< NotificationSource, T1 >::getNotificationType_(), and NotificationManager().
template<class NotificationSource > bool BALL::Notify (NotificationSource & notification_source) [inline]
References BALL::NotificationTarget< NotificationSource >::countNotificationTypes_(), BALL::NotificationTarget< NotificationSource >::getNotificationType_(), BALL::NotificationTarget< NotificationSource >::getVirtualNotificationType_(), NotificationManager(), and BALL::NotificationTarget< NotificationSource >::onNotify().
template<typename T > TVector3<T> BALL::operator* (const TMatrix4x4< T > & matrix, const TVector3< T > & vector) [inline]
References BALL::TMatrix4x4< T >::m11, BALL::TMatrix4x4< T >::m12, BALL::TMatrix4x4< T >::m13, BALL::TMatrix4x4< T >::m14, BALL::TMatrix4x4< T >::m21, BALL::TMatrix4x4< T >::m22, BALL::TMatrix4x4< T >::m23, BALL::TMatrix4x4< T >::m24, BALL::TMatrix4x4< T >::m31, BALL::TMatrix4x4< T >::m32, BALL::TMatrix4x4< T >::m33, BALL::TMatrix4x4< T >::m34, BALL::TVector3< T >::x, BALL::TVector3< T >::y, and BALL::TVector3< T >::z.
template<typename T > TMatrix4x4< T > BALL::operator* (const T & scalar, const TMatrix4x4< T > & m) [inline]
References BALL::TMatrix4x4< T >::m11, BALL::TMatrix4x4< T >::m12, BALL::TMatrix4x4< T >::m13, BALL::TMatrix4x4< T >::m14, BALL::TMatrix4x4< T >::m21, BALL::TMatrix4x4< T >::m22, BALL::TMatrix4x4< T >::m23, BALL::TMatrix4x4< T >::m24, BALL::TMatrix4x4< T >::m31, BALL::TMatrix4x4< T >::m32, BALL::TMatrix4x4< T >::m33, BALL::TMatrix4x4< T >::m34, BALL::TMatrix4x4< T >::m41, BALL::TMatrix4x4< T >::m42, BALL::TMatrix4x4< T >::m43, and BALL::TMatrix4x4< T >::m44.
template<typename Container , typename DataType , typename Position , typename Traits > ConstRandomAccessIterator<Container, DataType, Position, Traits> BALL::operator+ (Distance distance, const ConstRandomAccessIterator< Container, DataType, Position, Traits > & iterator) throw (Exception::InvalidIterator) [inline]
Return an incremented iterator. It points to the element with the given distance from the element of the given iterator.
template<typename DataT , typename PeakT , typename PositionT > double BALL::operator- (const Spectrum< DataT, PeakT, PositionT > & s1, const Spectrum< DataT, PeakT, PositionT > & s2) [inline]
Difference operator. Calculate the sum of the unsigned differences of the two spectra
References BALL::Spectrum< DataT, PeakT, PositionT >::difference().
template<typename T > std::ostream& BALL::operator<< (std::ostream & os, const BinaryFileAdaptor< T > & data) [inline]
Output stream for BinaryFileAdaptors.
References swapBytes().
BALL_EXPORT std::ostream& BALL::operator<< (std::ostream & s, const TriangulatedSurface & surface)
Output- Operator
BALL_EXPORT std::ostream& BALL::operator<< (std::ostream & s, const TrianglePoint & point)
Output- Operator
BALL_EXPORT std::ostream& BALL::operator<< (std::ostream & s, const TriangleEdge & edge)
Output- Operator
BALL_EXPORT std::ostream& BALL::operator<< (std::ostream & s, const Triangle & triangle)
Output- Operator
BALL_EXPORT std::ostream& BALL::operator<< (std::ostream & s, const SolventExcludedSurface & ses)
Output- Operator
BALL_EXPORT std::ostream& BALL::operator<< (std::ostream & s, const SolventAccessibleSurface & sas)
Output- Operator
BALL_EXPORT std::ostream& BALL::operator<< (std::ostream & s, const SESVertex & sesvertex)
Output- Operator
BALL_EXPORT std::ostream& BALL::operator<< (std::ostream & s, const SESFace & sesface)
Output- Operator
BALL_EXPORT std::ostream& BALL::operator<< (std::ostream & s, const SESEdge & sesedge)
Output- Operator
BALL_EXPORT std::ostream& BALL::operator<< (std::ostream & s, const SASVertex & sasvertex)
Output- Operator
BALL_EXPORT std::ostream& BALL::operator<< (std::ostream & s, const SASFace & sasface)
Output- Operator
BALL_EXPORT std::ostream& BALL::operator<< (std::ostream & s, const SASEdge & sasedge)
Output- Operator
BALL_EXPORT std::ostream& BALL::operator<< (std::ostream & s, const RSVertex & rsvertex)
Output- Operator prints out a rsvertex
BALL_EXPORT std::ostream& BALL::operator<< (std::ostream & s, const RSFace & rsface)
Output- Operator
BALL_EXPORT std::ostream& BALL::operator<< (std::ostream & s, const RSEdge & rsedge)
Output- Operator
BALL_EXPORT std::ostream& BALL::operator<< (std::ostream & s, const ReducedSurface & rs)
Output- Operator. Prints out a ReducedSurface
template<typename Node , typename Edge > std::ostream& BALL::operator<< (std::ostream & os, const TMolecularGraph< Node, Edge > & G) [inline]
References BALL::TMolecularGraph< Node, Edge >::beginEdge(), BALL::TMolecularGraph< Node, Edge >::endEdge(), and BALL::TMolecularGraph< Node, Edge >::endNode().
std::ostream& BALL::operator<< (std::ostream & out, const DockResult & dock_res)
Operator to write dock result into an ostream. Calls writeDockResult(std::ostream& file).
template<typename PositionType > std::ostream& BALL::operator<< (std::ostream & os, const Peak< PositionType > & peak) [inline]
Output operator
::std::ostream& BALL::operator<< (::std::ostream & os, const SnapShot & ss)
Output stream operator for SnapShots.
template<typename T > std::ostream& BALL::operator<< (std::ostream & s, const TSphere3< T > & sphere) [inline]
Output Operator. Write the contents of p and radius to an output stream. The values are enclose in brackets.
Example:
((0 1 1.5) 0.4)
template<typename T > std::ostream& BALL::operator<< (std::ostream & s, const TQuaternion< T > & q) [inline]
template<typename ComplexTraits > const RegularData3D& BALL::operator<< (RegularData3D & to, const TFFT3D< ComplexTraits > & from) [inline]
Global assignment operator from TFFT3D to TRegularData3D<float>. This operator assigns the real part of the complex TFFT3D-data to the TRegularData3D<float> to.
template<typename ComplexTraits > const TRegularData3D< typename TFFT3D< ComplexTraits >::Complex > & BALL::operator<< (TRegularData3D< typename TFFT3D< ComplexTraits >::Complex > & to, const TFFT3D< ComplexTraits > & from) [inline]
Global assignment operator from TFFT3D to TRegularData3D<Complex>
References BALL::TVector3< T >::set().
template<typename ComplexTraits > const RegularData2D& BALL::operator<< (RegularData2D & to, const TFFT2D< ComplexTraits > & from) [inline]
Global assignment operator from FFT3D to TRegularData3D<float>. This operator assigns the real part of the complex TFFT2D-data to the TRegularData2D<float> to.
template<typename ComplexTraits > const TRegularData2D< typename TFFT2D< ComplexTraits >::Complex > & BALL::operator<< (TRegularData2D< typename TFFT2D< ComplexTraits >::Complex > & to, const TFFT2D< ComplexTraits > & from) [inline]
Global assignment operator from TFFT2D to TRegularData2D<Complex>
References BALL::TVector2< T >::set().
template<typename ComplexTraits > const RegularData1D& BALL::operator<< (RegularData1D & to, const TFFT1D< ComplexTraits > & from) [inline]
References BALL::TRegularData1D< ValueType >::setDimension(), and BALL::TRegularData1D< ValueType >::setOrigin().
template<typename T > std::ostream& BALL::operator<< (std::ostream & s, const TBox3< T > & box) [inline]
Output Operator. Writes the two coordinates of the box to an output stream. The vectors are enclosed by brackets.
Example:
((0 1 2) (7.5 3.4 10))
See also:
TVector3::operator<<
template<typename T > std::ostream& BALL::operator<< (std::ostream & s, const TAngle< T > & angle) [inline]
Output Operator. Writes the value of the angle to an output stream. The stream operator operator << has to be defined for the template parameter T.
std::ostream& BALL::operator<< (std::ostream & s, const NMRAtomDataSet & set)
std::ostream& BALL::operator<< (std::ostream & s, const ShiftReferenceSet & sr)
std::ostream& BALL::operator<< (std::ostream & s, const ShiftReferenceElement & sre)
std::ostream& BALL::operator<< (std::ostream & s, const SampleCondition & sc)
std::ostream& BALL::operator<< (std::ostream & s, const NMRAtomData & ad)
template<typename ValueType > std::ostream& BALL::operator<< (std::ostream & os, const TRegularData3D< ValueType > & grid) [inline]
Output operator.
template<typename ValueType > std::ostream& BALL::operator<< (std::ostream & os, const TRegularData2D< ValueType > & data) [inline]
Output operator.
template<typename ValueType > std::ostream& BALL::operator<< (std::ostream & os, const TRegularData1D< ValueType > & data) [inline]
Output operator.
BALL_EXPORT std::ostream& BALL::operator<< (std::ostream & os, const TimeStamp & stamp)
Print the contents of a TimeStamp object to a stream.
BALL_EXPORT std::ostream& BALL::operator<< (std::ostream & os, const PreciseTime & time)
Global stream operators for PreciseTime and TimeStamp Print the contents of a PreciseTime object to a stream.
template<typename T > std::istream& BALL::operator>> (std::istream & is, BinaryFileAdaptor< T > & data) [inline]
Input stream for BinaryFileAdaptors.
References BALL::BinaryFileAdaptor< T >::getData(), BALL::BinaryFileAdaptor< T >::getSwapEndian(), BALL::BinaryFileAdaptor< T >::setData(), and swapBytes().
std::istream& BALL::operator>> (std::istream & in, DockResult & dock_res)
Operator to read dock result into an istream. Calls readDockResult(std::istream& file) .
::std::istream& BALL::operator>> (::std::istream & is, SnapShot & ss)
Input stream operator for SnapShots.
template<typename T > std::istream& BALL::operator>> (std::istream & s, TSphere3< T > & sphere) [inline]
Input operator. Reads in an instance of TVector3 and a T value : p, radius.
References BALL::Constants::c, BALL::TSphere3< T >::p, and BALL::TSphere3< T >::radius.
template<typename T > std::istream& BALL::operator>> (std::istream & s, TQuaternion< T > & q) [inline]
References BALL::Constants::c, BALL::TQuaternion< T >::i(), BALL::TQuaternion< T >::j(), BALL::TQuaternion< T >::k(), and BALL::TQuaternion< T >::w().
template<typename T > std::istream& BALL::operator>> (std::istream & s, TBox3< T > & box) [inline]
Input operator. Reads in two objects of type TVector3 a and b
References BALL::TBox3< T >::setDepth(), BALL::TBox3< T >::setHeightVector(), BALL::TBox3< T >::setPoint(), and BALL::TBox3< T >::setRightVector().
template<typename T > std::istream& BALL::operator>> (std::istream & s, TAngle< T > & angle) [inline]
Input Operator. Reads the value (in radians) of an angle from an instream using T::operator >>
References BALL::Constants::c, and BALL::TAngle< T >::value.
template<typename ValueType > std::istream& BALL::operator>> (std::istream & is, TRegularData3D< ValueType > & grid) [inline]
Input operator.
References BALL::TRegularData3D< ValueType >::begin(), BALL::TRegularData3D< ValueType >::resize(), BALL::TRegularData3D< ValueType >::setDimension(), BALL::TRegularData3D< ValueType >::setOrigin(), BALL::TRegularData3D< ValueType >::IndexType::x, BALL::TVector3< T >::x, BALL::TRegularData3D< ValueType >::IndexType::y, BALL::TVector3< T >::y, BALL::TRegularData3D< ValueType >::IndexType::z, and BALL::TVector3< T >::z.
template<typename ValueType > std::istream& BALL::operator>> (std::istream & is, TRegularData2D< ValueType > & grid) [inline]
Input operator.
References BALL::TRegularData2D< ValueType >::begin(), BALL::TRegularData2D< ValueType >::resize(), BALL::TRegularData2D< ValueType >::setDimension(), BALL::TRegularData2D< ValueType >::setOrigin(), BALL::TRegularData2D< ValueType >::IndexType::x, BALL::TVector2< T >::x, BALL::TRegularData2D< ValueType >::IndexType::y, and BALL::TVector2< T >::y.
template<typename ValueType > std::istream& BALL::operator>> (std::istream & is, TRegularData1D< ValueType > & grid) [inline]
Input operator.
References BALL::TRegularData1D< ValueType >::begin(), BALL::TRegularData1D< ValueType >::resize(), BALL::TRegularData1D< ValueType >::setDimension(), and BALL::TRegularData1D< ValueType >::setOrigin().
BALL_EXPORT void BALL::sleepFor (Size mseconds)
template<typename T > BALL_INLINE void BALL::swapBytes (T & t) [inline]
Coping with endianness. This function swaps the bytes of a variable of type T if this type is of size 2n.
References BALL::LogStream::error(), and Log.
Referenced by operator<<(), and operator>>().
Variable Documentation
BALL_EXPORT const char BALL::CCONN__INSIDE
BALL_EXPORT const char BALL::CCONN__INSIDE_PROBE
BALL_EXPORT const char BALL::CCONN__OUTSIDE
const Distance BALL::DISTANCE_MAX = INT_MAX [static]
const Distance BALL::DISTANCE_MIN = (INT_MIN + 1) [static]
const Handle BALL::HANDLE_MAX = INT_MAX - 1 [static]
const Handle BALL::HANDLE_MIN = 0 [static]
const Index BALL::INDEX_MAX = INT_MAX [static]
const Index BALL::INDEX_MIN = 0 [static]
const double BALL::INFINITY = Limits<double>::max() [static]
const Distance BALL::INVALID_DISTANCE = INT_MIN [static]
const Handle BALL::INVALID_HANDLE = INT_MAX [static]
const Index BALL::INVALID_INDEX = -1 [static]
Referenced by BALL::ResourceEntry::IteratorTraits_::forward(), BALL::HashGrid3< Item >::getIndex_(), BALL::HashGrid3< Item >::getIndices(), and BALL::ResourceEntry::IteratorTraits_::pop().
const Position BALL::INVALID_POSITION = INT_MAX [static]
Referenced by BALL::HashGrid3< Item >::getIndices(), and BALL::HashSet< Key >::IteratorTraits::invalidate().
const Size BALL::INVALID_SIZE = INT_MAX [static]
BALL_EXPORT LogStream BALL::Log
Global static instance of a logstream. This instance of LogStream is by default bound to cout cerr by calling the default constructor.
Referenced by BALL::VIEW::DemoTutorialDialog::DemoTutorialDialog(), BALL::AssignBondOrderProcessor::getNumberOfAddedHydrogens(), BALL::AssignBondOrderProcessor::getNumberOfNodeExpansions(), BALL::AssignBondOrderProcessor::getQueueSize(), BALL::AssignBondOrderProcessor::getTotalCharge(), BALL::AssignBondOrderProcessor::getTotalPenalty(), logMessages(), BALL::Mainframe::Mainframe(), BALL::VIEW::DemoTutorialDialog::nextStepDemo_(), BALL::VIEW::DemoTutorialDialog::onNotifyTutorial_(), BALL::ConnectedToPredicate::CTPNode::greater_::operator()(), BALL::VIEW::Renderer::renderBox_(), BALL::VIEW::Renderer::renderClippingPlane_(), BALL::VIEW::Renderer::renderDisc_(), BALL::VIEW::Renderer::renderGridVisualisation_(), BALL::VIEW::Renderer::renderLabel_(), BALL::VIEW::Renderer::renderLine_(), BALL::VIEW::Renderer::renderMesh_(), BALL::VIEW::Renderer::renderMultiLine_(), BALL::VIEW::Renderer::renderPoint_(), BALL::VIEW::Renderer::renderQuadMesh_(), BALL::VIEW::Renderer::renderSimpleBox_(), BALL::VIEW::Renderer::renderSphere_(), BALL::VIEW::Renderer::renderTube_(), BALL::VIEW::Renderer::renderTwoColoredLine_(), BALL::VIEW::Renderer::renderTwoColoredTube_(), swapBytes(), and BALL::VIEW::DemoTutorialDialog::~DemoTutorialDialog().
Size BALL::MMFF94_number_atom_types
hold the maximum number of MMFF94 atom types + 1 (wildcard)
const Position BALL::POSITION_MAX = INT_MAX - 1 [static]
const Position BALL::POSITION_MIN = 0 [static]
const Size BALL::SIZE_MAX = INT_MAX - 1 [static]
const Size BALL::SIZE_MIN = 0 [static]