BALL::PDB::Structure::AtomEntry Struct Reference
#include <BALL/FORMAT/PDBdefs.h>
Public Member Functions
AtomEntry (const BALL::Atom &a)
Public Attributes
const BALL::Atom * atom
const BALL::Residue * residue
const BALL::SecondaryStructure * sec_struct
const BALL::Chain * chain
Constructor & Destructor Documentation
BALL::PDB::Structure::AtomEntry::AtomEntry (const BALL::Atom & a) [inline]
References BALL::Atom::getChain(), BALL::Atom::getResidue(), and BALL::Atom::getSecondaryStructure().
Member Data Documentation
const BALL::Atom* BALL::PDB::Structure::AtomEntry::atom
const BALL::Chain* BALL::PDB::Structure::AtomEntry::chain
const BALL::Residue* BALL::PDB::Structure::AtomEntry::residue
const BALL::SecondaryStructure* BALL::PDB::Structure::AtomEntry::sec_struct